create phing target to change environment
shopsys/shopsys pull request #1951
Opened 2020-07-24 08:02 UTC by malyMiso

| Q             | A
| ------------- | ---
|Description, reason for the PR| programmer can easily switch to desired environment. There is a protection to run command in production environment.
|New feature| Yes 
|[BC breaks] No 
|Fixes issues| closes #1744  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-08-27 11:38 UTC, TomasLudvik requested changes

2020-08-27 11:38 UTC, TomasLudvik commented on docs/introduction/console-commands-for-application-management-phing-targets.md
> +Switching to development environment will also install dev dependencies of composer.
```suggestion
Switching to development environment will also install composer dev dependencies.
```

2020-08-27 11:38 UTC, TomasLudvik commented on docs/introduction/console-commands-for-application-management-phing-targets.md
> +Change environment easily by this target.
```suggestion
!!! important
    Do not use this target on your production server, because it could cause some security vulnerabilities.
```

2020-08-27 11:38 UTC, TomasLudvik commented on docs/introduction/console-commands-for-application-management-phing-targets.md
> +Currently, you can switch to production, development or test enviroment.
```suggestion
```

2020-08-27 11:38 UTC, TomasLudvik commented on docs/introduction/console-commands-for-application-management-phing-targets.md
> +It can be handy in production environment, when you need to debug some functionality on testing server.
```suggestion
Change environment to production, development or test using this target.
This target is hand when you need to debug some functionality on your development / testing server.
```

2020-08-27 11:38 UTC, TomasLudvik commented on packages/framework/build.xml
> +    <target name="environment-change" depends="production-protection" description="Change application environment with installing environment related dependencies.">
```suggestion
    <target name="environment-change" depends="production-protection" description="Change application environment and install composer dev-dependencies when development environment is selected.">
```

2020-08-28 06:27 UTC, TomasLudvik approved these changes

2020-08-28 11:24 UTC, TomasLudvik commented on packages/framework/build.xml
> +        <input propertyName="change.environment" validArgs="dev,prod,test" defaultValue="dev" message="Select environment you want to change to"/>
```suggestion
        <input propertyName="change.environment" validArgs="dev, prod, test" defaultValue="prod" message="Select environment you want to change to"/>
```

2020-08-28 11:26 UTC, TomasLudvik commented
From tests I found that you should change parameter of `Environment::getEnvironment` to `false` in `project-base/app/getEnvironment.php` so this works correctly in `test` environment

2020-08-28 13:17 UTC, s3tezsky commented
> From tests I found that you should change parameter of Environment::getEnvironment to false in project-base/app/getEnvironment.php so this works correctly in test environment

Solved in #2009

2020-08-28 13:39 UTC, TomasLudvik approved these changes

2020-08-29 10:17 UTC, sslt approved these changes

2020-08-31 06:41 UTC, merged