[shopsys] add brands to frontend API
shopsys/shopsys pull request #2047
Opened 2020-09-24 09:20 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| We want to add everything to frontend API that could be displayed on frontend. This PR adds brands.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-09-24 15:32 UTC, grossmannmartin requested changes
nice work!

can you chek please my comments?

2020-09-25 08:18 UTC, TomasLudvik commented on packages/frontend-api/apiary.apib
> +            uuid
Well US does not say anything about that. Also when some eshop have side with brands list it mostly is not paginated.

2020-09-25 08:27 UTC, TomasLudvik commented on packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
> +                    return $this->brandFacade->getById($data['brand']);
fixed in 691724a42415505235252f2682caf7d027f3c89d

2020-09-25 09:00 UTC, grossmannmartin commented on packages/frontend-api/apiary.apib
> +            uuid
Okay 👍

2020-09-25 09:00 UTC, grossmannmartin approved these changes

2020-09-25 12:46 UTC, sslt approved these changes

2020-09-25 13:06 UTC, merged