[shopsys] autocompletion for Phing targets
shopsys/shopsys pull request #2049
Opened 2020-09-24 13:46 UTC by grossmannmartin

- documentation: reordered navigation in introduction section
- added autocompletion for phing in php-fpm container
- added autocompletion for phing targets documentation

| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| Yes/No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes/No

2020-09-25 08:42 UTC, TomasLudvik approved these changes

2020-09-25 09:28 UTC, TomasLudvik requested changes
Hi, nice job!

From testing I found one small change in code and one interesting problem. If I first run `alias dphing='docker-compose exec php-fpm ./phing'`, then I close my terminal and open again, alias is lost. It is not persisted.

2020-09-25 09:28 UTC, TomasLudvik commented on docs/introduction/autocompletion-for-phing-targets.md
> +Store this file in `/etc/bash_completion.d/dphing` on Linux, or in `usr/local/etc/bash_completion.d/dphing` on MacOS.
```suggestion
Store this file in `/etc/bash_completion.d/dphing` on Linux, or in `/usr/local/etc/bash_completion.d/dphing` on MacOS.
```

2020-09-25 09:42 UTC, grossmannmartin commented
> Hi, nice job!
> 
> From testing I found one small change in code and one interesting problem. If I first run `alias dphing='docker-compose exec php-fpm ./phing'`, then I close my terminal and open again, alias is lost. It is not persisted.

Yes, it's standard alias behavior. I added a note about it in 920b5987c

2020-09-25 13:03 UTC, TomasLudvik approved these changes

2020-09-29 05:50 UTC, sslt approved these changes

2020-09-29 06:31 UTC, merged