[shopsys] fixed wrong generated demodata for different number of domains than 2
shopsys/shopsys pull request #2051
Opened 2020-09-25 12:01 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| Wher we are not running exactly 2 domain the faker will generate different created date to order so some tests will fail (when they are dependent on sorted orders). This PR removes faker for datetime.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-09-25 13:24 UTC, grossmannmartin requested changes

2020-09-25 13:46 UTC, s3tezsky commented on project-base/config/domains.yaml
> -        styles_directory: domain2
It servse for easiear testing 6d6907d1d4a82d0d05d8a48461d9220f22fb88b0 but it wil not be merged

2020-09-29 06:33 UTC, grossmannmartin commented on project-base/config/domains.yaml
> -        styles_directory: domain2
Oh, I missed that, okay

2020-09-29 06:33 UTC, grossmannmartin approved these changes

2020-09-29 13:40 UTC, sslt approved these changes

2020-09-29 17:48 UTC, merged