[project-base] tail logs unbuffered
shopsys/shopsys pull request #2103
Opened 2020-11-07 16:37 UTC by henzigo

| Q             | A
| ------------- | ---
|Description, reason for the PR| By default, `tail` command output is buffered by 8KB when it runs in the background. Because of this, some logs can be missed or there can be delayed to see logs. More information can be found here:https://superuser.com/questions/742238/piping-tail-f-into-awk/1123674#1123674 and https://unix.stackexchange.com/questions/46723/flush-tail-f-buffer
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-11-16 09:46 UTC, s3tezsky approved these changes

2020-11-18 11:34 UTC, TomasLudvik requested changes
Hello, nice job. @s3tezsky can you please add UPGRADE notes?

2020-11-18 12:11 UTC, s3tezsky commented
> Hello, nice job. @s3tezsky can you please add UPGRADE notes?

When the only issue is missing upgrade notes, feel free to add them 😉

2020-11-18 12:57 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.0-dev.md
> +    - see #project-base-diff to update your project
```suggestion
- avoid missing or delayed logs ([#2103](https://github.com/shopsys/shopsys/pull/2103))
    - see #project-base-diff to update your project
```

2020-11-19 09:12 UTC, grossmannmartin approved these changes

2020-11-19 09:12 UTC, TomasLudvik approved these changes

2020-11-19 09:21 UTC, sslt approved these changes

2020-11-19 11:25 UTC, merged