[project-base] disable validation for product filter form
shopsys/shopsys pull request #2104
Opened 2020-11-07 21:32 UTC by henzigo

| Q             | A
| ------------- | ---
|Description, reason for the PR| JS validation consuming a lot of compute power and increase HTML output even if there is no validation needed.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-11-16 09:38 UTC, s3tezsky approved these changes
Nice point, thanks!

2020-11-18 11:33 UTC, TomasLudvik requested changes
Nice job, @s3tezsky can you please add UPGRADE notes?

2020-11-18 12:09 UTC, s3tezsky commented
> Nice job, @s3tezsky can you please add UPGRADE notes?

It is up! I would not be mad at you when you add it by yourself 😉

2020-11-18 12:54 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.0-dev.md
> +    - see #project-base-diff to update your project
```suggestion
- disable javascript validation for product filter form ([#2104](https://github.com/shopsys/shopsys/pull/2104))
    - see #project-base-diff to update your project
```

2020-11-19 09:03 UTC, TomasLudvik approved these changes

2020-11-19 09:12 UTC, grossmannmartin approved these changes

2020-11-19 09:19 UTC, sslt approved these changes

2020-11-19 12:46 UTC, merged