[project-base] enabled logging in tests
shopsys/shopsys pull request #2113
Opened 2020-11-10 09:49 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| Logging in tests was disabled which lead to harder debugging of problems with tests. Now we have enabled logging of level WARNING or higher, so only important informations are logged.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-11-10 11:29 UTC, grossmannmartin requested changes

2020-11-11 10:13 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.0-dev.md
> +- enable logging in tests ([#](https://github.com/shopsys/shopsys/pull/))
Ofc, thx for noticing.

2020-11-11 10:23 UTC, grossmannmartin approved these changes

2020-11-12 17:40 UTC, sslt approved these changes

2020-11-13 11:23 UTC, merged