[frontend-api] Timmed string type
shopsys/shopsys pull request #2127
Opened 2020-11-18 11:55 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| All string input is trimmed. To prevent trimming passwords there was introduced a new type `Password` which do not manipulate with the values.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| fixes #2111  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2020-11-19 13:13 UTC, TomasLudvik requested changes

2020-11-19 13:13 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.0-dev.md
> +- trimmed String type and new Password type in frontend API ([#2127](https://github.com/shopsys/shopsys/pull/2127))
```suggestion
- add automatic string trimming and new Password type for frontend API ([#2127](https://github.com/shopsys/shopsys/pull/2127))
```

2020-11-20 08:33 UTC, s3tezsky commented
Fixed the commit message.

Also it is rebased on #2119 because of used trim there.

2020-11-20 08:56 UTC, TomasLudvik approved these changes

2020-11-23 09:49 UTC, sslt approved these changes

2020-11-23 11:35 UTC, merged