[coding-standards] added support for symfony5
shopsys/shopsys pull request #2183
Opened 2021-01-12 10:33 UTC by pesektomas

| Q             | A
| ------------- | ---
|Description, reason for the PR| added support for symfony5 for coding standards package
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-01-27 15:48 UTC, TomasLudvik approved these changes

2021-01-28 07:17 UTC, grossmannmartin requested changes
Hi, 
I improved Travis configuration, so this package is tested with Symfony 4 and Symfony 5.

Bun unfortunately it seems like there is a bug in Symplify/easy-coding-standards library, which means it's not Symfony 5 compatible. see https://travis-ci.org/github/shopsys/coding-standards/builds/756437210

2021-01-28 07:50 UTC, s3tezsky commented
Please change the target to 9.1 instead of master 🙏 .

2021-02-02 12:50 UTC, grossmannmartin approved these changes

2021-02-02 12:52 UTC, sslt approved these changes

2021-02-02 13:18 UTC, merged