Set CountryDomain as multi domain entity
shopsys/shopsys pull request #2191
Opened 2021-01-15 06:06 UTC by stanoMilan

| Q             | A
| ------------- | ---
|Description, reason for the PR| Adding new domains does not create country domain data
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

Pri pridávaní nových domén do projektu sa nevytvorili multidoménové dáta pre krajiny.

2021-01-27 15:45 UTC, TomasLudvik approved these changes
Hello @stanoMilan, nice catch! Thank you

2021-01-28 07:28 UTC, grossmannmartin approved these changes
Cool!

2021-01-28 07:30 UTC, sslt approved these changes

2021-01-28 07:47 UTC, s3tezsky requested changes
Please change the target to 9.1 instead of master 🙏 .

2021-02-02 10:23 UTC, s3tezsky approved these changes

2021-02-02 10:24 UTC, merged