[shopsys] product decorators inherit all fields from product type
shopsys/shopsys pull request #2195
Opened 2021-01-18 14:05 UTC by malyMiso

| Q             | A
| ------------- | ---
|Description, reason for the PR| product decorators are correctly configured to inherit all fields from product type.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No (But I'm not sure) 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-01-18 14:38 UTC, malyMiso commented
It solves one issue mentioned in https://github.com/shopsys/shopsys/issues/2168

> After extending ProductResolverMap I thought I was ready, so I ran some queries. Unfortunately, queries failed, because newly defined field weight was unknown to RegularProduct, MainVariant, Variant. I solved it by copying field definition to the rest types.
> What is the best way to extend Product type ?

2021-01-27 15:37 UTC, TomasLudvik approved these changes

2021-01-28 06:12 UTC, grossmannmartin approved these changes

2021-01-28 06:19 UTC, grossmannmartin commented
good job! I created #2208 to address this issue in other inherited types

2021-01-28 06:30 UTC, sslt approved these changes

2021-01-28 07:47 UTC, s3tezsky requested changes
Please change the target to 9.1 instead of master 🙏 .

2021-02-02 11:14 UTC, s3tezsky approved these changes

2021-02-02 11:28 UTC, merged