use `CategoryResolverMap` as an example of `ResolverMap` in FE API introduction
shopsys/shopsys pull request #2196
Opened 2021-01-18 14:31 UTC by malyMiso

| Q             | A
| ------------- | ---
|Description, reason for the PR| `ProductResolverMap::map()` has been changed, since introducing `ProductEntityFieldMapper` and `ProductArrayFieldMapper` in  SSFW 9.1. There is also custom section called `ProductResolverMap`.I think it would be better to use `CategoryResolverMap` as an example of `ResolverMap` for better understanding how resolver mappers work (Anyone can look at current implementation of `CategoryResolverMap`).
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-01-27 15:34 UTC, TomasLudvik approved these changes

2021-01-28 06:10 UTC, grossmannmartin approved these changes

2021-01-28 06:33 UTC, sslt approved these changes

2021-01-28 07:46 UTC, s3tezsky requested changes
Please change the target to 9.1 instead of master 🙏 .

2021-02-02 11:31 UTC, s3tezsky approved these changes

2021-02-02 12:21 UTC, merged