Payment price is required
shopsys/shopsys pull request #2201
Opened 2021-01-21 07:55 UTC by stanoMilan

| Q             | A
| ------------- | ---
|Description, reason for the PR| Payment price is required 
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

Payment price must be `Price!` because `Shopsys\FrontendApiBundle\Model\Resolver\Price::resolveByPayment` return always object of `\Shopsys\FrameworkBundle\Model\Pricing\Price`

2021-01-27 16:36 UTC, TomasLudvik approved these changes
Hello @stanoMilan, nice job, thank you!

2021-01-28 06:24 UTC, grossmannmartin approved these changes

2021-01-28 06:29 UTC, sslt approved these changes

2021-01-28 07:45 UTC, s3tezsky requested changes
Please change the target to 9.1 instead of master 🙏

2021-02-02 10:51 UTC, s3tezsky approved these changes

2021-02-02 11:09 UTC, merged