[framework] empty strings are stored as null if possible
shopsys/shopsys pull request #2206
Opened 2021-01-27 09:17 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| We use nullable datatype in our database schema but actually we are saving empty string on many places. This PR unifies saving those empty strings (each of them is converted to null) to prevent confusions.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1735  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-01-27 15:07 UTC, TomasLudvik requested changes
Hey, nice job, it is only missing one thing - trimming of the text, so we are sure, there are no names with white space. We have agreed on this here https://github.com/shopsys/shopsys/pull/1735#issuecomment-756656009

2021-01-28 08:57 UTC, TomasLudvik requested changes

2021-01-28 08:57 UTC, TomasLudvik commented on packages/framework/src/Component/String/TransformString.php
> +    public static function sanitizeInput(?string $value): ?string
From the name it is not clear what is being sanitized - that it is empty or whitespace string

2021-01-28 08:57 UTC, TomasLudvik commented on packages/framework/src/Migrations/Version20210127085903.php
> +        $this->sql('UPDATE category_translations SET name = NULL WHERE name = \'\'');
You need to trim even here in SQL like:
```suggestion
        $this->sql('UPDATE category_translations SET name = NULL WHERE TRIM(name) = \'\'');
```

2021-01-29 10:33 UTC, TomasLudvik approved these changes

2021-02-01 06:47 UTC, sslt approved these changes

2021-02-02 09:08 UTC, merged