[shopsys] exception is now caught when main category does not exist
shopsys/shopsys pull request #2224
Opened 2021-02-02 17:52 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| When main category of product was removed or hidden the detail of procut thrown error 500. This PR cathces exception which caused this problem.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| #2182  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-02-03 14:43 UTC, TomasLudvik requested changes

2021-02-03 14:43 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        }
You should use `CategoryFacade::findProductMainCategoryByDomainId()` instead

2021-02-03 14:43 UTC, TomasLudvik commented on packages/framework/src/Model/Product/ProductBreadcrumbGenerator.php
```suggestion
        $productMainCategory = $this->categoryFacade->findProductMainCategoryByDomainId(
            $product,
                $this->domain->getId()
            );

        $breadcrumbItems = [];

        if ($productMainCategory !== null) {
            $breadcrumbItems = $this->getCategoryBreadcrumbItems($productMainCategory);
        }
```

2021-02-03 14:43 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.1-dev.md
> +- catch exception to prevent error 500 on product detail when main category is hidden or removed ([#2224](https://github.com/shopsys/shopsys/pull/2224))
```suggestion
- prevent error 500 on product detail when main category is hidden or removed ([#2224](https://github.com/shopsys/shopsys/pull/2224))
```

2021-02-03 14:43 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.1-dev.md
> +    - - see #project-base-diff to update your project
```suggestion
      - see #project-base-diff to update your project
```

2021-02-03 14:43 UTC, TomasLudvik commented on project-base/src/Model/Category/CurrentCategoryResolver.php
> +            }
```suggestion
            /** @var \App\Model\Category\Category $currentCategory */
            $currentCategory = $this->categoryFacade->findProductMainCategoryOnDomain($product, $domainId);
```

2021-02-08 10:18 UTC, TomasLudvik approved these changes

2021-02-08 10:33 UTC, grossmannmartin approved these changes

2021-02-08 16:39 UTC, grossmannmartin reviewed
A point from testing:
in dev environment, error 500 is still raised, I think it can be confusing.

2021-02-08 16:45 UTC, s3tezsky commented
> A point from testing:
> in dev environment, error 500 is still raised, I think it can be confusing.

Yeah, I know. That is because in dev environment it is not going through ErrorController. I actually do not mind that because it still shows me the trace what has happend.

2021-02-15 11:39 UTC, grossmannmartin commented
closed with #2236

2021-02-15 11:39 UTC, closed without merging