[shopsys] trigger deprecations wrapped to helper class
shopsys/shopsys pull request #2349
Opened 2021-06-08 11:54 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| Triggering deprecations was tedious and required copy-paste approach. This PR introduce a helper class to trigger several types of deprecations along with replaced usage
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-06-10 07:37 UTC, TomasLudvik requested changes

2021-06-10 07:37 UTC, TomasLudvik commented on project-base/app/Environment.php
> +        return self::getEnvironmentFileSetting()->getEnvironment(true);
this should not be here

2021-06-10 12:42 UTC, grossmannmartin commented on packages/framework/src/Component/Deprecations/DeprecationHelper.php
> +class DeprecationHelper
fixed

2021-06-10 12:42 UTC, grossmannmartin commented on project-base/app/Environment.php
> +        return self::getEnvironmentFileSetting()->getEnvironment(true);
thanks! fixed

2021-06-14 08:36 UTC, TomasLudvik approved these changes

2021-06-15 06:37 UTC, sslt approved these changes

2021-06-15 08:33 UTC, merged