Release candidate for v9.1.2
shopsys/shopsys pull request #2364
Opened 2021-06-28 12:17 UTC by s3tezsky

| Q             | A
| ------------- | ---
|Description, reason for the PR| Preparing for release a new patch version
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2021-06-28 13:31 UTC, TomasLudvik requested changes

2021-06-28 13:39 UTC, s3tezsky commented on CHANGELOG.md
> +- \[shopsys\] excluded friendsofphp/php-cs-fixer v2.19.0 in 7.3 [\#2320](https://github.com/shopsys/shopsys/pull/2320) ([s3tezsky](https://github.com/s3tezsky))
Actually it is not. This is just copy&pasted section from 7.3.7 release 😉

2021-06-29 08:38 UTC, s3tezsky commented on CHANGELOG.md
> +- \[shopsys\] excluded friendsofphp/php-cs-fixer v2.19.0 in 7.3 [\#2320](https://github.com/shopsys/shopsys/pull/2320) ([s3tezsky](https://github.com/s3tezsky))
I have added also previous (not included) changelogs (7.3.6, 7.3.5)

2021-06-29 09:07 UTC, TomasLudvik approved these changes

2021-07-01 09:13 UTC, sslt approved these changes

2021-07-01 09:32 UTC, sslt approved these changes

2021-07-01 09:36 UTC, merged