[project-base] assets js not need to be executable
shopsys/shopsys pull request #2403
Opened 2022-02-14 07:48 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| in windows sometimes executable bit is lost on assets/bin files. This PR changes how bin is running, so it's not necessary to have this files executable
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2022-02-14 08:26 UTC, pk16011990 approved these changes

2022-02-14 08:48 UTC, vitek-rostislav requested changes
Hi, could you please update the upgrade notes? :slightly_smiling_face:

2022-03-23 18:12 UTC, sspooky13 approved these changes
I agree, these changes fixed my issue with permissions 😊

2022-04-22 10:33 UTC, RobinDvorak approved these changes

2022-04-22 15:08 UTC, vitek-rostislav approved these changes

2022-04-25 06:57 UTC, merged