[shopsys] Use getValues() instead of toArray() on Doctrine Collections
shopsys/shopsys pull request #2439
Opened 2022-05-04 11:34 UTC by RobinDvorak

| Q             | A
| ------------- | ---
|Description, reason for the PR| Using `toArray()` on Doctrine Collections might be problematic as described in #2409  
|New feature| No
|[BC breaks]| No
|Fixes issues| closes #2409 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2022-05-04 16:14 UTC, grossmannmartin approved these changes

2022-05-05 05:55 UTC, pk16011990 commented
Please, add this replacing code to the upgrade notes for collections in project-base. I think, that this issue is common for new project entities in project base or in overridden entities methods.

2022-05-05 05:56 UTC, pk16011990 requested changes
Please, add this replacing code to the upgrade notes for collections in project-base. I think, that this issue is common for new project entities in project base or in overridden entity methods.

2022-05-05 12:24 UTC, RobinDvorak commented
> Please, add this replacing code to the upgrade notes for collections in project-base. I think, that this issue is common for new project entities in project base or in overridden entity methods.

@pk16011990 I didn't found any upgrade notes for Collections in project-base. I added it to classic upgrade notes under Application. You can check the result here: https://github.com/shopsys/shopsys/blob/1ab1faa878ffcf71cb3e2f6ed88ae8b6608ccaff/upgrade/UPGRADE-v9.2.0-dev.md

2022-05-06 04:58 UTC, pk16011990 approved these changes

2022-05-09 06:59 UTC, merged