[shopsys] Refactor ECS config to new syntax
shopsys/shopsys pull request #2454
Opened 2022-05-16 11:50 UTC by RobinDvorak

| Q             | A
| ------------- | ---
|Description, reason for the PR| Removes deprecation notices about new config syntax
|New feature| No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2022-05-16 15:32 UTC, grossmannmartin requested changes

2022-05-16 15:51 UTC, RobinDvorak commented on packages/frontend-api/ecs.php
> +    $ecsConfig->ruleWithConfiguration(ForbiddenPrivateVisibilityFixer::class, [
I was afraid about this, but tested it only with first package. You are right, rollbacking this chage...

2022-05-17 14:42 UTC, grossmannmartin commented on packages/frontend-api/ecs.php
> +    $ecsConfig->ruleWithConfiguration(ForbiddenPrivateVisibilityFixer::class, [
nice work and great catch with the same alias. You're right, it was a mistake.

2022-05-17 14:43 UTC, grossmannmartin approved these changes

2022-05-18 06:08 UTC, pk16011990 requested changes
There are changes in the project-base -> upgrade notes? :innocent:

2022-05-18 08:27 UTC, pk16011990 approved these changes

2022-05-18 08:45 UTC, merged