Error handler component
shopsys/shopsys pull request #2474
Opened 2022-07-01 12:32 UTC by RobinDvorak

| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| Yes/No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes/No

2022-07-10 20:55 UTC, grossmannmartin requested changes

2022-07-11 09:03 UTC, RobinDvorak commented on packages/framework/src/Component/Error/ErrorController.php
> +    use FlashMessageTrait;
I wanted to keep functionality, as `ErrorController` extended `FrontController` and this was only thing used in `FrontController`. I removed the extension and added `FlashMessage` trait. 
I was not sure if it's needed or not.

2022-07-11 10:43 UTC, RobinDvorak commented on project-base/config/services.yaml
> -    App\Controller\Front\ErrorController:
https://github.com/shopsys/shopsys/pull/2474/commits/eaa41fb3523f4b8152fa0923b154c7bb4148b7e1

2022-07-11 12:26 UTC, vitek-rostislav commented on composer.json
> -        "symfony/debug": "^4.4.0",
could you please perform these changes also in `composer.json` files in `framework` package and in `project-base`, please? :slightly_smiling_face:

2022-07-12 07:31 UTC, merged