[releaser] improve information in after-release stage
shopsys/shopsys pull request #2513
Opened 2022-11-15 16:07 UTC by vitek-rostislav

- added information about necessity of manually splitting monorepo when not on master branch

| Q             | A
| ------------- | ---
|Description, reason for the PR| there is a confusing moment when releasing a version that is not on master - you have tag in project-base but the tag is not in any branch until the monorepo branch is split 
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

**Note:** it would be nice to merge 10.0 branch into master after this PR is merged

2022-11-17 06:17 UTC, s3tezsky commented
Hi, it is the 6th bullet from the list https://github.com/shopsys/shopsys/issues/1424#issue-497358940. Unfortunately there are more issues than that.

Keep rollin! 💪

2022-11-17 10:16 UTC, vitek-rostislav commented on utils/releaser/config/after-release.php
> +    $services->set(CheckShopsysInstallReleaseWorker::class); // než provedu tohle, musím mít force-splitnuto
damn, this should not be committed :smile:

2023-01-26 09:19 UTC, TomasLudvik requested changes

2023-01-26 09:19 UTC, TomasLudvik commented on utils/releaser/src/ReleaseWorker/AfterRelease/CheckShopsysInstallReleaseWorker.php
> +        return '[Manually] Install Shopsys Framework (project-base) using installation guides (using Docker on Linux and Mac and natively). You need to wait with the installation until the monorepo i
```suggestion
        return '[Manually] Install Shopsys Framework (project-base) using installation guides on all supported operating systems. You need to wait with the installation until the monorepo is split.';
```

2023-01-27 09:50 UTC, TomasLudvik approved these changes

2023-01-27 10:11 UTC, pk16011990 approved these changes

2023-01-30 09:36 UTC, merged