Allow vendor patches and add patch for better logging url in profiler from frontend api
shopsys/shopsys pull request #2531
Opened 2023-01-09 08:12 UTC by RostislavKreisinger

| Q             | A
| ------------- | ---
|Description, reason for the PR| It is now possible to create a patch for vendor packages in the monorepo according to the instructions https://tomasvotruba.com/blog/2020/07/02/how-to-patch-package-in-vendor-yet-allow-its-updates/.

When you run composer install, the created patch is registered to composer.json from project-base and copied to the patches folder in project-base.

A patch was added that adjusts the url request statement to the symfony profiler. Now URLs on the graphQL API contain information about the query or mutation. ( http://127.0.0.1:8000/graphql/ - query{categories} )
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-01-11 12:42 UTC, TomasLudvik requested changes

2023-01-11 12:42 UTC, TomasLudvik commented on packages/framework/src/Component/HttpKernel/Profiler/FileProfilerStorage.php
> +
This comment is probably not necessary here

2023-01-12 07:41 UTC, TomasLudvik approved these changes

2023-01-12 08:19 UTC, pk16011990 commented on packages/framework/src/Resources/config/services.yaml
> +            $dsn: 'file:%kernel.project_dir%/var/cache/profiler'
Is there reason for not using of `%kernel.cache_dir%`?

2023-01-13 07:03 UTC, pk16011990 approved these changes

2023-01-17 10:05 UTC, merged