Release  v9.1.3
shopsys/shopsys pull request #2544
Opened 2023-01-19 09:01 UTC by RostislavKreisinger

| Q             | A
| ------------- | ---
|Description, reason for the PR| Release framework v9.1.3
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-01-20 12:32 UTC, TomasLudvik requested changes

2023-01-20 12:32 UTC, TomasLudvik commented on utils/releaser/src/GithubActions/GithubActionsStatusReporter.php
> +        'shopsys/product-feed-interface',
I think this package should be part of the check, right?

2023-01-20 12:32 UTC, TomasLudvik commented on CHANGELOG.md
> +
I do not think that versions higher than 9.1.3 should be present here

2023-01-20 12:32 UTC, TomasLudvik commented on upgrade/UPGRADE-v9.1.3.md
> +This guide contains instructions to upgrade from version v9.1.2 to v9.1.3.
In this file there is several upgrade notes for changes not mentioned in changelog

2023-01-23 12:53 UTC, TomasLudvik commented on CHANGELOG.md
> -- \[framework\] update heureka/overeno-zakazniky to latest version 4.0.1 [\#2534](https://github.com/shopsys/shopsys/pull/2534) ([RostislavKreisinger](https://github.com/RostislavKreisinger))
I asked you to fill missing changes in 9.1.3 and you even removed the only one mentioned :D

2023-01-23 13:13 UTC, TomasLudvik commented on CHANGELOG.md
> +
```suggestion
```

2023-01-23 13:19 UTC, RostislavKreisinger commented on CHANGELOG.md
> +
ok

2023-01-24 08:42 UTC, TomasLudvik approved these changes

2023-01-24 09:05 UTC, merged