New Redis Commander
shopsys/shopsys pull request #2550
Opened 2023-01-30 13:30 UTC by RostislavKreisinger

| Q             | A
| ------------- | ---
|Description, reason for the PR| old phpRedisAdmin has been replaced with new Redis Commander
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2532 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-01-30 13:39 UTC, vitek-rostislav commented
do not forget to update docs please, eg. https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-application-setup.md#2-see-it-in-your-browser

2023-02-01 09:01 UTC, TomasLudvik requested changes
Please also update project-base/kubernetes/deployments/redis-admin.yml

2023-02-02 12:41 UTC, TomasLudvik approved these changes

2023-02-03 07:08 UTC, pk16011990 approved these changes

2023-02-03 07:46 UTC, merged