Sitemap updates
shopsys/shopsys pull request #2551
Opened 2023-01-31 07:05 UTC by RostislavKreisinger

| Q             | A
| ------------- | ---
|Description, reason for the PR| We want the data in the sitemap to be true and relevant, or rather not be there. All information about `<lastmod>`, `<changefreq>` and `<priority>` is removed from the sitemap (page and images)
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues|  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-02-02 10:38 UTC, TomasLudvik requested changes

2023-02-02 10:38 UTC, TomasLudvik commented on project-base/config/services/cron.yaml
> +
You can squash second and third commit

2023-02-02 13:18 UTC, RostislavKreisinger commented on packages/framework/src/Model/Sitemap/SitemapListener.php
>      protected const PRIORITY_ARTICLES = 0.5;
ok

2023-02-02 13:19 UTC, RostislavKreisinger commented on project-base/config/services/cron.yaml
> +
ok, i do it before merge

2023-02-02 13:19 UTC, RostislavKreisinger commented on packages/framework/src/Model/ImageSitemap/ImageSitemapCronModule.php
> +        $this->imageSitemapFacade = $imageSitemapFacade;
ok

2023-02-03 14:19 UTC, TomasLudvik commented on packages/framework/src/Model/Sitemap/SitemapListener.php
>      protected const PRIORITY_ARTICLES = 0.5;
So what is the solution for this?

2023-02-03 14:19 UTC, TomasLudvik commented on packages/framework/src/Model/Sitemap/SitemapListener.php
> -    protected const PRIORITY_ARTICLES = 0.5;
You will have to mention this in the UPGRADE notes

2023-02-10 13:23 UTC, TomasLudvik approved these changes

2023-02-10 13:23 UTC, merged