columns in grid can now be reordered
shopsys/shopsys pull request #2564
Opened 2023-02-16 14:06 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| If project extend any existing grid (for example Product List grid in administration), it may be useful to be able to reorder columns (when it's needed to have fields in specific order)
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-04-14 11:35 UTC, TomasLudvik requested changes

2023-04-14 11:35 UTC, TomasLudvik commented on packages/framework/src/Component/Grid/Grid.php
> +    public function reorderColumns(array $newColumnOrder): void
```suggestion
    public function reorderColumns(array $orderedColumnIds): void
```

2023-04-14 11:35 UTC, TomasLudvik commented on packages/framework/src/Component/Grid/Grid.php
> +        foreach ($newColumnOrder as $column) {
```suggestion
        foreach ($orderedColumnIds as $columnId) {
```

2023-04-14 11:35 UTC, TomasLudvik commented on packages/framework/src/Component/Grid/Grid.php
> +            $newColumns[$column] = $this->columnsById[$column];
```suggestion
            $orderedColumns[$columnId] = $this->columnsById[$columnId];
```

2023-04-14 11:36 UTC, TomasLudvik requested changes
I think it would be nice to add info about this to docs https://docs.shopsys.com/en/11.0/administration/grid/ and also somewhere to https://docs.shopsys.com/en/11.0/extensibility/

2023-04-18 05:58 UTC, TomasLudvik commented
> > I think it would be nice to add info about this to docs https://docs.shopsys.com/en/11.0/administration/grid/ and also somewhere to https://docs.shopsys.com/en/11.0/extensibility/
> 
> I have added it to the grid documentation. But I don't see a fitting place in the "extensibility" section.

Well I will approve this, but I thought that extensibility is the main place for reordering as you will probably use this in project-base for extended functionalityů

2023-04-18 05:58 UTC, TomasLudvik approved these changes

2023-04-18 06:38 UTC, pk16011990 approved these changes

2023-04-19 06:34 UTC, merged