[shopsys] added ability to change periodicity and length of cron runs
shopsys/shopsys pull request #2584
Opened 2023-03-22 15:05 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| Developers are now able to change length and periodicity of cron instances.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-03-23 10:22 UTC, LuKillman requested changes

2023-03-23 16:40 UTC, TomasLudvik commented on packages/framework/src/DependencyInjection/Compiler/RegisterCronModulesCompilerPass.php
> +     * @return array{run_every_min: int, timeout_iterated_cron_sec: int}>
Good 👀 ! :)

2023-03-23 16:40 UTC, TomasLudvik commented on packages/framework/src/Component/Cron/CronModuleExecutor.php
> +    public function canRun(CronModuleConfig|null $cronConfig = null): bool
You are right

2023-03-24 10:31 UTC, LuKillman approved these changes

2023-04-04 09:56 UTC, merged