[shopsys] updated installation docs for macOS using Mutagen
shopsys/shopsys pull request #2593
Opened 2023-04-12 15:41 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| Replaced Docker-sync by Mutagen. Mutagen synchronization does not suffer from synchronization freezes and its performance is same as of Docker-sync.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-04-13 14:36 UTC, grossmannmartin requested changes

2023-04-13 14:36 UTC, grossmannmartin commented on docs/installation/installation-using-docker-application-setup.md
> +You can use [Kibana](https://www.elastic.co/downloads/kibana) for Elasticseacrh management, it is available on [http://127.0.0.1:5601](http://127.0.0.1:5601).
```suggestion
You can use [Kibana](https://www.elastic.co/downloads/kibana) for Elasticsearch management, it is available on [http://127.0.0.1:5601](http://127.0.0.1:5601).
```

2023-04-14 07:27 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
> +     * We recommend to set at least 8 GB RAM, 4 CPUs and 512 MB Swap in `Docker -> Preferences… -> Resources -> ADVANCED`
Well, previous recommendations were wrong - using Swap to "balance" spikes of memory usage is the worst idea possible - you will slow down everything by hundreds of percent if such a situation occurs. Also this are only recommendations from my own experience with really good performance (I use even 10 GB of RAM) and have no other opinion (:wink: :wink:) that I could use.

2023-04-14 07:28 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
> +* [PHP](http://php.net/manual/en/install.macOSx.php)
```suggestion
* [PHP](http://php.net/manual/en/install.macosx.php)
```

2023-04-14 07:29 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
> +* [PHP](http://php.net/manual/en/install.macOSx.php)
You are right

2023-04-17 11:30 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
> +#### 3.1 Enable second domain (optional)
Ok

2023-04-17 11:33 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
>  This can be achieved by build arguments `www_data_uid` and `www_data_gid` that should be set to the same UID and GID as your own user in your `docker-compose.yml`.
Added

2023-04-17 11:42 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
>  ```sh
I hope I got what you meant and updated it correctly :)

2023-04-19 07:36 UTC, grossmannmartin commented on docs/installation/installation-using-docker-macos.md
> +* [PHP](http://php.net/manual/en/install.macOSx.php)
Should it be changed then? I see it still the same

2023-04-20 10:37 UTC, TomasLudvik commented on docs/installation/installation-using-docker-macos.md
> +* [PHP](http://php.net/manual/en/install.macOSx.php)
Fixed :)

2023-04-20 11:20 UTC, grossmannmartin approved these changes

2023-04-21 07:24 UTC, pk16011990 approved these changes

2023-04-21 07:24 UTC, pk16011990 commented on project-base/scripts/configure.sh
> +    2) MacOS with Mutagen
```suggestion
    2) macOS with Mutagen
```

2023-04-21 07:24 UTC, pk16011990 commented on upgrade/UPGRADE-v11.0.1-dev.md
> +<<<<<<< HEAD
```suggestion
```

2023-04-24 06:44 UTC, TomasLudvik commented on project-base/scripts/configure.sh
> +    2) MacOS with Mutagen
Nice catch, thanks

2023-04-24 06:44 UTC, TomasLudvik commented on upgrade/UPGRADE-v11.0.1-dev.md
> +<<<<<<< HEAD
Nice catch, thanks

2023-04-25 09:44 UTC, merged