[project-base] returned symfony.lock to project-base as it caused problems with symfony flex installing packages again
shopsys/shopsys pull request #2595
Opened 2023-04-17 12:38 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| With the release of Shopsys Framework 11 we have removed symfony.lock from the project-base and that caused several problems.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-04-19 10:14 UTC, grossmannmartin requested changes

2023-04-19 11:38 UTC, TomasLudvik commented on utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
> -        $this->processRunner->run('git add project-base/symfony.lock');
It is a committed file, so it would be weird if it was not added already.

2023-04-19 12:29 UTC, grossmannmartin commented on utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
> -        $this->processRunner->run('git add project-base/symfony.lock');
This file may be updated (with install done before and copy – line 45). Then these changes will not be committed without this line, or?

2023-04-20 10:40 UTC, TomasLudvik commented on utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
> -        $this->processRunner->run('git add project-base/symfony.lock');
I have returned it

2023-04-20 11:22 UTC, grossmannmartin approved these changes

2023-04-21 07:08 UTC, pk16011990 approved these changes

2023-04-24 07:08 UTC, merged