[shopsys] users and admins now have only five tries to log in in one minute
shopsys/shopsys pull request #2599
Opened 2023-04-19 15:01 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| This change is made to prevent brute force attacks.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-04-20 12:31 UTC, grossmannmartin requested changes

2023-04-20 12:51 UTC, TomasLudvik commented on project-base/config/packages/lock.yaml
> +    lock: '%env(LOCK_DSN)%'
Removed

2023-04-20 12:53 UTC, TomasLudvik commented on packages/framework/src/Controller/Admin/LoginController.php
> +                $error = t('Too many login attempts. Please try again later.');
Lets @pk16011990 decide

2023-04-21 07:22 UTC, grossmannmartin commented on upgrade/UPGRADE-v11.0.1-dev.md
> +- enable login rate limits to prevent brute force attacks (#2599[https://github.com/shopsys/shopsys/pull/2599])
```suggestion
- enable login rate limits to prevent brute force attacks ([#2599](https://github.com/shopsys/shopsys/pull/2599))
```

2023-04-21 07:23 UTC, grossmannmartin commented on symfony.lock
> +            "repo": "github.com/symfony/recipes",
what about this, please?

2023-04-24 07:15 UTC, TomasLudvik commented on upgrade/UPGRADE-v11.0.1-dev.md
> +- enable login rate limits to prevent brute force attacks (#2599[https://github.com/shopsys/shopsys/pull/2599])
fixed

2023-04-24 07:15 UTC, TomasLudvik commented on symfony.lock
> +            "repo": "github.com/symfony/recipes",
symfony.lock is again back in the project-base, so I could add it :)

2023-04-25 05:53 UTC, grossmannmartin approved these changes

2023-04-25 06:42 UTC, pk16011990 commented on packages/framework/src/Controller/Admin/LoginController.php
> +                $error = t('Too many login attempts. Please try again later.');
I don't have a strong opinion. Now it's okay.

2023-04-25 06:46 UTC, pk16011990 approved these changes

2023-04-26 07:54 UTC, merged