added detailed opening hours to stores
shopsys/shopsys pull request #2660
Opened 2023-07-11 14:13 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| Administrators need to set more detailed opening hours and show if the store is currently opened or closed.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-07-12 10:20 UTC, grossmannmartin requested changes

2023-07-12 10:20 UTC, grossmannmartin commented on project-base/app/src/Model/Store/StoreDataFactory.php
> +        );
I would probably move this method into the factory, but I don't mind it this way.

2023-07-13 11:29 UTC, TomasLudvik commented on project-base/app/src/Model/Store/StoreRepository.php
> +//            ->join(OpeningHours::class, 'oh', Join::WITH, 's.id = oh.store')
removed

2023-07-13 11:29 UTC, TomasLudvik commented on project-base/app/config/graphql/types/ModelType/Store/OpeningHours/OpeningHours.types.yaml
> +                description: "Current day of the week"
Added

2023-07-13 11:42 UTC, TomasLudvik commented on project-base/app/src/DataFixtures/Demo/StoreDataFixture.php
> +            }
Hmmm, okay

2023-07-13 11:43 UTC, TomasLudvik commented on project-base/app/src/Model/Store/OpeningHours/Exception/OpeningHoursException.php
> +interface OpeningHoursException extends Throwable
fixed

2023-07-13 11:46 UTC, TomasLudvik commented on project-base/app/src/Model/Store/OpeningHours/OpeningHours.php
> +    private int $id;
I have updated entity according to our framework rules

2023-07-13 11:46 UTC, TomasLudvik commented on project-base/app/src/Model/Store/OpeningHours/OpeningHours.php
> +    public function getStore(): Store
removed

2023-07-13 11:47 UTC, TomasLudvik commented on project-base/app/src/Model/Store/OpeningHours/OpeningHoursData.php
> +    public int $dayOfWeek = 0;
Ok

2023-07-13 11:47 UTC, TomasLudvik commented on project-base/app/src/DataFixtures/Demo/StoreDataFixture.php
> +            $openingHour->firstOpeningTime = (clone $firstOpeningTime)->add($dateInterval)->format('H:i');
I have rewritten it to setting exact values

2023-07-13 12:54 UTC, TomasLudvik commented on project-base/app/src/Model/Store/OpeningHours/OpeningHoursFacade.php
> +        ];
I have moved it to resolver map

2023-07-13 12:55 UTC, TomasLudvik commented on project-base/app/src/Model/Store/OpeningHours/OpeningHoursFacade.php
> +            return false;
You are right

2023-07-13 12:57 UTC, TomasLudvik commented on project-base/app/src/Model/Store/Store.php
> +     * @ORM\OrderBy({"id" = "ASC"})
Good catch!

2023-07-13 13:02 UTC, TomasLudvik commented on project-base/app/src/Model/Store/Store.php
> +        $dayOfWeek = (int)date('N');
Again, good catch, I have updated it

2023-07-17 08:14 UTC, grossmannmartin approved these changes

2023-07-25 11:02 UTC, merged