improve Web Vitals metrics
shopsys/shopsys pull request #2675
Opened 2023-07-24 12:58 UTC by tvikito

| Q             | A
| ------------- | ---
|Description, reason for the PR| improve several Web Vitals metrics for better UX and SEO
|New feature| No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-08-03 09:21 UTC, sebaholesz requested changes
Nice job :+1: I have a couple of questions and other matters. Let's discuss them.

2023-08-03 09:21 UTC, sebaholesz commented on project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
> +                                const sortHref = `${asPathWithoutQueryParams}?${sortParams}`;
I added a util for this. Its not in 'master' yet, but looks like this

```ts
const parseObjectToQueryString = (object: Record<string, string>) => {
    const params = new URLSearchParams();

    for (const [key, value] of Object.entries(object)) {
        if (Array.isArray(value)) {
            value.forEach((val) => params.append(`${key}[]`, val));
        } else {
            params.append(key, value);
        }
    }

    return params.toString();
};

export const getUrlFromPathnameAndQueries = (pathname: string, query?: Record<string, string>) => {
    let url = `${pathname}`;

    if (query && Object.keys(query).length > 0) {
        url += `?${parseObjectToQueryString(query)}`;
    }

    return url;
};
```

2023-08-03 09:21 UTC, sebaholesz commented on project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
> +                                        href={sortHref}
It is a little bit weird. We are setting the href, then preventing its behavior, and handling it manually. I probably understand the semantic reasoning behind that, but I am not sure if thats the best way to handle it. Cannot the buttons just be links? Or if we want to use the `updateSort` function (preferred by me), cannot it just be buttons?

2023-08-03 09:21 UTC, sebaholesz commented on project-base/storefront/components/Layout/Header/Cart/Cart.tsx
> +                            height={104}
Why is this needed?

2023-08-03 09:21 UTC, sebaholesz commented on project-base/storefront/styles/globals.css
> -
Not necessary anymore, or?

2023-08-03 09:21 UTC, sebaholesz commented on project-base/storefront/components/Basic/Gallery/Gallery.tsx
> +const LightGallery = dynamic(() => import('lightgallery/react').then((component) => component));
As I understand this, you still load it during SSR. Is that what we want?

2023-08-03 09:21 UTC, sebaholesz commented on project-base/storefront/components/Pages/CategoryDetail/AdvancedSeoCategories/AdvancedSeoCategories.tsx
> -            <Heading type="h3">{t('Favorite categories')}</Heading>
Was this incorrect?

2023-08-04 09:27 UTC, tvikito commented on project-base/storefront/components/Layout/Header/Logo/Logo.tsx
> +                alt="Shopsys logo"
That doesn't make much sense to me, since client will replace it anyway. This way I would rather use hardcoded name.

2023-08-04 09:28 UTC, tvikito commented on project-base/storefront/components/Basic/ExtendedNextLink/ExtendedNextLink.tsx
> -    children?: ReactElement | string | number;
Seems like it's working so let's leave it as fixed :)

2023-08-04 09:28 UTC, tvikito commented on project-base/storefront/components/Basic/Link/Link.tsx
> -    children?: ReactElement | string | number;
Seems like it's working so let's leave it as fixed :)

2023-08-04 13:07 UTC, sebaholesz commented on project-base/storefront/components/Layout/Header/Logo/Logo.tsx
> +                alt="Shopsys logo"
Alright

2023-08-04 13:09 UTC, sebaholesz commented on project-base/storefront/components/Basic/Link/Link.tsx
> -    children?: ReactElement | string | number;
Alright then :laughing:

2023-08-07 09:55 UTC, sebaholesz commented on project-base/storefront/components/Blocks/BlogPreview/BlogPreviewElements.tsx
> +    <ExtendedNextLink type="blogArticle" href={href} className={className}>
Alright

2023-08-07 09:56 UTC, sebaholesz commented on project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
> +                                const { page, ...queriesWithoutPage } = getFilteredQueries(router.query);
Nah, I am good :)

2023-08-07 09:58 UTC, sebaholesz commented on project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
> +                                const sortHref = `${asPathWithoutQueryParams}?${sortParams}`;
You're right :+1:

2023-08-07 09:59 UTC, sebaholesz commented on project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
> +                                        href={sortHref}
Alright then

2023-08-07 10:07 UTC, sebaholesz approved these changes

2023-08-09 10:23 UTC, merged