replaced Shopsys Framework with Shopsys Platform
shopsys/shopsys pull request #2682
Opened 2023-07-28 10:30 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| Yes/No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes/No

2023-08-04 06:08 UTC, pk16011990 requested changes

2023-08-07 10:11 UTC, grossmannmartin commented on CONTRIBUTING.md
> +* [Releasing a new version of Shopsys Platform monorepo](https://docs.shopsys.com/en/latest/contributing/releasing-a-new-version-of-shopsys-framework/)
changed in d2c486a93d

2023-08-07 11:55 UTC, grossmannmartin commented on packages/framework/assets/public/admin/images/logo.svg
No, it was a mistake. Thanks for pointing it out :) fixed

2023-08-09 11:11 UTC, pk16011990 approved these changes

2023-08-11 12:51 UTC, merged