storefront unit tests config and initial examples
shopsys/shopsys pull request #2686
Opened 2023-07-31 19:41 UTC by sebaholesz

| Q             | A
| ------------- | ---
|Description, reason for the PR| This PR implements the basic config and showcase of unit tests using vitest, which can be used as a blueprint for future test implementation..
|New feature| Yes
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-08-01 11:45 UTC, sebaholesz commented on project-base/storefront/vitest/components/ExtendedNextLink/snap-1.json
> +undefined
Great catch! Thanks. I fixed it

2023-08-02 07:26 UTC, grossmannmartin requested changes

2023-08-02 07:26 UTC, grossmannmartin commented on .github/workflows/docker-build.yaml
> +    unit-test-storefront:
The same test should also be added to `build-fork-docker-images` job in the same file. 
After `Check storefront standards` please add 
```
-   name: Run storefront unit tests
     run: docker compose exec storefront pnpm test--no-watch
```

2023-08-02 10:17 UTC, grossmannmartin approved these changes

2023-08-02 20:00 UTC, merged