[shopsys] updated open source license acknowledgements
shopsys/shopsys pull request #2709
Opened 2023-08-10 15:37 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| open source license acknowledgements is possible to generate automatically and is now up-to-date
|New feature| Yes (for monorepo) 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-08-14 13:09 UTC, TomasLudvik requested changes

2023-08-14 13:09 UTC, TomasLudvik commented on utils/license-acknowledgements-generator/composer.json
> +    ]
I am not sure if it is correct to use this license and also the author name as it should be Shopsys

2023-08-14 13:09 UTC, TomasLudvik commented on utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateLicenseAcknowledgementsReleaseWorker.php
> +<?php
❤️

2023-08-15 05:15 UTC, grossmannmartin commented on utils/license-acknowledgements-generator/composer.json
> +    ]
Thanks, I generated the file with composer and didn't check it 😇 

License is, I believe, ok. We already use MIT in several packages

2023-08-17 06:53 UTC, TomasLudvik approved these changes

2023-08-18 14:46 UTC, pk16011990 approved these changes

2023-08-21 08:17 UTC, merged