remove closed filter groups from DOM
shopsys/shopsys pull request #2741
Opened 2023-08-22 14:22 UTC by tvikito

- on projects usually they have closed filters, because of that it is not necessary to include them in the DOM
- this helps with smaller DOM

| Q             | A
| ------------- | ---
|Description, reason for the PR| On projects usually they have closed filters, because of that it is not necessary to include them in the DOM. This helps with smaller DOM.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-08-23 09:34 UTC, sebaholesz requested changes

2023-08-23 09:34 UTC, sebaholesz commented on project-base/storefront/components/Blocks/Product/Filter/FilterGroupParameters.tsx
> +            {isGroupCollapsed && (
I think you should flip this condition, right?

2023-08-24 05:52 UTC, tvikito commented on project-base/storefront/components/Blocks/Product/Filter/FilterGroupParameters.tsx
> +            {isGroupCollapsed && (
Ah, sure! Thank for noticing!

2023-08-25 08:50 UTC, sebaholesz approved these changes

2023-08-29 14:09 UTC, pk16011990 approved these changes

2023-08-30 06:41 UTC, merged