[project-base] SEO categories are now returned even when ignored filters are set
shopsys/shopsys pull request #2756
Opened 2023-08-30 10:38 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| SEO categories are now returned even when ignored filters (price, brand and availability) are set.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-08-31 06:24 UTC, grossmannmartin requested changes

2023-08-31 06:24 UTC, grossmannmartin commented on project-base/app/src/FrontendApi/Resolver/Category/CategoryQuery.php
> +                    !$this->findMatchingReadyCategorySeoMix($info, $readyCategorySeoMix->getCategory())
thanks to this line it's possible that the original category is not returned even when should be. 

Consider the following setting of the SEO Mix (the only difference is the added flag)

![Snímek obrazovky 2023-08-30 v 18 27 20](https://github.com/shopsys/shopsys/assets/1177414/836cf480-cc6d-498d-9686-eb9b543474fa)

and the following query 
```graphql
query CategoryDetailQuery($urlSlug: String, $orderingMode: ProductOrderingModeEnum, $filter: ProductFilter) {
  category(urlSlug: $urlSlug, orderingMode: $orderingMode, filter: $filter) {
    ...CategoryDetailFragment
  }
}

fragment CategoryDetailFragment on Category {
  __typename
  id
  uuid
  slug
  originalCategorySlug
  name
}
```

then when the query is called with the following variables 

``` json
{
  "urlSlug": "oreo",
  "orderingMode": "PRIORITY",
  "filter": {
    	"flags": ["1d9dc3d5-c288-4598-aa17-1dea5a6398fd"],
    	"parameters": [{
        "parameter": "efcc5e69-ec23-40ca-91c8-e2171664c26c",
        "values": ["7be9264e-2c24-4a50-be7d-5eab88d65655"]
      }]
  }
}
```
(parameter is `dimension`, value is `80x70x70 mm`, flag is `New`)

the result is the returned `/oreo` seo mix – that seo mix does not match the requested filter settings. 
I think the best expected outcome is `/myoreo` seo mix, but I think `Tv audio` category is acceptable too.

2023-08-31 11:44 UTC, TomasLudvik commented on project-base/app/src/FrontendApi/Resolver/Category/CategoryQuery.php
> +                    !$this->findMatchingReadyCategorySeoMix($info, $readyCategorySeoMix->getCategory())
Ok I fixed it and outcome is now /myoreo

2023-08-31 12:25 UTC, grossmannmartin approved these changes

2023-09-06 09:34 UTC, pk16011990 approved these changes

2023-09-07 13:21 UTC, merged