[project-base] reduced image url redis cache size
shopsys/shopsys pull request #2761
Opened 2023-08-31 12:20 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| Only information about the source image is saved into the Redis cache as nothing else is necessary.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-08-31 13:40 UTC, grossmannmartin requested changes

2023-08-31 13:40 UTC, grossmannmartin commented on project-base/app/src/Component/Image/ImageFacade.php
>              $additionalIndex,
The last variable in the string key is named `type`, but the `$additionalIndex` is passed.

Also, has the distinguishing by $additionalIndex any meaning? From the code, it seems like the additionalSizes will have always the same slug saved in the Redis. Isn't possible to reduce the data further and make the code a little less complex as the bonus?

![Snímek obrazovky 2023-08-31 v 14 59 54](https://github.com/shopsys/shopsys/assets/1177414/c867e12d-ae5a-4b5d-a08e-0aec11e56f2c)

2023-09-05 07:50 UTC, TomasLudvik commented on project-base/app/src/Component/Image/ImageFacade.php
>              $additionalIndex,
I have updated it

2023-09-07 05:11 UTC, grossmannmartin approved these changes

2023-09-07 06:39 UTC, pk16011990 approved these changes

2023-09-07 12:55 UTC, merged