[shopsys] upgraded doctrine/orm to latest version
shopsys/shopsys pull request #2774
Opened 2023-09-07 09:15 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, reason for the PR| There were some problems with the order of Order Items when upgrading to the newest doctrine/orm. This has been fixed and the restriction to older doctrine/orm has been removed.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-09-08 11:25 UTC, grossmannmartin requested changes

2023-09-08 11:25 UTC, grossmannmartin commented on composer.json
> -        "doctrine/orm": "2.12.0 || >=2.16.0"
this conflict should be removed also from the `packages/framework/composer.json`

2023-09-08 11:25 UTC, grossmannmartin commented on upgrade/UPGRADE-v12.0.0-dev.md
> +    - see #project-base-diff for more details
From this PR will be no project-base-diff as no changes in the project-base were made.

2023-09-11 07:24 UTC, TomasLudvik commented on composer.json
> -        "doctrine/orm": "2.12.0 || >=2.16.0"
fixed

2023-09-11 07:24 UTC, TomasLudvik commented on upgrade/UPGRADE-v12.0.0-dev.md
> +    - see #project-base-diff for more details
fixed

2023-09-11 08:18 UTC, grossmannmartin approved these changes

2023-09-11 08:19 UTC, grossmannmartin approved these changes

2023-09-11 14:14 UTC, pk16011990 approved these changes

2023-09-12 07:39 UTC, merged