[project-base] removed unused code
shopsys/shopsys pull request #2777
Opened 2023-09-07 13:09 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| removed unused code
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-09-11 08:02 UTC, TomasLudvik commented on project-base/app/src/Model/Category/Category.php
> -    }
We want to have edit and setData method here as in https://github.com/shopsys/shopsys/blob/12.0/project-base/src/Model/Article/Article.php

2023-09-11 18:05 UTC, grossmannmartin commented on project-base/app/src/Model/Category/Category.php
> -    }
Ok, it's back

2023-09-12 07:25 UTC, TomasLudvik approved these changes

2023-09-13 06:01 UTC, pk16011990 requested changes
Please, add upgrade notes like:
> "Products - exposed on stores", "Category - SVG icon" and "Category - short description" have been removed. If you use this functionality (e.g. from Commerce Cloud version), you can skip DB migration `20230908095905`.

2023-09-14 07:28 UTC, pk16011990 approved these changes

2023-09-14 08:15 UTC, merged