fix Filter parameter slider selected value
shopsys/shopsys pull request #2784
Opened 2023-09-12 06:37 UTC by tvikito

| Q             | A
| ------------- | ---
|Description, reason for the PR| fix Filter parameter slider selected value which has not been displayed properly
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-09-12 10:28 UTC, sebaholesz requested changes

2023-09-12 10:28 UTC, sebaholesz commented on project-base/storefront/components/Blocks/Product/Filter/FilterSelectedParameters.tsx
> +
I am not sure, if I follow. I can see `selectedParameterOptions.maximalValue` twice. Does that mean it can get rendered twice?

2023-09-12 12:54 UTC, tvikito commented on project-base/storefront/components/Blocks/Product/Filter/FilterSelectedParameters.tsx
> +
Ah, it was implemented even before my changes. It was meant to add space in case there is also maximalValue, but the logic was not correct. Now it's refactored.

2023-09-13 10:26 UTC, sebaholesz approved these changes

2023-09-14 07:23 UTC, pk16011990 approved these changes

2023-09-14 07:46 UTC, merged