[shopsys] added order filter by domain in admin
shopsys/shopsys pull request #2796
Opened 2023-09-14 12:49 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| Orders from only one domain can be displayed in admin in the order list. Refactoring of domain filter in categories and blog categories was done along.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

----
:globe_with_meridians: Live Preview:
  - https://mg-order-list-domain.odin.shopsys.cloud
  - https://cz.mg-order-list-domain.odin.shopsys.cloud

2023-09-15 11:39 UTC, TomasLudvik approved these changes
This change feels like it should be documented. I leave this up to you -> approve.

2023-09-19 07:26 UTC, pk16011990 requested changes
There exist a few removed/changed methods and deleted twig template. Shouldn't there be upgrade notes?

2023-09-20 12:34 UTC, TomasLudvik approved these changes

2023-09-21 05:49 UTC, pk16011990 approved these changes

2023-09-21 06:15 UTC, merged