[shopsys] added general upgrade notes to upgrade to Shopsys Platform
shopsys/shopsys pull request #2817
Opened 2023-09-19 12:52 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| The upgrade to the new version may be challenging, so the basic upgrade options were added here.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-09-19 13:03 UTC, TomasLudvik requested changes

2023-09-19 13:03 UTC, TomasLudvik commented on upgrade/UPGRADE-v13.0.0-dev.md
> +   You still get the fixes, and you will be ready to upgrade to the new storefront in the future.
I wonder if this is really possible. Have you tried to pick version 12 and just update shopsys dependencies to version 13?

2023-09-19 16:17 UTC, grossmannmartin commented on upgrade/UPGRADE-v13.0.0-dev.md
> +   You still get the fixes, and you will be ready to upgrade to the new storefront in the future.
Yup, I did that 🙂
Problems were with the time zone mentioned below, with missing migration. Then some tests were failing, but on the things that are mentioned as a bc breaking changes in the next section.

2023-09-20 12:30 UTC, TomasLudvik approved these changes

2023-09-21 05:54 UTC, pk16011990 approved these changes

2023-09-22 06:42 UTC, merged