[project-base] admin with limited permissions now can use domain filter
shopsys/shopsys pull request #2844
Opened 2023-09-29 10:19 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| In #2796 the domain filter was introduced, but the admin with limited permissions was not able to use it. This PR fixes it.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-10-02 09:11 UTC, TomasLudvik requested changes

2023-10-02 09:11 UTC, TomasLudvik commented on upgrade/UPGRADE-v13.0.0-dev.md
> +    - see also ([#2844](https://github.com/shopsys/shopsys/pull/2844)) for permission fix
This should probably lead to project-base-diff?

2023-10-03 08:17 UTC, TomasLudvik approved these changes

2023-10-04 08:25 UTC, pk16011990 approved these changes

2023-10-04 11:03 UTC, merged