[shopsys] graphql validation errors now contain violation list in the additional data
shopsys/shopsys pull request #2889
Opened 2023-10-19 09:01 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| ArgumentsValidationError is by default logged, but without any information about the exact violation that caused the validation to fail. This PR adds a list of violations to the log message context, so it's clear what caused the validation error.  
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-10-19 10:31 UTC, vitek-rostislav approved these changes

2023-10-19 10:31 UTC, vitek-rostislav commented on packages/frontend-api/src/Model/Logger/FrontendApiLogger.php
> +                // log level may be decreased to INFO to prevent sending validation errors to Sentry
:+1:

2023-10-23 15:15 UTC, pk16011990 requested changes
Please add a configuration (yaml/ENV?) for enabling logging violations to Sentry. The default value should be disabled. 

Validation errors like invalid promo code or non-unique email in registration are not wanted in Sentry, but optionally, it can be enabled on a project.

2023-10-24 09:16 UTC, vitek-rostislav approved these changes

2023-10-25 03:47 UTC, pk16011990 approved these changes

2023-10-25 06:41 UTC, merged