[FW-1848] SEO categories with ignored filters
shopsys/shopsys pull request #2891
Opened 2023-10-19 14:36 UTC by sebaholesz

| Q             | A
| ------------- | ---
|Description, reason for the PR| After adding the option for SEO categories to ignore certain filters, we had to implement this on SF as well.
|New feature| Yes
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

----
:globe_with_meridians: Live Preview:
  - https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud
  - https://cz.sh-seo-categories-with-ignored-filters.odin.shopsys.cloud

2023-10-27 07:18 UTC, pk16011990 requested changes
It does not work properly. 

1. I'm on page https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/electronics
2. Choose "In Stock" filter, url is https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/electronics?filter=%7B%22onlyInStock%22%3Atrue%7D
3. Choose "Color - black" filter, url is https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/electronics?filter=%7B%22onlyInStock%22%3Atrue%2C%22parameters%22%3A%5B%7B%22parameter%22%3A%226436fdc5-dce6-49f8-b66d-0d4c4022f2f3%22%2C%22values%22%3A%5B%221e82a495-692b-4ba1-8d5e-b062e7312729%22%5D%7D%5D%7D but it should be https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/elektro-barva-cerna?filter=%7B%22onlyInStock%22%3Atrue%7D

And new issue is:
1. I'm on page https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/electronics
2. Choose "Color - black" filter, url is https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/electronics?filter=%7B%22parameters%22%3A%5B%7B%22parameter%22%3A%226436fdc5-dce6-49f8-b66d-0d4c4022f2f3%22%2C%22values%22%3A%5B%221e82a495-692b-4ba1-8d5e-b062e7312729%22%5D%7D%5D%7D but it should be https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/elektro-barva-cerna

And another one:
1. I'm on page https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/elektro-barva-cerna
2. I don't see selected filter "Color - black"

2023-11-07 13:27 UTC, romankuna commented
There are this problems now:

First scenario
1. i am on page https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/electronics
2. i select black color parameter
3. URL changed correctly https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/elektro-barva-cerna 
4. i choose brand "LG" from filter
5. i thing, URL is correctly https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/elektro-barva-cerna?filter=%7B%22brands%22%3A%5B%228a8dfdac-223b-41b6-a35d-a1577d376255%22%5D%7D 
![image](https://github.com/shopsys/shopsys/assets/60608926/c61820e5-17cd-4312-9be5-4e0b2c1c4cad)
6. when i remove color "black" parameter from filter, b**rand "LG" is remove too**


https://github.com/shopsys/shopsys/assets/60608926/3896c925-57a8-4e75-b665-27c300ff9a62

Second scenario
1. i am on page https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/tv-audio
2. i choose seo category "TV,audio plasma with HDMI" and i see correcty https://sh-seo-categories-with-ignored-filters.odin.shopsys.cloud/televize-audio-plasma-s-hdmi and selected parameters "Technology", "HDMI" 
3. i select brand "Hyundai" => i see still correctly seo category, with brand parameter
4. i select "screen size" parameter - value 27" 
5. now, after selecting Screen size paremeter, "Hyundai" parameter was removed automaticly - this is not correctly

https://github.com/shopsys/shopsys/assets/60608926/b8994eb3-be84-4065-b43a-77eda4dfb1b3

2023-11-15 13:01 UTC, tvikito approved these changes

2023-11-15 13:01 UTC, tvikito commented on project-base/storefront/helpers/filterOptions/seoCategories.ts
> +const mergeCurrentFlagOrBrandValuesWithNew = (currentValues: string[], newValues: string[] | undefined) => {
Can we use more generic name for this function? It doesn't work directly with brands or flags structure, so let's put proper name.

2023-11-15 16:44 UTC, sebaholesz commented on project-base/storefront/helpers/filterOptions/seoCategories.ts
> +const mergeCurrentFlagOrBrandValuesWithNew = (currentValues: string[], newValues: string[] | undefined) => {
I made it more generic in general. Thanks for the suggestion.

2023-11-16 09:14 UTC, tvikito approved these changes

2023-11-16 13:42 UTC, romankuna commented
Now it's ok for me

2023-11-20 08:46 UTC, pk16011990 approved these changes

2023-11-20 14:00 UTC, merged