add equal spacing to the Category page
shopsys/shopsys pull request #2900
Opened 2023-10-23 14:07 UTC by tvikito

| Q             | A
| ------------- | ---
|Description, reason for the PR| add equal spacing to the Category page
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2023-10-24 08:15 UTC, sebaholesz requested changes

2023-10-24 08:15 UTC, sebaholesz commented on UPGRADE-14.0.md
> +-   add equal add equal spacing to the Category page ([#2900](https://github.com/shopsys/shopsys/pull/2900))
You should remove the `add equal` as it is duplicated...

2023-10-24 08:37 UTC, tvikito commented on UPGRADE-14.0.md
> +-   add equal add equal spacing to the Category page ([#2900](https://github.com/shopsys/shopsys/pull/2900))
Ah, fixed. Thanks.

2023-10-27 09:54 UTC, pk16011990 approved these changes

2023-10-27 13:41 UTC, merged