[shopsys] added Symfony Toolbar to JavaScript Storefront
shopsys/shopsys pull request #2967
Opened 2024-01-04 16:55 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, the reason for the PR| It is hard to debug frontend API when running into an error on JavaScript Storefront without Symfony Toolbar and this PR solves that!
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

![Uploading Screenshot at Jan 04 17-51-58.png…]()

2024-01-04 18:40 UTC, grossmannmartin requested changes
Thanks for the PR 👍  

I'm unsure whether this will be counterproductive – the toolbar will not show all requests, only those made on the client side while browsing the storefront
see missing hashes in the toolbar, that are present in the profiler.

![Snímek obrazovky 2024-01-04 v 19 36 40](https://github.com/shopsys/shopsys/assets/1177414/ca244537-92f3-435e-a31e-98308fc143a2)


![Snímek obrazovky 2024-01-04 v 19 36 25](https://github.com/shopsys/shopsys/assets/1177414/17e5de47-5ad2-4c23-a07c-3892edaa9530)


Also, after the page refresh the last profile is displayed (for example `privacyPolicyArticle`), but many more queries were executed until the page was rendered. This may be confusing and lead developers to false beliefs that their backend is blazing fast although one of the executed queries is really slow.

2024-01-04 18:40 UTC, grossmannmartin commented on composer.json
> +        "mgdsoft/symfony-profiler-spa": "^1.0",
I think this should be as a dev dependency and also added in the project-base's composer.json file, right?

2024-01-04 18:40 UTC, grossmannmartin commented on symfony.lock
> +    },
can you please add this to the project-base/symfony.lock file?

2024-01-04 18:40 UTC, grossmannmartin commented on project-base/storefront/components/Basic/SymfonyToolbar/SymfonyToolbar.tsx
> +    return <Script src={url + '/bundles/symfonyprofilerspa/load_toolbar_spa.js'} strategy="beforeInteractive" />;
```suggestion
    return <Script src='/bundles/symfonyprofilerspa/load_toolbar_spa.js' strategy="beforeInteractive" />;
```

should be enough

2024-01-07 14:50 UTC, sebaholesz requested changes

2024-01-07 14:50 UTC, sebaholesz commented on project-base/storefront/helpers/errors/logException.ts
> +    if (isEnvironment('development')) {
Thinking if this shouldn't be a separate commit.

2024-01-07 14:50 UTC, sebaholesz commented on project-base/storefront/components/Basic/SymfonyToolbar/SymfonyToolbar.tsx
> +    if (!isEnvironment('development')) {
How do I turn this feature off as a developer? I say it should be possible to completely turn off (by ENV or whatever). I am not sure about other devs, but I personally do not want it there 😆

2024-01-23 12:06 UTC, closed without merging