[docs] added documentation about asynchronous processing
shopsys/shopsys pull request #2988
Opened 2024-01-15 14:12 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| Added documentation about asynchronous processing and product recalculations
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

----
:globe_with_meridians: Live Preview:
  - https://mg-async-docs.odin.shopsys.cloud
  - https://cz.mg-async-docs.odin.shopsys.cloud

2024-01-22 12:04 UTC, vitek-rostislav requested changes
Hi, nice job there, I have added a few suggestions so please, check them out.

Also, have you considered creating a cookbook? I can imagine a simple cookbook with the scenario "let's send a mail every time a product is created" that would help developers to understand the whole asynchronous system.

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +[Symfony/Messenger](https://symfony.com/doc/5.4/messenger.html) provides a message bus with the ability to send messages and then handle them immediately in your application or send them through tran
> through transports (e.g. queues) 

Are "queues" an example of transport? (I am referring to "e.g." notation which is quite confusing to me - would this be better?
```
through transports (e.g. into queues) 
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +### When is the message really sent?
In this paragraph, I am missing an explanation of why this is done this way. I believe it deserves a subparagraph called "Motivation" or something like that - the transactional request should be mentioned there and even maybe the extensibility (you do not need to think about the "timing" of the dispatch call thanks to the delays dispatching mechanism). We can discuss this of course

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +When a message fails to be processed (for example, due to an exception), it is sent to the failure transport.
I would add the information about the retries, something like this:
```
When a message fails to be processed (for example, due to an exception), and a [max retry count is exceeded](https://symfony.com/doc/current/messenger.html#retries-failures), it is sent to the failure transport.
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +that way only one pod will be deployed, and it will consume messages from both `example_transport` and `my_new_transport` queues in the order they are specified in the configuration (meaning no messa
love this explanation. It is a neat way how to explain the product priority queue. To make it perfect, I would mention the priority product recalculation.

```
 (meaning no messages from the `my_new_transport` will be processed until `example_transport` is empty). For example, this is the way how product recalculation priority is implemented (you can examine `product_recalculation_priority_regular` and `product_recalculation_priority_high` transports for detailed information).
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +that way two pods will be deployed, and each of them will consume messages independently
```suggestion
that way two pods will be deployed, and each of them will consume messages independently.
````

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +## Consumer infrastructure
Do not we want to mention CI? GitHub actions/GitlabCI configuration?

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +# Recalculations (price and visibility recalculation and export to Elasticsearch)
```suggestion
# Product Recalculations (price and visibility recalculation and export to Elasticsearch)
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +This approach is used instead of cron modules and allows, among other benefits, also to horizontally scale the recalculations.
If we want to have this sentence here, I would modify it this way:
```suggestion
This approach has been used since `14.0` version onwards instead of cron modules and allows, among other benefits, also to horizontally scale the recalculations.
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +This is a safety net to make sure all products are recalculated at least once a day to prevent inconsistencies in the catalog due to possible mistakes in the code.
```suggestion
This ensures the product is recalculated at the start of a new day to cover scenarios when it is supposed to be visible or hidden from a particular date (see `Product::$sellingFrom` and `$sellingTo` properties). Moreover, it is a safety net to make sure all products are recalculated at least once a day to prevent inconsistencies in the catalog due to possible mistakes in the code.
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +You should use the `handleDispatchedRecalculationMessages()` method to process all dispatched recalculation messages.
```suggestion
You should use the `Tests\App\Test\WebTestCase::handleDispatchedRecalculationMessages()` method to process all dispatched recalculation messages.
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +This command accepts ids of products, that should be dispatched, or `--all` option to dispatch all products.
```suggestion
This command accepts ids of products, that should be dispatched, or `--all` option to dispatch all products. You can also define the priority of the recalculations using `--priority` option.
```

2024-01-22 12:04 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +```
```suggestion
# dispatch product with id 22 into the high priority queue
./bin/console shopsys:dispatch:recalculations 22 --priority=high
```

note: I am not able ta add the three backticks into the suggestion :smile:

2024-01-22 13:53 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +[Symfony/Messenger](https://symfony.com/doc/5.4/messenger.html) provides a message bus with the ability to send messages and then handle them immediately in your application or send them through tran
changed in c4e7ce3832

2024-01-22 14:13 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +### When is the message really sent?
added motivation in b4544a3a41

2024-01-22 14:14 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +When a message fails to be processed (for example, due to an exception), it is sent to the failure transport.
added in fb23732ed6

2024-01-22 14:17 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +that way only one pod will be deployed, and it will consume messages from both `example_transport` and `my_new_transport` queues in the order they are specified in the configuration (meaning no messa
cool – 7bd137b9e9

2024-01-22 14:19 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +that way only one pod will be deployed, and it will consume messages from both `example_transport` and `my_new_transport` queues in the order they are specified in the configuration (meaning no messa
good idea – added in 7bd137b9e92ce9893410b28f6ff9d100927fdcea

2024-01-22 14:19 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +that way two pods will be deployed, and each of them will consume messages independently
👍 223cf23b6b

2024-01-22 14:22 UTC, grossmannmartin commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +## Consumer infrastructure
I'm not sure. GitHub actions are monorepo-specific, maybe some general info, or a Gitlab configuration... let's discuss it further

2024-01-22 14:43 UTC, grossmannmartin commented on docs/asynchronous-processing/product-recalculations.md
> +```
9c97f9a67b

2024-01-23 19:41 UTC, vitek-rostislav commented on docs/asynchronous-processing/introduction-to-asynchronous-processing.md
> +## Consumer infrastructure
ok, let's discuss it tomorrow, I think we can mention the GitLab configuration as the config is a part of project-base and is used by default by the Shopsys projects

2024-01-23 19:48 UTC, vitek-rostislav approved these changes
Thank you for the tweaks, I love the cookbook :ok_hand:  One more suggestion - could you please add a link to the cookbook somewhere into `docs/asynchronous-processing/introduction-to-asynchronous-processing.md` article? I suggest adding a headline "Try it yourself" at the end of the article followed by a short paragraph, something like "You can try implementing your own asynchronous notifier by following our [cookbook](link-to-the-cookbook))"

2024-01-24 15:26 UTC, pk16011990 approved these changes

2024-01-24 15:48 UTC, merged