add personalization to search
shopsys/shopsys pull request #2999
Opened 2024-01-24 09:55 UTC by tvikito

| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-01-24 11:24 UTC, vitek-rostislav requested changes

2024-01-24 11:24 UTC, vitek-rostislav commented on packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
> +                    requestingPage:
each search query now uses three input arguments - `search`, `requestingPage`, and `userIdentifier` - IMHO it would make sense to wrap them into an input object so we do not have to repeat ourselves.

2024-01-24 11:24 UTC, vitek-rostislav commented on packages/persoo/src/Model/Product/ProductSearchResultsProvider.php
> +        $requestingPage = $argument['requestingPage'] ?? '';
I believe the empty string can be set as a default value in `QueryDecorator.types.yaml`, would not it be better there?

2024-01-24 11:24 UTC, vitek-rostislav commented on packages/persoo/src/Model/Product/ProductSearchResultsProvider.php
> +            throw new InvalidArgumentUserError('Provided argument \'requestingPage\' is not in correct URL format.');
should not this be implemented as a validation (i.e. using constraint and validator)? I believe I can live without that but the design would be better with the validator IMHO.

One way or another, could you please add tests for this behavior?

(the same comment applies to `$userIdentifier` bellow)

2024-01-25 10:01 UTC, TomasLudvik commented on packages/persoo/src/Model/Product/ProductSearchResultsProvider.php
> +            throw new InvalidArgumentUserError('Provided argument \'requestingPage\' is not in correct URL format.');
We decided we do not want to follow this path now

2024-01-25 10:01 UTC, TomasLudvik commented on packages/persoo/src/Model/Product/ProductSearchResultsProvider.php
> +        $requestingPage = $argument['requestingPage'] ?? '';
We decided we do not want to follow this path now

2024-03-12 21:22 UTC, closed without merging