update repo dependencies
shopsys/shopsys pull request #3010
Opened 2024-01-31 14:40 UTC by tvikito

| Q             | A
| ------------- | ---
|Description, reason for the PR| update repo dependencies
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-01-31 15:19 UTC, sebaholesz approved these changes

2024-01-31 15:20 UTC, sebaholesz requested changes
Padaji Vitesty

2024-02-05 14:56 UTC, sebaholesz approved these changes

2024-02-07 11:40 UTC, pk16011990 approved these changes

2024-02-07 12:31 UTC, merged