[project-base] fixed entity extension test
shopsys/shopsys pull request #3011
Opened 2024-01-31 22:05 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| Entity extension test is now application independent and skipped on project (test is run only in monorepo)
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-02-01 08:32 UTC, vitek-rostislav requested changes

2024-02-01 08:32 UTC, vitek-rostislav commented on project-base/app/tests/App/Functional/EntityExtension/EntityExtensionTest.php
> +        // To ensure the changes in application does not brake this test, it's necessary to start with a clean database
```suggestion
// To ensure the changes in the application do not break this test, it's necessary to start with a clean database
```

2024-02-01 08:32 UTC, vitek-rostislav commented on project-base/app/tests/App/Functional/EntityExtension/EntityExtensionTest.php
> +        // test database is restored thanks to the transactional test case
```suggestion
// test database is restored after the test thanks to the usage of transactional test case
```

2024-02-01 08:32 UTC, vitek-rostislav commented on project-base/app/tests/App/Functional/EntityExtension/Model/Category/Category.php
> +    protected int $lft;
I am thinking - do we need so many attributes? In general, in the test entities, IMHO we do not need one type of a column more than once (e.g. in `Category`, I already have an integer column `$level` so `$lft` seems redundant, in `CategoryDomain`, there is `$seoTitle` so `$seoMetaDescription` and other string columns seem unnecessary as well, etc.). 

It seems like there is room for simplifying the test entities

2024-02-05 10:55 UTC, grossmannmartin commented on project-base/app/tests/App/Functional/EntityExtension/Model/Category/Category.php
> +    protected int $lft;
good idea, I have removed several columns and kept those I found interesting somehow.

2024-02-05 13:31 UTC, vitek-rostislav approved these changes

2024-02-07 13:46 UTC, pk16011990 approved these changes

2024-02-07 14:42 UTC, merged