[framework] added unique constraint to cart
shopsys/shopsys pull request #3017
Opened 2024-02-07 17:31 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| cart has to be unique in a DB
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-02-09 10:09 UTC, vitek-rostislav approved these changes
Neat! :slightly_smiling_face:

2024-02-09 10:18 UTC, vitek-rostislav requested changes
Hi, I tested it and sadly, it does not work as expected (probably because of the nullable `customer_user_id` column :frowning_face: )

![image](https://github.com/shopsys/shopsys/assets/10401898/7e1e5362-1959-416d-8c24-91b26bcb16e3)

2024-02-14 20:44 UTC, grossmannmartin commented
> Hi, I tested it and sadly, it does not work as expected (probably because of the nullable `customer_user_id` column ☹️ )

Thanks! Appreciate the testing :) 
I have fixed it by creating two partial indexes

2024-02-15 09:00 UTC, vitek-rostislav approved these changes
Hi, reviewed and tested :ok_hand: 

I have one suggestion - for future reference, could you please add an explanation on why this is not possible to achieve via `@ORM` annotation? I would put it into the PR description and commit message but I am ok with either of the places

2024-02-15 11:20 UTC, pk16011990 approved these changes

2024-02-15 13:54 UTC, merged