[shopsys] separate order item types
shopsys/shopsys pull request #3056
Opened 2024-03-06 07:43 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| Yes/No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes/No

2024-03-08 12:11 UTC, vitek-rostislav requested changes

2024-03-08 12:11 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Item/OrderItemFacade.php
> -        $order->addItem($orderProduct);
this was unnecessary as the method is called inside the constructor of `OrderItem` itself, right?

2024-03-08 12:11 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Item/OrderItemFactory.php
> +    public function createProductByOrderItemData(
one thought - do we need to rename the methods? It made sense from the project-base point of view as it was necessary to distinguish the original framework create* methods from the new approach. But at this moment, I believe we can have just `createPayment()`, `createProduct()`, and other `create*` methods without explicitly mentioning `ByOrderItemData`...

In the other entity factories, we also have just `create` methods, no need to mention the "by entity data". What do you think?

2024-03-08 12:11 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Mail/OrderMail.php
> -            self::VARIABLE_TRANSPORT => htmlspecialchars($order->getTransportName(), ENT_QUOTES),
why is `getTransportName` removed? I understand there might be multiple transports but `getTransportItem` still returns the first one so I would say we can still expose `getTransportName` and use `getTransportItem` inside it :thinking:

2024-03-08 12:11 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Order.php
> +     * @deprecated use getPaymentItem() instead
why haven't you removed it directly? Will it be removed anytime soon?

2024-03-08 12:11 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Order.php
> +     * @deprecated use getTransportItem() instead
same here, I would vote for immediate removal :innocent:

2024-03-08 12:11 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Mail/OrderMail.php
> -            self::VARIABLE_TRANSPORT => htmlspecialchars($order->getTransportName(), ENT_QUOTES),
edit: After I found out it was used just here and in one test, I understand the removal :+1:

2024-03-08 12:11 UTC, vitek-rostislav commented on project-base/app/src/Model/Order/OrderFacade.php
> -        $orderItemData->transport = $transport;
removing transport/payment properties from `OrderItemData` could simplify things but it seems like we need it there, right? E.g. for the form in admin.

Another idea - do not require transport as a parameter in `OrderItemFactory::createTransportByOrderItemData()` and use the one set in `orderItemData` (and throw an exception if not set?). I am not sure if it is a better approach :smile:

2024-03-08 12:11 UTC, vitek-rostislav commented on docs/cookbook/adding-a-new-order-item-type.md
> +<!TODO - add the rest of the cookbook after finish implementation of the middleware>
ok, I am looking forward to it :slightly_smiling_face:

2024-03-08 12:11 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +#### general instruction ([#<PR number>](https://github.com/shopsys/shopsys/pull/<PR number>))
:ok_hand:

2024-03-08 12:11 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +-   the following classes are now strictly typed:
https://github.com/shopsys/shopsys/issues/1876 still can not be closed, right? Do you have an idea when it will be solved completely? Probably with the removal of the order preview, right? :smile:

2024-03-08 12:11 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +#### add rounding and discount as a separate order item types ([#3056](https://github.com/shopsys/shopsys/pull/3056))
should this change be mentioned explicitly as well?
![image](https://github.com/shopsys/shopsys/assets/10401898/20b1e3af-28d4-4821-9519-741666004df2)

2024-03-08 12:11 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +#### add rounding and discount as a separate order item types ([#3056](https://github.com/shopsys/shopsys/pull/3056))
technically, it is not a BC break, right? So I believe it does not need to be mentioned :slightly_smiling_face:

2024-03-08 12:18 UTC, grossmannmartin commented on packages/framework/src/Model/Order/Item/OrderItemFacade.php
> -        $order->addItem($orderProduct);
Exactly :)

2024-03-08 12:23 UTC, grossmannmartin commented on packages/framework/src/Model/Order/Order.php
> +     * @deprecated use getPaymentItem() instead
Complete removal is not trivial and we have the task to do it. Check SSP-2159 in our internal backlog, or #1272 here

2024-03-08 12:23 UTC, grossmannmartin commented on packages/framework/src/Model/Order/Order.php
> +     * @deprecated use getTransportItem() instead
Complete removal is not trivial and we have the task to do it. Check SSP-2159 in our internal backlog, or #1272 here

2024-03-08 12:24 UTC, grossmannmartin commented on project-base/app/src/Model/Order/OrderFacade.php
> -        $orderItemData->transport = $transport;
I believe it's also related to the task with removal of transport and payment from the order (as mentioned above)

2024-03-08 12:24 UTC, grossmannmartin commented on docs/cookbook/adding-a-new-order-item-type.md
> +<!TODO - add the rest of the cookbook after finish implementation of the middleware>
me too 😄

2024-03-08 12:26 UTC, grossmannmartin commented on UPGRADE-15.0.md
> +-   the following classes are now strictly typed:
Most likely :) 
As the order process is altered in project-base, the fix seems not worthy the effort as we plan to rewrite the order process

2024-03-08 12:30 UTC, grossmannmartin commented on UPGRADE-15.0.md
> +#### add rounding and discount as a separate order item types ([#3056](https://github.com/shopsys/shopsys/pull/3056))
I thought that the mention of the removal of the interface was enough.
Reading that instruction, I would search for the usage of the interface and replace it.
If I have extended the OrderController, I find this usage and replace it, and if not, I have no problem :)

2024-03-08 12:50 UTC, grossmannmartin commented on packages/framework/src/Model/Order/Item/OrderItemFactory.php
> +    public function createProductByOrderItemData(
ok, that makes sense, changed in 5da7a01deb and 5dc9871b60

2024-03-08 13:41 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Order.php
> +     * @deprecated use getPaymentItem() instead
ok, thanks for the information :ok_hand:

2024-03-08 13:46 UTC, vitek-rostislav commented on packages/framework/src/Model/Order/Item/OrderItemFactory.php
> +    public function createProductByOrderItemData(
:ok_hand: I hope it wont mess with you during rebasing :smile:

2024-03-08 13:49 UTC, vitek-rostislav approved these changes

2024-03-12 07:23 UTC, pk16011990 approved these changes

2024-03-13 14:21 UTC, merged