[frontend-api] main blog category URL is now available via settings query
shopsys/shopsys pull request #3087
Opened 2024-04-02 16:54 UTC by vitek-rostislav

| Q             | A
| ------------- | ---
|Description, reason for the PR| There was no easy way how to access the main blog category URL so on the storefront, we had to fetch all the blog categories and then get the link from the first one which was sub-optimal :slightly_smiling_face: 
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-04-03 11:56 UTC, TomasLudvik requested changes

2024-04-03 11:56 UTC, TomasLudvik commented on packages/frontend-api/src/Resources/config/graphql-types/SettingsDecorator.types.yaml
> +            blogUrl:
Would not be better to name it as "mainBlogCategoryUrl" or "rootBlogCategoryUrl"?

2024-04-05 12:25 UTC, vitek-rostislav commented on packages/frontend-api/src/Resources/config/graphql-types/SettingsDecorator.types.yaml
> +            blogUrl:
good point, fixed and push forced :innocent:

2024-04-08 08:34 UTC, TomasLudvik approved these changes

2024-04-08 12:40 UTC, pk16011990 approved these changes

2024-04-09 05:32 UTC, merged