[frontend-api] cart is now correctly created for current customer user when carts are merged
shopsys/shopsys pull request #3112
Opened 2024-04-16 09:39 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, the reason for the PR| When carts were merged, new cart was incorrectly created without customer user association.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-04-17 08:22 UTC, grossmannmartin approved these changes

2024-04-19 10:18 UTC, grossmannmartin requested changes

2024-04-19 10:18 UTC, grossmannmartin commented on project-base/app/src/FrontendApi/Mutation/Cart/CartMutation.php
> +            if ($orderItem->getPromoCodeIdentifier() !== null) {
This identifier is removed in #3088 (https://github.com/shopsys/shopsys/pull/3088/commits/1bc3201a47937f4a20b0626772e6d54189927d74)
We should think about a different solution

2024-04-22 13:27 UTC, TomasLudvik commented on project-base/app/src/FrontendApi/Mutation/Cart/CartMutation.php
> +            if ($orderItem->getPromoCodeIdentifier() !== null) {
This should be solved different way during merge to 15.0

!!!PLEASE DO NOT CLOSE THIS COMMIT BEFORE MERGE, SO IT IS NOT FORGOTTEN!!!

2024-04-23 07:43 UTC, grossmannmartin approved these changes

2024-04-24 08:42 UTC, pk16011990 approved these changes

2024-04-26 09:13 UTC, merged