[project-base] friendly url fixes
shopsys/shopsys pull request #3115
Opened 2024-04-17 12:52 UTC by vitek-rostislav

| Q             | A
| ------------- | ---
|Description, reason for the PR| There are several bugs in the work with friendly URLs - the redirect does not work, and 500 error occur in various scenarios, see #3107 
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues|  closes #3107 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-04-17 15:28 UTC, grossmannmartin requested changes

2024-04-17 15:28 UTC, grossmannmartin commented on project-base/app/src/Component/Router/FriendlyUrl/FriendlyUrlMatcher.php
>              $matchedParameters['_controller'] = 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction';
the $matchedParameters array is created dynamically if I'm not mistaken... Is it ok?

2024-04-17 15:28 UTC, grossmannmartin commented on project-base/app/src/Model/Product/Flag/FlagRepository.php
> +            throw new FlagNotFoundException(sprintf('Flag with ID "%s" does not exist.', $flagId));
can it still be a problem in flagBreadcrumbGenerator? The exception is not caught there...

2024-04-19 10:45 UTC, vitek-rostislav commented on project-base/app/src/Component/Router/FriendlyUrl/FriendlyUrlMatcher.php
>              $matchedParameters['_controller'] = 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction';
good catch, fixed in 25eea475d1

2024-04-19 12:48 UTC, vitek-rostislav commented on project-base/app/src/Model/Product/Flag/FlagRepository.php
> +            throw new FlagNotFoundException(sprintf('Flag with ID "%s" does not exist.', $flagId));
that is a good point, added c190860950 commit

2024-04-20 17:13 UTC, grossmannmartin approved these changes

2024-04-23 09:43 UTC, pk16011990 approved these changes

2024-04-23 10:35 UTC, merged