[frontend-api] applied promo code is now taken into account in priceByTransportQuery and priceByPaymentQuery
shopsys/shopsys pull request #3118
Opened 2024-04-19 13:27 UTC by vitek-rostislav

| Q             | A
| ------------- | ---
|Description, reason for the PR| Transport and payment price is affected by total products price (including discounts) as there might be limit for free transport and payment. However, the promo code was omitted when the transport/payment price was calculated
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-04-22 08:54 UTC, grossmannmartin requested changes

2024-04-22 08:54 UTC, grossmannmartin commented on project-base/app/src/FrontendApi/Resolver/Price/PriceQuery.php
> +    public function priceByPaymentQuery(
I'm not sure about the paymentquery – the only difference against the original implementation is the @var annotation near cart variable.

2024-04-22 11:58 UTC, vitek-rostislav commented on project-base/app/src/FrontendApi/Resolver/Price/PriceQuery.php
> +    public function priceByPaymentQuery(
ah, thanks for pointing that out, it should have been like this: https://github.com/shopsys/shopsys/pull/3118/commits/e606c8e0d1246944c10117176e515f7b7bb8fb29

2024-04-24 10:19 UTC, grossmannmartin approved these changes

2024-04-24 10:47 UTC, merged