[shopsys] removed no longer used functionality of measuring scripts
shopsys/shopsys pull request #3122
Opened 2024-04-22 06:48 UTC by TomasLudvik

| Q             | A
| ------------- | ---
|Description, the reason for the PR| This functionality is no longer in use
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-04-22 14:11 UTC, vitek-rostislav requested changes
Hi, check the failing builds, please

2024-04-22 14:11 UTC, vitek-rostislav commented on UPGRADE-14.0.md
> +-   remove measuring scripts functionality ()
missing link :slightly_smiling_face:

2024-04-22 14:11 UTC, vitek-rostislav commented on UPGRADE-14.0.md
> +    -   if you do not want to remove functionality and are still using it, you should skip migration `Version20240222100000` and keep the functionality
it would be nice to be more specific here about what was removed. I would mention at least something like:
```
Shopsys\FrameworkBundle\Model\Script namespace was removed
```

2024-04-22 14:11 UTC, vitek-rostislav commented on project-base/app/src/Model/Security/Roles.php
> -                self::ROLE_SCRIPT_FULL => t('Scripts - full'),
the roles are still used in `security.yaml`. Also, the constant could be removed from this class along with `ROLE_SCRIPT_VIEW`, or?

2024-04-24 08:49 UTC, TomasLudvik commented on UPGRADE-14.0.md
> +    -   if you do not want to remove functionality and are still using it, you should skip migration `Version20240222100000` and keep the functionality
I hope that "measuring scripts functionality" with link to PR and link to project-base diff should be sufficient.

2024-04-24 12:49 UTC, vitek-rostislav approved these changes

2024-04-26 11:59 UTC, pk16011990 approved these changes

2024-04-29 05:22 UTC, merged