[framework] VACUUM FULL ANALYZE is now run once a week
shopsys/shopsys pull request #3160
Opened 2024-05-10 13:02 UTC by vitek-rostislav

| Q             | A
| ------------- | ---
|Description, reason for the PR| It is a good practice to garbage-collect the Postgres database once in a while in production. We added a CRON module that performs `VACUUM FULL ANALYZE` on the database once a week so we don't have to think about it and run it manually anymore.
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-05-10 18:01 UTC, henzigo commented on packages/framework/src/Component/Doctrine/VacuumFullAnalyzeCronModule.php
> +    protected function waitUntilOtherCronModulesOff(): void
Those functions are just duplicated in our base:

`waitUntilOtherCronModulesOff()` -> `CronWatchCommand`
`lockAllCronModules()` -> `CronLockCommand`
`maintenanceOn()` and `maintenanceOff()` -> `MaintenanceModeCommand`

2024-05-10 18:01 UTC, henzigo commented on packages/framework/src/Component/Doctrine/VacuumFullAnalyzeCronModule.php
> +            $this->makeVacuum();
I don't like the idea of making VACUUM FULL from the application. Additionally, you should run VACUUM FULL as an edge case and not regularly. 

Postgres has AUTOVACUUM that should handle bloat in databases. If you have miswritten your application then you have to use VACUUM FULL. Running it periodically covers problems in your application.

Another view can be that ANALYSE rebuilds all statistics instead of updating them. So this means that this command can negatively impact the performance of some SQL commands.

I don't say we should entirely avoid using VACUUM FULL, but we should do that manually as an edge case.

There is an outdated but still relevant article about it: https://wiki.postgresql.org/wiki/VACUUM_FULL

2026-03-14 14:25 UTC, vitek-rostislav commented on packages/framework/src/Component/Doctrine/VacuumFullAnalyzeCronModule.php
> +            $this->makeVacuum();
long time ago, we agreed we want this anyway :slightly_smiling_face:

2026-03-16 08:00 UTC, grossmannmartin requested changes

2026-03-16 08:00 UTC, grossmannmartin commented on project-base/app/config/cron.yaml
> +    Shopsys\FrameworkBundle\Component\Doctrine\VacuumFullAnalyzeCronModule:
I have a slightly bad feeling about the co-joined setting of time. Meaning the instance has 
`hours: '3', minutes: '15'`, and cron-vacuum is set to `15 3 * * 1`

1. I don't know how it behaves on these precise timings (both have the same time). 
2. It's really easy to forget about the other value when a change is needed.

2026-03-16 08:00 UTC, grossmannmartin commented on packages/framework/src/Component/Doctrine/VacuumFullAnalyzeCronModule.php
> +            );
Are other instances automatically locked? Isn't possible that another cron will run during vacuum?

2026-03-16 08:00 UTC, grossmannmartin commented on packages/framework/src/Component/Doctrine/VacuumFullAnalyzeCronModule.php
> +    public function run(): void
I still don't think this is a good idea in general 🤷‍♂️

2026-03-17 13:27 UTC, vitek-rostislav commented
ok, we are closing this now as it is considered a bad practice

2026-03-17 13:27 UTC, closed without merging