[shopsys] renamed cookie article setting to user consent policy
shopsys/shopsys pull request #3181
Opened 2024-05-27 10:22 UTC by grossmannmartin

| Q             | A
| ------------- | ---
|Description, reason for the PR| Cookies information was not descriptive enough and it was not unified across the codebase. Now it is renamed to better User consent policy
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-05-28 09:06 UTC, vitek-rostislav requested changes

2024-05-28 09:06 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +-   administrator roles `ROLE_COOKIES_FULL` and `ROLE_COOKIES_VIEW` were renamed to `ROLE_USER_CONSENT_POLICY_FULL` and `ROLE_USER_CONSENT_POLICY_VIEW`
there should be a migration for this change as well, right?

2024-05-28 09:06 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +-   see #project-base-diff to update your project
should we mention the API changes as well?

`cookiesArticleQuery` was renamed to `userConsentPolicyArticleQuery` in `ArticleQuery` and the field name (is it called "field"?) was changed from `cookiesArticle` to `userConsentPolicyArticleQuery` :slightly_smiling_face:

2024-05-28 22:20 UTC, grossmannmartin commented on UPGRADE-15.0.md
> +-   administrator roles `ROLE_COOKIES_FULL` and `ROLE_COOKIES_VIEW` were renamed to `ROLE_USER_CONSENT_POLICY_FULL` and `ROLE_USER_CONSENT_POLICY_VIEW`
Yes, yes it should. 
added in 3ccbfa66ca

2024-05-28 22:25 UTC, grossmannmartin commented on UPGRADE-15.0.md
> +-   see #project-base-diff to update your project
Good catch! thanks – d065a08fff

2024-05-29 09:22 UTC, vitek-rostislav approved these changes

2024-05-29 09:22 UTC, vitek-rostislav commented on packages/framework/src/Migrations/Version20240527121326.php
> +            WHERE :oldRole = ANY (SELECT jsonb_array_elements_text(roles::jsonb)::text)';
eh, one more reason why to avoid json in database columns? :smile:

2024-05-31 21:39 UTC, vitek-rostislav approved these changes

2024-06-05 07:54 UTC, vitek-rostislav approved these changes

2024-06-05 07:54 UTC, vitek-rostislav commented on UPGRADE-15.0.md
> +    -   if user consent article is not found, we do not display the footer link to the user consent update page, the consent update bar (`UserConsent.tsx`), and the consent update page throws returns
```suggestion
    -   if user consent article is not found, we do not display the footer link to the user consent update page, the consent update bar (`UserConsent.tsx`), and the consent update page returns 404
```

2024-06-05 07:54 UTC, vitek-rostislav commented on project-base/storefront/components/Layout/Footer/Footer.tsx
> +    );
the same block of code is used in `DeferredUserConsent.tsx`, I would say it is worth extracting into some helper method, what do you think?

2024-06-05 09:16 UTC, sebaholesz commented on project-base/storefront/components/Layout/Footer/Footer.tsx
> +    );
I extracted it, thanks for the suggestion.

2024-06-05 09:17 UTC, sebaholesz commented on UPGRADE-15.0.md
> +    -   if user consent article is not found, we do not display the footer link to the user consent update page, the consent update bar (`UserConsent.tsx`), and the consent update page throws returns
Thanks. I fixed it in the commit message as well.

2024-06-06 06:19 UTC, merged