[project-base] change free transport limit in demo data
shopsys/shopsys pull request #3199
Opened 2024-06-05 06:15 UTC by AndrejBlaho

| Q             | A
| ------------- | ---
|Description, reason for the PR| Free transport limit in demo data was too high, now it is more appropriate.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-06-05 08:37 UTC, vitek-rostislav requested changes
please, add an entry to the upgrade notes (just the "see project base diff" note :slightly_smiling_face:)

2024-06-11 07:11 UTC, pk16011990 approved these changes

2024-06-13 09:20 UTC, vitek-rostislav requested changes
please, add upgrade notes for the storefront part as well (the blackout of footer social links should be mentioned IMHO)

2024-06-13 10:24 UTC, vitek-rostislav approved these changes

2024-06-13 13:20 UTC, merged