[shopsys] top products are now in elasticsearch
shopsys/shopsys pull request #3242
Opened 2024-06-28 06:33 UTC by AndrejBlaho

| Q             | A
| ------------- | ---
|Description, reason for the PR| Top products data are now stored in and queried on frontend from elasticsearch which should lead to better performance.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-07-01 10:32 UTC, TomasLudvik requested changes

2024-07-01 10:32 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        protected array $domainTopProductsIndexedByProductId = [],
This should be only class property not dependency as it is not provided via dependency injection

2024-07-01 10:32 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +
It would be better to have a method for this to check if top products are loaded and load them if not and then return the value.

2024-07-01 10:32 UTC, TomasLudvik commented on project-base/app/src/FrontendApi/Resolver/Products/PromotedProductsQuery.php
This class can be removed now, right?

2024-07-01 10:32 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        protected readonly TopProductFacade $topProductFacade,
This should be mentioned in upgrade notes

2024-07-01 10:32 UTC, TomasLudvik commented on packages/frontend-api/src/Model/Resolver/Products/PromotedProductsQuery.php
> +        protected readonly ProductElasticsearchProvider $productElasticsearchProvider,
This should be mentioned in the upgrade notes

2024-07-08 04:31 UTC, AndrejBlaho commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        protected array $domainTopProductsIndexedByProductId = [],
what about $variantCache? should that be changed as well?

2024-07-08 04:36 UTC, AndrejBlaho commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +
I rewrote it. Is this how you meant it?

2024-07-08 04:48 UTC, AndrejBlaho commented on project-base/app/src/FrontendApi/Resolver/Products/PromotedProductsQuery.php
I remember brief discussion with @vitek-rostislav about this and conclusion was keep it as it is for some reason, but it makes sense to remove it as you suggest, so i deleted it for now. But i am not sure about the reasoning and most correct approach so please clarify.

2024-07-08 04:52 UTC, AndrejBlaho commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        protected readonly TopProductFacade $topProductFacade,
added

2024-07-08 04:52 UTC, AndrejBlaho commented on packages/frontend-api/src/Model/Resolver/Products/PromotedProductsQuery.php
> +        protected readonly ProductElasticsearchProvider $productElasticsearchProvider,
added as well

2024-07-08 08:34 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        protected array $domainTopProductsIndexedByProductId = [],
Yes, but you will have to mention it in UPGRADE notes.

2024-07-08 08:51 UTC, vitek-rostislav commented on project-base/app/src/FrontendApi/Resolver/Products/PromotedProductsQuery.php
well, the general reason is that when moving logic from project-base to the packages, it is easier to keep the empty class in project-base - we do not have a reverse function in the annotation fixer so we would have to rewrite all the usages manually then. Moreover, at least about some of the classes we can assume they will be overwritten on the particular project sooner or later (entities, data objects, facades, ...) so already extended empty project-base classes can help the developers a little in the future.

TLDR; I do not think the empty classes in the project-base can do any harm, rather it is the opposite.

2024-07-08 09:18 UTC, TomasLudvik requested changes

2024-07-08 09:18 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +    protected array $domainTopProductsIndexedByProductId = [];
```suggestion
    /**
      * @property array<int, \Shopsys\FrameworkBundle\Model\Product\TopProduct\TopProduct>|null
      */
    protected ?array $domainTopProductsIndexedByProductId = null;
```

2024-07-08 09:18 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +    protected array $domainTopProductsIndexedByProductId = [];
I have wrote this suggestion by hand, you might need to correct it :)

2024-07-08 09:18 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +
I would like you to use that method to also retrieve that product, so it could be named `getDomainTopProductById`-

2024-07-08 09:18 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        if (empty($this->domainTopProductsIndexedByProductId)) {
What if second domain ID is used?

2024-07-08 09:22 UTC, TomasLudvik commented on project-base/app/src/FrontendApi/Resolver/Products/PromotedProductsQuery.php
My opinion is, that it is ok to have empty classes for the basic functionality, that is always changed (entity, factory,...) but I would remove it for other less common scenarios. Reasons:
- searching for class is duplicate and you need to check if the functionality is extended or that class is empty
- annotation fixer causes changes in files that do not need to be reviewed
- projects have empty classes that are actually not extended

2024-07-10 08:36 UTC, TomasLudvik commented on packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
> +        if (!isset($this->domainTopProductsIndexedByDomainIdAndProductId[$domainId])) {
```suggestion
        if (!array_key_exists($domainId, $this->domainTopProductsIndexedByDomainIdAndProductId)) {
```

2024-07-10 08:36 UTC, TomasLudvik approved these changes

2024-07-19 09:40 UTC, TomasLudvik approved these changes

2024-07-22 06:00 UTC, pk16011990 approved these changes

2024-07-23 04:33 UTC, merged