[project-base][SSP-2259] added wheel click condition for safari navigation loading
shopsys/shopsys pull request #3260
Opened 2024-07-10 10:16 UTC by chlebektomas

| Q             | A
| ------------- | ---
|Description, reason for the PR| Safari needs a wheel click condition for opening links in a new tab without a loading skeleton in the current tab.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-07-10 19:28 UTC, sebaholesz requested changes

2024-07-10 19:28 UTC, sebaholesz commented on project-base/storefront/components/Basic/ExtendedNextLink/ExtendedNextLink.tsx
> +        const isWithoutOpeningInNewTab = !e.ctrlKey && !e.metaKey && e.button !== 1;
I would outsource `e.button !== 1` into a variable, or at least the `1`. Something like

const `isNotHoldingMouseWheel`, or something similar.

2024-07-11 14:52 UTC, pk16011990 approved these changes

2024-07-12 07:49 UTC, sebaholesz approved these changes

2024-07-12 07:57 UTC, merged