[project-base][SSP-1606] added info message to main product variant
shopsys/shopsys pull request #3267
Opened 2024-07-15 12:10 UTC by chlebektomas

| Q             | A
| ------------- | ---
|Description, reason for the PR| Added informational message for main product variant when no variants are available for purchase.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-07-15 15:50 UTC, sebaholesz requested changes

2024-07-15 15:50 UTC, sebaholesz commented on project-base/storefront/public/locales/cs/common.json
> +    "None of the product variants are available for purchase.": "Aktuálně není možné koupit ani jednu variantu produktu.",
I do not care if you're going to keep the Czech or English version, but the Czech version includes info about this being a temporary state (Aktualne), whereas the English version does not. I would just unify this somehow.

2024-07-16 07:03 UTC, sebaholesz approved these changes

2024-07-22 08:07 UTC, pk16011990 approved these changes

2024-07-22 10:12 UTC, merged