[project-base][SSP-2465] Add search parameters to queries
shopsys/shopsys pull request #3298
Opened 2024-08-01 16:59 UTC by JanMolcik

| Q             | A
| ------------- | ---
|Description, reason for the PR| To match the order of parametric filters from luigis box, FE now includes order of previous search result in SearchQuery and SearchProductsQuery
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ... 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

2024-08-02 08:58 UTC, chlebektomas commented
Please check failing step `Docker build / Check standards`

2024-08-02 09:01 UTC, chlebektomas requested changes
Please check failing step `Docker build / Check standards`

2024-08-03 09:08 UTC, chlebektomas approved these changes

2024-08-05 06:29 UTC, sebaholesz approved these changes

2024-08-09 17:57 UTC, merged