Sh ssp 2454 color system
shopsys/shopsys pull request #3311
Opened 2024-08-05 12:13 UTC by sebaholesz

#### Description, the reason for the PR
...

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-08-05 17:00 UTC, JanMolcik requested changes

2024-08-05 17:00 UTC, JanMolcik commented on project-base/storefront/tailwind.config.js
> +            textAccent: '#004EB6',
Is there a reason you are using `camelCase` instead of `kebab-case`? For example this `textAccent` could be `'text-accent'` and then could be used as `text-text-accent` instead of mixing two different naming types.

2024-08-05 17:00 UTC, JanMolcik commented on project-base/storefront/tailwind.config.js
> +            background: '#FFFFFF',
Wouldn't it be possible, instead of prepending the position in the general `colors` section (eg. `backgroundMore`, `backgroundBrand` etc.) to put it in `extend` of the specific position colour? 

```js
module.exports = {
    theme: {
        colors: {
           ...
        },
      
        extend: {
            backgroundColor: {
                more: '#FAFAFA',
                ...
            },
        },
        plugins: [],
    },
};

```

2024-08-06 08:46 UTC, JanMolcik approved these changes

2024-08-06 09:30 UTC, sebaholesz commented on project-base/storefront/tailwind.config.js
> +            textAccent: '#004EB6',
This was agreed in the team to keep as-is.

2024-08-06 09:30 UTC, sebaholesz commented on project-base/storefront/tailwind.config.js
> +            background: '#FFFFFF',
This was agreed in the team to keep as-is.

2024-08-07 19:50 UTC, merged