Product form type fix
shopsys/shopsys pull request #3320
Opened 2024-08-07 11:42 UTC by stanoMilan

After upgrading to platform 14.0, the product form type in the administration does not display the new attributes: "Hidden on domain" and "Warehouse". This pull request fixes this issue by ensuring these attributes are correctly displayed.

2024-08-22 09:43 UTC, TomasLudvik approved these changes

2024-08-22 12:56 UTC, vitek-rostislav commented
Hi, the build is failing on 
```
Shopsys Platform > error-pages-generate:

19/19 [=========] 100, Elapsed: 0h 00m 00s, Remaining: 0h 00m 00s, MEM: 90.5 MiBPHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction.php on line 18
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/symfony/routing/Loader/AnnotationFileLoader.php on line 87
```

Is that something that is already resolved in the 15.0 version? Probably by this - https://github.com/shopsys/shopsys/pull/3162

2024-08-22 13:02 UTC, vitek-rostislav requested changes

2024-08-22 13:02 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Product/ProductFormType.php
> +            'label' => t('Hide on domain'),
translations need to be dumped - they should be moved from project-base to framework as well

2024-08-23 11:38 UTC, vitek-rostislav approved these changes
you will need to fix the standards yet :wink:

2024-08-26 09:53 UTC, merged