[project-base] [SSP-2564] fixed responsive design in mobile menu and on cart page
shopsys/shopsys pull request #3324
Opened 2024-08-08 16:42 UTC by sebaholesz

#### Description, the reason for the PR
This PR fixes various issues with responsive design after color scheme changes.

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-08-12 08:32 UTC, chlebektomas requested changes

2024-08-12 08:32 UTC, chlebektomas commented on project-base/storefront/components/Blocks/PromoCode/PromoCode.tsx
> +                                <div className="flex max-w-sm">
In this case, I would stick to the gap with the original design as well. Please check https://shopsys.atlassian.net/browse/SSP-2527 for more info.

2024-08-12 08:32 UTC, chlebektomas commented on project-base/storefront/components/Blocks/PromoCode/PromoCode.tsx
>                          variant="inverted"
Based on this issue https://shopsys.atlassian.net/browse/SSP-2527 I would keep the original design with the primary variant. Clicking area is more obvious then.

2024-08-12 08:32 UTC, chlebektomas commented on project-base/storefront/components/Blocks/PromoCode/PromoCode.tsx
> +                                            className: '!rounded-r-none border-r-0',
Same thing here based on https://shopsys.atlassian.net/browse/SSP-2527.

2024-08-13 06:59 UTC, chlebektomas approved these changes

2024-08-14 07:17 UTC, pk16011990 approved these changes

2024-08-14 09:13 UTC, merged