Move category parametrs to framework package
shopsys/shopsys pull request #3336
Opened 2024-08-13 10:33 UTC by stanoMilan

Move Category parameters from project base to framework

2024-08-27 09:43 UTC, TomasLudvik approved these changes

2024-08-28 08:26 UTC, vitek-rostislav requested changes
Hi, please check the failing standards + my comments

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +     * @param \App\Model\Category\Category|null $category
```suggestion
     * @param \Shopsys\FrameworkBundle\Model\Category\Category|null $category
```
App namespace must not be used in the framework

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +     * @param \App\Model\Category\Category|null $category
```suggestion
     * @param \Shopsys\FrameworkBundle\Model\Category\Category|null $category
```
App namespace must not be used in the framework

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +    protected function buildFilterParameters(FormBuilderInterface $builder, ?\App\Model\Category\Category $category): void
use `Shopsys\FrameworkBundle\Model\Category\Category`, please

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +        $parametersFilterBuilder = $builder->add('parametersGroup', GroupType::class, ['label' => t('Filter parameters')]);
the translations should be moved in the po files as well

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +            'label' => t('Parameters order in category'),
the translations should be moved in the po files as well

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +            'label' => t('Filter parameters closed by default'),
the translations should be moved in the po files as well

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +        $parametersFilterBuilder->add('parametersCollapsed', ChoiceType::class, [
`CategoryData::$parametersCollapsed` property is still defined in the project-base, it should be moved as well, right?

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +        $parametersFilterBuilder->add('parametersPosition', SortableValuesType::class, [
`CategoryData::$parametersPosition` property is still defined in the project-base, it should be moved as well, right?

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Parameter/ParameterRepository.php
> +     * @param \App\Model\Category\Category $category
framework namespace, please

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Parameter/ParameterRepository.php
> +     * @return \App\Model\Product\Parameter\Parameter[]
framework namespace, please

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Parameter/ParameterRepository.php
> +     * @param \App\Model\Category\Category $category
framework namespace, please

2024-08-28 08:26 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Parameter/ParameterRepository.php
> +            ->join(\App\Model\Product\Product::class, 'product', Join::WITH, 'ppv.product = product')
framework namespace, please

2024-08-28 10:15 UTC, vitek-rostislav approved these changes

2024-09-02 09:17 UTC, merged