[project-base] limiting image size options propagated for resizing in CDN to predefined set of options
shopsys/shopsys pull request #3349
Opened 2024-08-15 15:39 UTC by AndrejBlaho

#### Description, the reason for the PR
This pull request introduces a limitation on the ImageResizer in shopsys/project-base/app/web/imageResizer.php to prevent potential abuse by restricting the range of allowable image dimensions. The changes ensure that only predefined dimensions are accepted, reducing the risk of CDN overload from generating numerous image sizes via malicious requests.

Previously, the ImageResizer allowed for arbitrary dimensions, which could be exploited by attackers to flood the CDN with a large number of image resize requests. This PR restricts the allowed dimensions to a predefined set (e.g., 30, 50, 200, 350, 500, 1000). When a request for an unsupported size is received, the nearest larger allowed size will be returned, or the maximum allowed size if the requested size exceeds it. This enhancement safeguards the system by minimizing unnecessary CDN load and ensuring better performance and security.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-08-16 12:55 UTC, grossmannmartin requested changes

2024-08-16 12:55 UTC, grossmannmartin commented on project-base/app/web/imageResizer.php
> +function getClosestAllowedDimension(int $requestedSize, array $allowedSizes): int {
this function poses two problems: 
1. for every number lower than 1000, it returns 1000
2. it's dependent on the order of elements in the array

Both problems may be solved by sorting the $allowedDimensions array first (from lowest number to highest).

2024-08-16 12:55 UTC, grossmannmartin commented on project-base/app/web/imageResizer.php
> +function getClosestAllowedDimension(int $requestedSize, array $allowedSizes): int {
can you put the function at the end of the file to the rest of the functions?

2024-08-16 12:55 UTC, grossmannmartin commented on project-base/app/web/imageResizer.php
> +$allowedDimensions = [1000, 500, 350, 200, 50, 30];
This array could be higher as it's one of a few things that the project may modify.

Also. I would unify the variable names in function and in array declaration

2024-08-16 12:55 UTC, grossmannmartin commented on project-base/app/web/imageResizer.php
> +$width = getClosestAllowedDimension($width, $allowedDimensions);
I would merge these lines with the initialization, or move them closer together, so it's clear what is happening.

```php
$resize = $_GET['resize'] ?? 'fit';
$width = getClosestAllowedDimension((int)($_GET['width'] ?? 0), $allowedDimensions);
$height = getClosestAllowedDimension((int)($_GET['height'] ?? 0), $allowedDimensions);
$gravity = 'no';
$enlarge = 1;
```

or 

```php
$resize = $_GET['resize'] ?? 'fit';
$width = (int)($_GET['width'] ?? 0);
$width = getClosestAllowedDimension($width, $allowedDimensions);
$height = (int)($_GET['height'] ?? 0);
$height = getClosestAllowedDimension($height, $allowedDimensions);
$gravity = 'no';
$enlarge = 1;
```

2024-08-19 08:24 UTC, AndrejBlaho commented on project-base/app/web/imageResizer.php
> +function getClosestAllowedDimension(int $requestedSize, array $allowedSizes): int {
sure

2024-08-19 08:32 UTC, AndrejBlaho commented on project-base/app/web/imageResizer.php
> +function getClosestAllowedDimension(int $requestedSize, array $allowedSizes): int {
1. you are right, now it should be ok
2. is it ok if we will leave it as it is or should i put there sorting function?

2024-08-19 08:32 UTC, AndrejBlaho commented on project-base/app/web/imageResizer.php
> +$allowedDimensions = [1000, 500, 350, 200, 50, 30];
done both

2024-08-19 08:33 UTC, AndrejBlaho commented on project-base/app/web/imageResizer.php
> +$width = getClosestAllowedDimension($width, $allowedDimensions);
done

2024-08-22 08:35 UTC, grossmannmartin approved these changes

2024-08-22 08:35 UTC, grossmannmartin commented on project-base/app/web/imageResizer.php
> +}
please end file with line break

2024-08-22 08:35 UTC, grossmannmartin commented on project-base/app/web/imageResizer.php
> +function getClosestAllowedDimension(int $requestedSize, array $allowedSizes): int {
2. I would add a sorting function - to prevent bad usage

2024-08-28 07:31 UTC, merged