[project-base][SSP-2560] redesigned radio and inverted button hover
shopsys/shopsys pull request #3358
Opened 2024-08-19 12:12 UTC by chlebektomas

#### Description, the reason for the PR
Radio button has a new design and added hover effect to inverted button.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-08-19 16:04 UTC, JanMolcik requested changes

2024-08-19 16:04 UTC, JanMolcik commented on project-base/storefront/components/Blocks/Pagination/Pagination.tsx
> +                        : 'bg:actionInvertedBackground border:actionInvertedBorder text-actionInvertedText hover:bg-actionInvertedBackgroundHovered hover:border-actionInvertedBorderHovered hover:text
Probably typo `bg-actionInvertedBackground`

2024-08-20 06:52 UTC, chlebektomas commented on project-base/storefront/components/Blocks/Pagination/Pagination.tsx
> +                        : 'bg:actionInvertedBackground border:actionInvertedBorder text-actionInvertedText hover:bg-actionInvertedBackgroundHovered hover:border-actionInvertedBorderHovered hover:text
fixed

2024-08-20 12:57 UTC, JanMolcik approved these changes

2024-08-28 13:16 UTC, merged