[shopsys] moved friendly urls from project-base to the framework
shopsys/shopsys pull request #3368
Opened 2024-08-23 10:08 UTC by TomasLudvik

#### Description, the reason for the PR
Some of the framework functionality was dependent on functionality in the project-base, so this PR moves it to the framework.

#### Fixes issues
closes #3297 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-08-23 12:19 UTC, vitek-rostislav requested changes

2024-08-23 12:19 UTC, vitek-rostislav commented on packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlData.php
> +    public $entityId;
could you please remove the original `FriendlyUrlData::$id`? It looks like it is not used anywhere (but the removal should be mentioned in the upgrade notes then anyway)

2024-08-23 12:19 UTC, vitek-rostislav commented on packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
> +        $friendlyUrl->setLastModification(new DateTime('now', new DateTimeZone('UTC')));
I believe you do not need to set the timezone here, it is UTC by default

2024-08-23 12:19 UTC, vitek-rostislav commented on packages/framework/src/Migrations/Version20240108154624.php
> +class Version20240108154624 extends AbstractMigration
:ok_hand:

2024-08-23 12:19 UTC, vitek-rostislav commented on packages/framework/src/Model/Blog/Article/BlogArticleDetailFriendlyUrlDataProvider.php
> -    protected function createFromIdAndName(int $id, string $name): FriendlyUrlData
this removal should be mentioned in the upgrade notes

2024-08-23 12:19 UTC, vitek-rostislav commented on packages/framework/src/Model/Blog/Category/BlogCategoryDetailFriendlyUrlDataProvider.php
> -    public function createFromIdAndName(int $id, string $name): FriendlyUrlData
this removal should be mentioned in the upgrade notes

2024-08-26 09:30 UTC, vitek-rostislav approved these changes

2024-09-02 13:46 UTC, vitek-rostislav approved these changes

2024-09-02 13:46 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/ProductFacade.php
> +     * @param array $originalNames
```suggestion
     * @param string[] $originalNames
```

2024-09-02 13:46 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/ProductFacade.php
> +     * @param array $originalNames
```suggestion
     * @param string[] $originalNames
```

2024-09-02 13:46 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/ProductFacade.php
> +     * @return array
```suggestion
     * @return string[]
```

2024-09-03 06:25 UTC, vitek-rostislav commented
Hi, check the tests please

2024-09-04 09:22 UTC, vitek-rostislav approved these changes

2024-09-05 09:14 UTC, pk16011990 approved these changes

2024-09-06 08:56 UTC, merged