Fix flag friendly url not found after upgrade to 14 and deploy to server
shopsys/shopsys pull request #3403
Opened 2024-09-04 10:15 UTC by stanoMilan

After upgrading our project to version 14.0, querying for products results in an internal server error. This issue occurs because the friendly URL for flags is not found. This Pull Request addresses the problem by fixing the logic responsible for retrieving the friendly URL, preventing the internal server error during product queries.

2024-09-06 09:38 UTC, TomasLudvik approved these changes

2024-09-07 09:21 UTC, vitek-rostislav requested changes

2024-09-07 09:21 UTC, vitek-rostislav commented on UPGRADE-14.0.md
> +
```suggestion
-   see #project-base-diff to update your project

```

2024-09-09 10:34 UTC, vitek-rostislav approved these changes

2024-09-09 10:34 UTC, merged