[project-base][SSP-2682] removed hp headlines when no data available
shopsys/shopsys pull request #3436
Opened 2024-09-15 18:47 UTC by chlebektomas

#### Description, the reason for the PR
Currently, the homepage does not display section headlines when there is no data available for that specific section.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-09-16 10:37 UTC, JanMolcik requested changes

2024-09-16 10:37 UTC, JanMolcik commented on project-base/storefront/components/Blocks/Product/PromotedProducts/DeferredPromotedProducts.tsx
Is there a reason to have two `DeferredPromotedProducts.tsx` files? Please check.

2024-09-16 10:42 UTC, chlebektomas commented on project-base/storefront/components/Blocks/Product/PromotedProducts/DeferredPromotedProducts.tsx
sure not, removed :)

2024-09-16 15:16 UTC, JanMolcik approved these changes

2024-09-18 08:44 UTC, JanMolcik approved these changes

2024-09-23 08:19 UTC, merged