[project-base] unified date format based on localization
shopsys/shopsys pull request #3471
Opened 2024-10-03 11:38 UTC by chlebektomas

- specific localization needs to be imported in file formatDate.ts from dayjs/locale

#### Description, the reason for the PR
Display dates in the user's local format for improved localization and user experience.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-10-03 12:06 UTC, JanMolcik requested changes

2024-10-03 12:06 UTC, JanMolcik commented on project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailBasicInfo.tsx
> +                <div className="flex  flex-wrap gap-6 gap-y-2 vl:gap-8">
Here is a small typo (extra space between `flex  flex-wrap`.

2024-10-03 12:06 UTC, JanMolcik commented on upgrade-notes/storefront_20241003_113606.md
> +-   specific localization needs to be imported in file formatDate.ts from
I would include an example of the import as it is in the stack overflow for better understanding eg. `import 'dayjs/locale/en-gb';`

2024-10-03 12:13 UTC, JanMolcik approved these changes

2024-10-08 14:11 UTC, pk16011990 approved these changes

2024-10-09 11:01 UTC, merged