SSP-2279 - extended datafixtures by subcategories in the menu
shopsys/shopsys pull request #3489
Opened 2024-10-09 09:40 UTC by AmpMVn

#### Description, the reason for the PR
Added subcategory to menu in datafixtures

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-10-10 13:30 UTC, vitek-rostislav requested changes
Hi, I have added a few suggestions, and also, check the failing tests, please.

2024-10-10 13:30 UTC, vitek-rostislav commented on project-base/app/src/DataFixtures/Demo/NavigationItemDataFixture.php
> +     * @param array $categoriesByColumn
```suggestion
     * @param array<int, string[]> $categoriesByColumn
```

2024-10-10 13:30 UTC, vitek-rostislav commented on project-base/app/src/DataFixtures/Demo/NavigationItemDataFixture.php
> +                function ($category) {
```suggestion
                function (string $category) {
```

2024-10-10 13:30 UTC, vitek-rostislav commented on project-base/app/src/DataFixtures/Demo/NavigationItemDataFixture.php
> +        array $categoriesByColumn,
I would rather name this parameter `$categoryReferenceNamesByColumn`

2024-10-10 13:30 UTC, vitek-rostislav commented on project-base/app/src/DataFixtures/Demo/NavigationItemDataFixture.php
> +        foreach ($categoriesByColumn as $columnNumber => $categories) {
...and this `$categoryReferenceNames`, but I do not insist on that, it just feels more understandable that way

2024-10-11 09:40 UTC, vitek-rostislav approved these changes

2024-10-14 12:02 UTC, pk16011990 approved these changes

2024-10-17 09:15 UTC, merged