Do not log out the user after changing the password
shopsys/shopsys pull request #3532
Opened 2024-10-23 10:43 UTC by AmpMVn

#### Description, the reason for the PR
Every time the password was changed, all tokens were deleted and the user was logged out. I modified the method so that the excludedDeviceId parameter is optional, which is not deleted from the tokens and the user remains logged in after changing their password.

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-10-24 06:26 UTC, TomasLudvik requested changes

2024-10-24 06:26 UTC, TomasLudvik commented on packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
>          $this->runCheckUserIsLogged();
This is redundant now

2024-10-31 08:51 UTC, TomasLudvik approved these changes

2024-10-31 14:12 UTC, pk16011990 approved these changes

2024-11-01 07:08 UTC, merged