[project-base] fixed product edit in development environment
shopsys/shopsys pull request #3544
Opened 2024-10-30 09:53 UTC by grossmannmartin

#### Description, the reason for the PR
Fixes array to string conversion error on product edit in the development environment.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-10-31 07:54 UTC, vitek-rostislav requested changes
Could you please move the code from project-base to the framework package? (along with `project-base/app/assets/js/admin/validation/uniqueProductCatnumValidator.js` :slightly_smiling_face: )

2024-10-31 14:53 UTC, vitek-rostislav requested changes
one more thing :pray: `Product::$catnum` is still overridden in `project-base` to be set non-nullable and unique, could you move that into the `framework` package as well? Btw, the migration you will be looking for is `Version20200720134134`

2024-11-01 10:19 UTC, vitek-rostislav approved these changes

2024-11-04 05:17 UTC, pk16011990 approved these changes

2024-11-04 08:37 UTC, merged