[shopsys] register company after order is more user friendly on b2b domain
shopsys/shopsys pull request #3546
Opened 2024-10-30 14:52 UTC by grossmannmartin

#### Description, the reason for the PR

On B2B domain, the customer cannot be registered if company with the same number is already registered. 
This PR does not display the after-order registration form if company number is already registered. 
Also, when the customer cannot be registered, the info message is shown to the customer.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [x] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

----
:globe_with_meridians: Live Preview:
  - https://mg-register-company.odin.shopsys.cloud
  - https://cz.mg-register-company.odin.shopsys.cloud

2024-10-31 11:49 UTC, vitek-rostislav commented on packages/frontend-api/src/Resources/config/graphql-types/Query/QueryDecorator.types.yaml
> +            isCompanyRegisteredQuery:
Could you please unify it into one query with `isCustomerUserRegisteredQuery` and rename it to something better? Like `couldBeCustomerUserRegistered` or `isCustomerUSerRegistrationPossible` or anything like that

2024-10-31 11:50 UTC, vitek-rostislav requested changes

2024-10-31 11:50 UTC, vitek-rostislav commented on packages/frontend-api/src/Resources/config/graphql-types/Query/QueryDecorator.types.yaml
> +            isCompanyRegisteredQuery:
Could you please unify it into one query with `isCustomerUserRegisteredQuery` and rename it to something better? Like `couldBeCustomerUserRegistered` or `isCustomerUSerRegistrationPossible` or anything like that

2024-11-04 10:32 UTC, vitek-rostislav approved these changes

2024-11-04 10:36 UTC, chlebektomas approved these changes

2024-11-06 13:07 UTC, pk16011990 approved these changes

2024-11-06 21:13 UTC, merged