[shopsys] upgrade to Symfony 6.4
shopsys/shopsys pull request #3584
Opened 2024-11-08 12:18 UTC by TomasLudvik

#### Description, the reason for the PR
Symfony 5.4 lifecycle is ending so it is right time to upgrade to latest Symfony LTS.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-11-14 13:35 UTC, vitek-rostislav commented
@coderabbitai review

2024-11-14 14:16 UTC, vitek-rostislav requested changes

2024-11-14 14:16 UTC, vitek-rostislav commented on composer.json
> +        "shopsys/jsformvalidator-bundle": "2.0.x-dev",
please let's not forget to release the `2.0` version of the bundle and use it here

2024-11-14 14:16 UTC, vitek-rostislav commented on packages/administration/composer.json
>          "symfony/form": "^5.4",
why some of the packages are kept at `^5.4` version? I would like to upgrade them all :slightly_smiling_face:

2024-11-14 14:16 UTC, vitek-rostislav commented on project-base/app/tests/App/Test/WebTestCase.php
> +    }
could you please extract it into a helper, trait, common parent, or something like that so we avoid duplication with the code in `HttpSmokeTestCase`? :pray:

2024-11-14 14:16 UTC, vitek-rostislav commented on project-base/app/tests/App/Smoke/NewProductTest.php
> +        $client->submit($form);
I am surprised it works even without the CSRF token :open_mouth:

2024-11-14 14:16 UTC, vitek-rostislav commented on project-base/app/tests/App/Smoke/NewProductTest.php
> +        $client->submit($form);
I am surprised it works even without the CSRF token :open_mouth:

2024-11-14 14:16 UTC, vitek-rostislav commented on project-base/app/config/services.yaml
> +        lazy: true
should not this whole service definition be in the framework package?

2024-11-14 14:16 UTC, vitek-rostislav commented on packages/framework/tests/Unit/Model/Security/LoginListenerTest.php
>      public function testOnSecurityInteractiveLoginUnique(): void
`testOnSecurityInteractiveLoginUnique` and `testOnSecurityInteractiveLoginAdministrator` methods are now identical :slightly_smiling_face:

2024-11-14 14:16 UTC, vitek-rostislav commented on packages/framework/src/Form/Constraints/UniqueBillingAddress.php
>       * @phpcsSuppress SlevomatCodingStandard.TypeHints.PropertyTypeHint.MissingNativeTypeHint
the suppress can be removed now, right? (it is on multiple places yet)

2024-11-14 14:16 UTC, vitek-rostislav commented on packages/framework/src/Form/Constraints/UniqueBillingAddress.php
> +    protected const array ERROR_NAMES = [
I see this change in +-2 classes only, what about the rest of the classes that extend `Symfony\Component\Validator\Constraint`?

2024-11-15 07:57 UTC, TomasLudvik commented on project-base/app/config/services.yaml
> +        lazy: true
Can be, it was not moved yet

2024-11-15 08:12 UTC, TomasLudvik commented on project-base/app/tests/App/Test/WebTestCase.php
> +    }
Those are a bit different use cases and without same parent I decided to keep it as it is.

2024-11-15 09:52 UTC, vitek-rostislav commented on project-base/app/tests/App/Test/WebTestCase.php
> +    }
ok :upside_down_face:

2024-11-15 10:04 UTC, vitek-rostislav approved these changes

2024-11-25 12:08 UTC, merged