[project-base] custom select
shopsys/shopsys pull request #3588
Opened 2024-11-11 11:11 UTC by chlebektomas

#### Description, the reason for the PR
Created a new select box featuring a combo box option and infinite scrolling within the selection list. Updated style guide as well.

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-11-11 13:30 UTC, JanMolcik requested changes
We can remove the `react-select` from dependancies (`package.json` file) now.

Also, you have removed the custom animation, so `.animate-fadeOut` class definition can also be removed from `globals.css` file. Have you consider fixing animations? Seems like there is only animation when the menu is appearing, but not disappearing.

2024-11-12 18:02 UTC, JanMolcik approved these changes
Approved. Before moving to tests, check the pipeline and fix failing storefront build, translations and standards please.

2024-11-13 09:43 UTC, JanMolcik approved these changes

2024-11-25 08:05 UTC, pk16011990 approved these changes

2024-11-26 08:45 UTC, merged