Uploaded files can be open in a browser
shopsys/shopsys pull request #3589
Opened 2024-11-11 13:19 UTC by malyMiso

#### Description, the reason for the PR
Uploaded files can be configured to being streamed to a browser instead of downloading. 

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2026-03-16 13:36 UTC, vitek-rostislav commented
I do not think we should close this, let's rather process it :slightly_smiling_face:

2026-03-31 16:46 UTC, grossmannmartin approved these changes

2026-03-31 16:46 UTC, grossmannmartin commented on packages/framework/src/Controller/Front/UploadedFileController.php
> +                throw new NotFoundRedirectToStorefrontException(
can't we just fallback to download url?

2026-04-17 09:58 UTC, grossmannmartin approved these changes

2026-04-17 09:58 UTC, grossmannmartin commented on packages/administration/translations/messages.en.po
> +msgstr "View"
English translations should not be filled if are the same

2026-04-29 09:31 UTC, grossmannmartin requested changes

2026-04-29 09:31 UTC, grossmannmartin commented on packages/framework/build.xml
> +            <arg value="shopsys:recalculate-file-sizes"/>
This command will be run after each deploy, but it's needed just once.

@pk16011990, please verify if it's ok by you. Otherwise, we could add some list of executed tasks (similar to database migration table)

2026-04-29 09:31 UTC, grossmannmartin commented on packages/framework/src/Command/RecalculateFileSizesCommand.php
If we want to improve performance even further, we can bypass entity hydration completely and return only the IDs of files without filesize set.
That lower the memory usage and we won't need to clear entity manager

2026-04-29 09:31 UTC, grossmannmartin approved these changes

2026-05-04 12:28 UTC, grossmannmartin approved these changes

2026-05-05 13:28 UTC, pk16011990 commented on packages/framework/build.xml
> +            <arg value="shopsys:recalculate-file-sizes"/>
Good point! @TomasLudvik, if it is not too complicated, pls do it.

2026-05-12 10:15 UTC, grossmannmartin commented on packages/framework/src/Command/RunPostDeployTasksCommand.php
> +    name: 'shopsys:post-deploy:run-tasks',
We already have `deploy:` commands, where I think this would fit better.

2026-05-12 10:15 UTC, grossmannmartin commented on packages/framework/src/Component/PostDeploy/Task/PostDeployTaskConfigLoader.php
> +class PostDeployTaskConfigLoader
I think we kinda re-invent the wheel here. 

What about putting post-deploy tasks under shopsys_framework semantic config?
I prototyped it in https://github.com/shopsys/shopsys/commit/83aa91f4443d9ed3a38262ed1a0bc0cd0835da31, and I like that it follows the already established Symfony's bundle configuration way and also we don't need to use custom loader at all.

2026-05-14 06:26 UTC, grossmannmartin approved these changes

2026-05-14 06:26 UTC, grossmannmartin commented on packages/framework/src/DependencyInjection/Configuration.php
> +                                        ->values((new PostDeployTaskRunEnum())->getAllCases())
Nitpick:
With `new` here, the enum may be a true enum as it's not extendable anyway. 

Or it should be `final` to make the intent clear.

I'm absolutely ok with a non-extendable task run list, as I don't think it will be necessary to modify this list.

2026-05-18 12:05 UTC, merged