[Administration] Create crud skeleton
shopsys/shopsys pull request #3629
Opened 2024-11-30 21:31 UTC by henzigo

#### Description, the reason for the PR
...

#### Fixes issues
... 

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2025-02-07 18:23 UTC, vitek-rostislav commented on docs/administration/crud-controller/getting-started/creating-a-new-crud-controller.md
> +Create a new Crud Controller by extending the `Shopsys\AdministrationBundle\Controller\AbstractCrudController` class and must have defined attribute `#[CrudController]` with the entity class name.
```suggestion
Create a new Crud Controller by extending the `Shopsys\AdministrationBundle\Controller\AbstractCrudController` class and on your class, define attribute `#[CrudController]` with the entity class name.
```

2025-02-07 18:23 UTC, vitek-rostislav commented on docs/administration/crud-controller/index.md
> +
redundant empty line

2025-02-07 18:23 UTC, vitek-rostislav commented on packages/administration/src/Controller/AbstractCrudController.php
> +    private ?CrudConfigData $config = null;
is  not there any case when I need to access the `$config` in my controller on a project?

2025-02-07 18:23 UTC, vitek-rostislav commented on packages/administration/src/Controller/AbstractCrudController.php
> +    private ?CrudConfigData $config = null;
I mean, I can still access it using `getConfig()` method but it seems a little bit cumbersome, or?

2025-02-07 18:23 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/crud-controller.md
> +- `$config->setMenuSection('customers', 'promo_codes')` will create Crud controller under `Customers -> Promo Codes` section
it is IMHO worth mentioning where to find the menu items' names - AFAIK in `SideMenuBuilder`, right? Too bad there is no command for listing all the items (or I was not able to find such a command)

2025-02-07 18:23 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/crud-controller.md
> +- `$config->setMenuSection('customers', 'promo_codes')` will create Crud controller under `Customers -> Promo Codes` section
... in the "end", those should be defined in `CrudConfig::setMenuTitle` calls, right?

2025-02-07 18:23 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/CrudConfig.php
> +    public function setMenuTitle(string $menuTitle): self
One thought - what if there are controllers that need to have multiple menu entries for multiple actions, is that possible?

2025-02-07 18:23 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/crud-controller.md
> +- `$config->setMenuSection('customers', 'promo_codes')` will create Crud controller under `Customers -> Promo Codes` section
... I see there is TODO below that could cover that :slightly_smiling_face:

2025-02-07 18:23 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/CrudConfigData.php
> +        $this->menuTitle = t('%entity_name% Overview', ['%entity_name%' => $entityName]);
I see a translation problem here - as `$entityName` is not translated, you will end up with titles like `Vytváření nového product` :thinking:

2025-02-14 18:12 UTC, vitek-rostislav requested changes

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Controller/AbstractCrudController.php
> +    protected function configureActions(ActionsConfig $actions): ActionsConfig
I think this deserves a mention in the docs :slightly_smiling_face:

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Resources/views/crud/new.html.twig
> +{% extends '@ShopsysFramework/Admin/Layout/layoutWithPanel.html.twig' %}
the templates for new end edit action are basically the same, we should create a common ancestor (`detail.html.twig`?) for them to avoid duplicates

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractActionBuilder.php
> +abstract class AbstractActionBuilder
If I am not mistaken, this class is called `AbstractAction` in the final version. Is there any point in having the abstract class and then one final implementation - `Action` class? Maybe we could merge them?

Or is it to enable adding more action types on a project? :eyes: Let's discuss this, please

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +- `OrmAdapter` - Adapter that works with Doctrine entities and it's used by Crud Controller
link to the crud controller docs would be nice here

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +You can also create your own adapter by implementing the `AdapterInterface`.
FQCN would be nice here

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +- `OrmAdapter` - Adapter that works with Doctrine entities and it's used by Crud Controller
+ FQCN please

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +- `ArrayAdapter` - Adapter that works with arrays
FQCN please

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +The `Datagrid` class is the main class that is used to configure the Datagrid. It provides methods to configure columns, filters, actions, and other features.
FQCN please

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +// Shopsys\AdministrationBundle\Component\Datagrid\Adapter\Orm\OrmAdapterFactory
it might be a little bit confusing whether you are referencing to `$adapter` or `$this->ormAdapterFactory`

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/datagrid/index.md
> +// Shopsys\AdministrationBundle\Component\Datagrid\DatagridFactory
it might be a little bit confusing whether you are referencing to `$datagrid` or `$this->datagridFactory`

2025-02-14 18:12 UTC, vitek-rostislav commented on docs/administration/index.md
> +- [Grid (Legacy)](./legacy-grid/index.md)
is it legacy indeed? I would rather say it is internal, or?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/DatagridDataSource.php
> +        $queryPaginator = new QueryPaginator($queryBuilder, DatagridHydrator::HYDRATION_MODE);
this (possibility to set the hint) should be taken into account now - https://github.com/shopsys/shopsys/pull/3641/commits/6ba3514642816d8933dcd7ff7938af9124c1668a

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/DatagridDataSource.php
> +            $results[$key] = call_user_func($this->manipulateRowCallback, $result, $results[$key], $results);
this should be taken into account - https://github.com/shopsys/shopsys/pull/3641/commits/3aa026a0a94fb8d0fabebc39b5fc7fa48272506b - working with all entries in the callback

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/DatagridDataSource.php
> +            $results[$key] = call_user_func($this->manipulateRowCallback, $result, $results[$key], $results);
ah, it already is, right? :slightly_smiling_face:

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/OrmAdapter.php
> +            throw new RuntimeException('Crud controller does not support entities with composite primary keys.');
is there a use case in our codebase now? I mean, what if we want to create a grid for such an entity?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +        $this->queryBuilder = clone $this->queryBuilder;
is not this confusing? when I call `clone` on the class, its query builder property is actually cloned instead?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +                    $this->queryBuilder->addSelect("{$alias}_tr.{$part}" . ' AS ' . $this->getAlias($path));
do not we want the same for `*Domain` associations?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +                    // We don't need to throw exeption here
...becauseee..? :smile:

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +                    // We don't need to throw exeption here
...it is handled a few lines below?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +            $alias = $joinAlias;
what is this good for in the last array iteration?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/DatagridFactory.php
> +        return $datagrid;
nitpick, the return can be inlined, right?

2025-02-14 18:12 UTC, vitek-rostislav commented on packages/administration/src/Component/Doctrine/DatagridHydrator.php
> +    protected function hydrateAllData()
missing return typehint

2025-02-15 18:14 UTC, vitek-rostislav requested changes
Awesome job there, love it! :heart_eyes:

2025-02-15 18:14 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/crud-controller.md
> +Fully disable the Crud Controller. Crud controller will not be accessible by the user.
Could you please add info on what this is useful for?

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/ActionsConfig.php
> +     * Add action to be displayed on specific Action
on specific Action? Should it not be something like "controller" or "page" instead of action?

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected $displayIf = null;
default value is not not necessary here

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected function __construct(protected string $name, string $label)
$name is not used

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/Action.php
> +final class Action extends AbstractAction
I am not sure whether it makes sense to create an abstract class here that has only one final implementation - do we expect project developers to create their own implementations?

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/ActionRoute/RouteActionRouteData.php
> +     * @param array|callable(?object $entity): array $routeParameters
duplicated param

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/CrudConfig.php
> +        Assert::allIsInstanceOf($actions, ActionType::class, 'The given action is not a valid action type');
could be extracted into a separate method to avoid DRY

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/CrudConfigData.php
> +        return $this->enabledActions->toArray();
getValues?

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Resources/views/crud/inline/actions.html.twig
> +            <a href="{{ action.url }}" class="btn btn--plus wrap-bar__btn {{ action.cssClass }}">
is `btn--plus` wanted every time? :thinking:

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Resources/views/crud/inline/actions.html.twig
> +            <a href="{{ action.url }}" class="btn btn--plus wrap-bar__btn {{ action.cssClass }}">
(should be also dependent on the specified icon, right?

2025-02-15 18:14 UTC, vitek-rostislav commented on docs/administration/datagrid/configuration.md
> +
too many empty lines here

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/DependencyInjection/Compiler/LoadControllersExtensionCompilerPass.php
> +            $attributeInstance = $attributes[0]->newInstance();
is not it dangerous to expect the first attribute will be `CrudControllerExtension`? There might be anything else in theory, or?

2025-02-15 18:14 UTC, vitek-rostislav commented on docs/administration/datagrid/fields.md
> +- `$datagrid->add('currency')` - This will fetch the `Currency` entity. In this case you need to define `template` or `transform` option to display the data in the field.
or you can set it as not visible, right? Then you can access it in the template or something like this, or?

2025-02-15 18:14 UTC, vitek-rostislav commented on docs/administration/datagrid/configuration.md
> +// Access to action configuration
docs/administration/crud-controller/reference/actions.md and docs/administration/datagrid/actions.md are now empty, so I am posting a TODO here :slightly_smiling_face:

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/DatagridActions.php
> +final class DatagridActions
maybe this should be named rather `DatagridRowActions` as in the future we might want to add actions for the grid as a whole (or is it already there? I am not sure)

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/DatagridManager.php
> +        return $this->crudRouteProvider;
I am not a big fan of having getters for services that can be autowired where needed :shrug:

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Controller/AbstractCrudController.php
>          return $this->redirect($this->generateUrl('admin_default_dashboard'));
implementing the delete action is not a part of this user story? :innocent:

2025-02-15 18:14 UTC, vitek-rostislav commented on packages/administration/src/Resources/views/crud/inline/actions.html.twig
> +                    <i class="btn__icon svg svg-{{ action.icon }}"></i>
needs to be updated now after https://github.com/shopsys/shopsys/pull/3765 is merged

2025-02-15 18:14 UTC, vitek-rostislav commented on project-base/app/src/Controller/Admin/TestController.php
> +                    'id' => 1,
this does not make sense here but I suppose it does not matter :slightly_smiling_face:

2025-02-18 11:13 UTC, henzigo commented on docs/administration/crud-controller/getting-started/creating-a-new-crud-controller.md
> +Create a new Crud Controller by extending the `Shopsys\AdministrationBundle\Controller\AbstractCrudController` class and must have defined attribute `#[CrudController]` with the entity class name.
fixed

2025-02-18 11:14 UTC, henzigo commented on docs/administration/crud-controller/index.md
> +
fixed

2025-02-18 11:16 UTC, henzigo commented on packages/administration/src/Controller/AbstractCrudController.php
> +    private ?CrudConfigData $config = null;
This is only used as a cache for that config. You can't access config property in your controller and we should also use getConfig() method instead of this private property inside that AbstractCrudController

2025-02-18 11:20 UTC, henzigo commented on docs/administration/crud-controller/reference/crud-controller.md
> +- `$config->setMenuSection('customers', 'promo_codes')` will create Crud controller under `Customers -> Promo Codes` section
We should refactor SideMenuBuilder in the future so that it correctly works with CRUD. For now, this is a different problem that I'm not capable of changing in this PR.

2025-02-18 11:21 UTC, henzigo commented on packages/administration/src/Component/Config/CrudConfig.php
> +    public function setMenuTitle(string $menuTitle): self
This is a very specific edge case that should be probably implemented differently. For now, every CrudController has one menu item.

2025-02-18 11:24 UTC, henzigo commented on packages/administration/src/Component/Config/CrudConfigData.php
> +        $this->menuTitle = t('%entity_name% Overview', ['%entity_name%' => $entityName]);
Yes exactly, it's designed to work without any additional configuration, but ofc you should configure some basic behavior like `setMenuTitle`

2025-02-18 11:25 UTC, henzigo commented on packages/administration/src/Controller/AbstractCrudController.php
> +    protected function configureActions(ActionsConfig $actions): ActionsConfig
This is probably the last section that is missing in the docs. I will finish it after this first round of CR.

2025-02-18 11:27 UTC, henzigo commented on packages/administration/src/Resources/views/crud/new.html.twig
> +{% extends '@ShopsysFramework/Admin/Layout/layoutWithPanel.html.twig' %}
I would like to leave it as it is for now.

2025-02-18 11:32 UTC, henzigo commented on docs/administration/datagrid/index.md
> +- `OrmAdapter` - Adapter that works with Doctrine entities and it's used by Crud Controller
FCQN updated. 

> link to the crud controller docs would be nice here
I don't think there should be a link to the crud controller as it's a standalone component. We can discuss it.

2025-02-18 11:33 UTC, henzigo commented on docs/administration/datagrid/index.md
> +You can also create your own adapter by implementing the `AdapterInterface`.
fixed

2025-02-18 11:34 UTC, henzigo commented on docs/administration/datagrid/index.md
> +The `Datagrid` class is the main class that is used to configure the Datagrid. It provides methods to configure columns, filters, actions, and other features.
fixed

2025-02-18 11:34 UTC, henzigo commented on docs/administration/datagrid/index.md
> +- `ArrayAdapter` - Adapter that works with arrays
fixed

2025-02-18 11:38 UTC, henzigo commented on docs/administration/index.md
> +- [Grid (Legacy)](./legacy-grid/index.md)
I want to completely refactor this internal grid and remove it in near future as part of the new administration. That's why It's called legacy.

2025-02-18 11:40 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/OrmAdapter.php
> +            throw new RuntimeException('Crud controller does not support entities with composite primary keys.');
We shouldn't as there are some issues with it when we want to use classMetadata with composite primary keys.

2025-02-18 11:42 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +                    $this->queryBuilder->addSelect("{$alias}_tr.{$part}" . ' AS ' . $this->getAlias($path));
Maybe when we will add support for DomainTabs.

2025-02-18 11:42 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +                    // We don't need to throw exeption here
I completely refactored ProxyQuery :D

2025-02-18 11:44 UTC, henzigo commented on packages/administration/src/Component/Datagrid/DatagridFactory.php
> +        return $datagrid;
fixed

2025-02-18 11:44 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +            $alias = $joinAlias;
completely refactored ProxyQuery :D

2025-02-18 11:45 UTC, henzigo commented on packages/administration/src/Component/Doctrine/DatagridHydrator.php
> +    protected function hydrateAllData()
outdated

2025-02-18 11:48 UTC, henzigo commented on project-base/app/src/Controller/Admin/TestController.php
> +                    'id' => 1,
It does make sense as I wanted to check if passed parameters are working as expected :D

2025-02-18 16:41 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +enum PartType
This is quite unusual for me, I would rather see this in a separate file

2025-02-18 16:43 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/CrudConfigData.php
> +        $this->menuTitle = t('%entity_name% Overview', ['%entity_name%' => $entityName]);
ok

2025-02-19 12:05 UTC, henzigo commented on packages/administration/src/Resources/views/crud/inline/actions.html.twig
> +                    <i class="btn__icon svg svg-{{ action.icon }}"></i>
updated

2025-02-19 12:29 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/DatagridDataSource.php
> +        $queryPaginator = new QueryPaginator($queryBuilder, DatagridHydrator::HYDRATION_MODE);
I updated my code for including meta columns little bit. Look 8ac5bbc4

2025-02-19 12:34 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/DatagridDataSource.php
> +            $results[$key] = call_user_func($this->manipulateRowCallback, $result, $results[$key], $results);
yes already used :)

2025-02-19 12:37 UTC, henzigo commented on docs/administration/crud-controller/reference/crud-controller.md
> +Fully disable the Crud Controller. Crud controller will not be accessible by the user.
I can add that as info that you can disable it when you for an example don't want to use this functionality in your project, but we probably don't need to write all possibilities for which this function is designed.

2025-02-19 12:40 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/Action.php
> +final class Action extends AbstractAction
It creates borders for projects to edit/update/implement some custom behavior. For now, it seems useless, but with a new admin, we will probably want to create DropdownAction or something like that.

2025-02-19 12:41 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/ActionRoute/RouteActionRouteData.php
> +     * @param array|callable(?object $entity): array $routeParameters
fixed

2025-02-19 12:49 UTC, henzigo commented on packages/administration/src/Component/Config/CrudConfig.php
> +        Assert::allIsInstanceOf($actions, ActionType::class, 'The given action is not a valid action type');
I thought about it and in final I decided to not avoid this DRY as it will decrease readability. As the second argument is that this code will be probably modified in the future in favor of custom actions

2025-02-19 12:52 UTC, henzigo commented on packages/administration/src/Component/Config/CrudConfigData.php
> +        return $this->enabledActions->toArray();
fixed

2025-02-19 12:54 UTC, henzigo commented on packages/administration/src/Resources/views/crud/inline/actions.html.twig
> +            <a href="{{ action.url }}" class="btn btn--plus wrap-bar__btn {{ action.cssClass }}">
`btn--plus` class was already removed. Anyway, I want to make some changes to rendering Actions so let's keep this conversation opened for now

2025-02-19 12:55 UTC, henzigo commented on docs/administration/datagrid/configuration.md
> +
fixed

2025-02-19 12:58 UTC, henzigo commented on packages/administration/src/DependencyInjection/Compiler/LoadControllersExtensionCompilerPass.php
> +            $attributeInstance = $attributes[0]->newInstance();
`$attributes` contains only `CrudControllerExtension` classes as it's filtered before those lines with:

```php
$attributes = $reflectionClass->getAttributes(CrudControllerExtension::class);
```

2025-02-19 13:10 UTC, henzigo commented on packages/administration/src/Component/Datagrid/DatagridManager.php
> +        return $this->crudRouteProvider;
I will refactor this

2025-02-19 13:10 UTC, henzigo commented on packages/administration/src/Controller/AbstractCrudController.php
>          return $this->redirect($this->generateUrl('admin_default_dashboard'));
It is, but It's willingly ignored

2025-02-19 13:14 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +enum PartType
fixed

2025-02-19 13:19 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `$datagrid->add('currency')` - This will fetch the `Currency` entity. In this case you need to define `template` or `transform` option to display the data in the field.
updated

2025-02-19 13:35 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected $displayIf = null;
instead of callable you can use Closure btw

2025-02-21 00:20 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +        $this->queryBuilder = clone $this->queryBuilder;
As we talked, QueryBuilder is mutable so without it any changes in cloned class would also affect original QueryBuilder

2025-02-21 03:12 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected $displayIf = null;
I changed callable to Closure :) ... but now I have problem with standards :D

2025-02-21 03:12 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected function __construct(protected string $name, string $label)
It is now :)

2025-02-21 06:24 UTC, henzigo commented on packages/administration/src/Controller/AbstractCrudController.php
> +    protected function configureActions(ActionsConfig $actions): ActionsConfig
Documented 🎉

2025-02-21 06:24 UTC, henzigo commented on docs/administration/datagrid/index.md
> +- `OrmAdapter` - Adapter that works with Doctrine entities and it's used by Crud Controller
Link added

2025-02-21 06:24 UTC, henzigo commented on docs/administration/datagrid/index.md
> +// Shopsys\AdministrationBundle\Component\Datagrid\Adapter\Orm\OrmAdapterFactory
Is it better now? :)

2025-02-21 06:24 UTC, henzigo commented on docs/administration/datagrid/index.md
> +// Shopsys\AdministrationBundle\Component\Datagrid\DatagridFactory
Also refactored

2025-02-21 06:29 UTC, henzigo commented on packages/administration/src/Component/Config/Action/ActionsConfig.php
> +     * Add action to be displayed on specific Action
It is better now?

2025-02-21 06:30 UTC, henzigo commented on docs/administration/datagrid/index.md
> +// Shopsys\AdministrationBundle\Component\Datagrid\DatagridFactory
Also refactored

2025-02-21 08:43 UTC, henzigo commented on docs/administration/index.md
> +- [Grid (Legacy)](./legacy-grid/index.md)
Edited to Internal :)

2025-02-21 08:45 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Adapter/Orm/ProxyQuery.php
> +        $this->queryBuilder = clone $this->queryBuilder;
For others. Without this line of code QueryBuilder would do this:

```php
$original = new ProxyQuery(...);
$copy = clone $original;

// Modify the cloned query
$copy->addSelect('someField');

// If we didn't clone QueryBuilder, this would also modify the original!
print_r($original->getQueryBuilder()->getDQLPart('select'));
```

2025-02-21 17:28 UTC, vitek-rostislav requested changes

2025-02-21 17:28 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    abstract protected function getTemplateParameters(?object $entity): array;
is $entity a proper name?

2025-02-21 17:28 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    abstract protected function getTemplateParameters(?object $entity): array;
or otherwise, should it be named `getTemplateParameters` when you need to pass the entity?

2025-02-21 17:28 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/Action.php
> +    private bool $openInNewTab = false;
why is it moved from the abstract class here?

2025-02-21 17:28 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/actions.md
> +- **Application Name**   : `create`
should not this be "Action name"?

2025-02-21 17:28 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/actions.md
> +- **Application Name**   : `backToList`
should not this be "Action name"?

2025-02-21 17:28 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/actions.md
> +// ...
in which class is this supposed to be?

2025-02-21 17:28 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/actions.md
> +// ...
in which class is this supposed to be?

2025-02-21 17:28 UTC, vitek-rostislav commented on docs/administration/index.md
> +- [Grid (Internal)](./legacy-grid/index.md)
the folder deserves renaming too :innocent:

2025-02-21 17:28 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +            throw new InvalidArgumentException(sprintf('Attribute "%s" is forbidden to set.', $name));
maybe it is worth mentioning something like "set this attribute using whateverFunction()"

2025-02-21 17:30 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected function __construct(protected string $name, string $label)
I do not think so :smile:

2025-02-21 18:04 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected function __construct(protected string $name, string $label)
It's used [here](https://github.com/shopsys/shopsys/blob/cafff15df3311abd78fc98282bcaa6888074fcde/packages/administration/src/Component/Config/Action/ActionsConfig.php#L60-L62) :)

2025-02-21 18:06 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    abstract protected function getTemplateParameters(?object $entity): array;
Do you have any suggestions, on how to avoid passing that parameter? In the other hand, it still says what it does. Like you will get TemplateParameters

2025-02-21 18:09 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/Action.php
> +    private bool $openInNewTab = false;
Two reasons:

1. AbstractAction knows nothing about links so this setting is just weird. You can set it as open in a new tab, but you can't configure a link
2. I was wondering what would a DropdownAction look like, which would not have any link itself, but only a list of other Actions. And then it doesn't make sense either

2025-02-21 18:22 UTC, henzigo commented on docs/administration/crud-controller/reference/actions.md
> +// ...
On top of this file is mentioned this:

Actions can be configured in `configureActions()` method of the Crud Controller.

```php
namespace App\Controller\Admin;

use App\Model\Article\Article;
use Shopsys\AdministrationBundle\Component\Attributes\CrudController;
use Shopsys\AdministrationBundle\Component\Config\Action\ActionsConfig;
use Shopsys\AdministrationBundle\Controller\AbstractCrudController;

#[CrudController(Article::class)]
class ArticleController extends AbstractCrudController
{
    // ...

    protected function configureActions(ActionsConfig $actions): ActionsConfig
    {
        
    }
}
```

So I think it's not necessary to specify everything in that sample :D

2025-02-21 18:22 UTC, henzigo commented on docs/administration/crud-controller/reference/actions.md
> +// ...
Same as above

2025-02-21 18:25 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +            throw new InvalidArgumentException(sprintf('Attribute "%s" is forbidden to set.', $name));
I can update the message to something like ... is forbidden to set. Look if any method sets this attribute... 

But `$this->forbiddenAttributes` can be updated by any child class so your suggestion could introduce additional overhead over configuring these values.

2025-02-23 03:07 UTC, henzigo commented on docs/administration/crud-controller/reference/actions.md
> +- **Application Name**   : `create`
yes, fixed

2025-02-23 03:07 UTC, henzigo commented on docs/administration/crud-controller/reference/actions.md
> +- **Application Name**   : `backToList`
yes, fixed

2025-02-23 05:00 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +            throw new InvalidArgumentException(sprintf('Attribute "%s" is forbidden to set.', $name));
Eventually, I got the idea. `$this->forbiddenAttributes` now accepts key as name of attribute and value as an additional error message.

2025-02-23 05:01 UTC, henzigo commented on docs/administration/index.md
> +- [Grid (Internal)](./legacy-grid/index.md)
Done

2025-02-24 08:56 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected function __construct(protected string $name, string $label)
ah, ok, I was confused by the constructor format - `$label` is not promoted but is initialized in the constructor body, while `$name` is a constructor-promoted property, ok, now I get it. It is a bit confusing, could it be unified, please?

2025-02-24 09:01 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    abstract protected function getTemplateParameters(?object $entity): array;
yeah, my bad, I probably misunderstood the method in the first place. However, now, when I see the usage, what about this?

![image](https://github.com/user-attachments/assets/c9075e22-13ae-4e0b-91c9-1431e6f42279)

2025-02-24 09:02 UTC, vitek-rostislav commented on packages/administration/src/Component/Config/Action/Builder/Action.php
> +    private bool $openInNewTab = false;
ok, thanks for the clarification

2025-02-24 09:03 UTC, vitek-rostislav commented on docs/administration/crud-controller/reference/actions.md
> +// ...
you are right :+1:

2025-02-25 05:40 UTC, henzigo commented on packages/administration/src/Component/Config/Action/Builder/AbstractAction.php
> +    protected function __construct(protected string $name, string $label)
fixed

2025-02-25 05:41 UTC, henzigo commented on docs/administration/datagrid/configuration.md
> +// Access to action configuration
Both section now contains some text :)

2025-02-25 05:42 UTC, henzigo commented on packages/administration/src/Component/Datagrid/DatagridActions.php
> +final class DatagridActions
I refactored Datagrid actions to DatagridRowActions and they are now defined by same AbstractAction class as CrudActions :)

2025-02-25 05:49 UTC, henzigo commented on packages/administration/src/Component/Datagrid/DatagridManager.php
> +        return $this->crudRouteProvider;
Ok after refactoring DatagridRowActions Datagrid needs only `Shopsys\FrameworkBundle\Component\Grid\GridFactory` that is now passed by the constructor :) So `DatagridManager` is no longer available

2025-02-25 15:24 UTC, vitek-rostislav requested changes

2025-02-25 15:24 UTC, vitek-rostislav commented on docs/administration/datagrid/row-actions.md
> +// Let's look about the methods that will help you with redirecting the user after clicking the
this sentence is somehow broken, "Let's look about" does not sound correct, and there is no ending :sweat_smile:

2025-02-25 15:24 UTC, vitek-rostislav commented on docs/administration/datagrid/row-actions.md
> +    // Use this in case you need to create an link to an external page
```suggestion
    // Use this in case you need to create a link to an external page
```

nitpick :slightly_smiling_face:

2025-02-25 15:24 UTC, vitek-rostislav commented on packages/administration/src/Component/Action/Action.php
> +    use ActionRouteTrait;
I would rather see all the trait logic directly in `AbstractAction`  :shrug: It seems like both the implementations need all the functionality defined in the trait, which is IMHO just complicating things...Or am I missing something?

2025-02-25 15:24 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Datagrid.php
> +    private DatagridRowActions $rowActions;
it feels like `DatagridRowActions` class is adding an unnecessary layer of complexity. IMHO, `Datagrid` should offer methods for manipulating the row actions (presented by his private `ArrayCollection` of `RowAction` instances (or probably `GridRowActionInterface` instances, right?)

2025-02-25 15:24 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Datagrid.php
> +    private DatagridRowActions $rowActions;
e.g. this usage is quite cumbersome:
```
foreach ($this->rowActions()->getRowActions() as $action) {
            $grid->addRowAction($action);
        }
```

2025-02-25 15:24 UTC, vitek-rostislav commented on packages/administration/src/Component/Datagrid/Datagrid.php
> +    private DatagridRowActions $rowActions;
btw now it is not consistent with the `$fields` property

2025-02-25 15:24 UTC, vitek-rostislav commented on packages/framework/src/Component/Grid/GridView.php
> +        throw new InvalidArgumentException(
this is quite weird - you declare `GridRowColumnInterface` can be passed to `renderActionCell`, however, only `ActionColumn`|`GridRowActionInterface` are actually supported. Could we discuss it, please?

2025-02-25 22:49 UTC, henzigo commented on docs/administration/datagrid/row-actions.md
> +// Let's look about the methods that will help you with redirecting the user after clicking the
I deleted that message :)

2025-02-25 22:50 UTC, henzigo commented on docs/administration/datagrid/row-actions.md
> +    // Use this in case you need to create an link to an external page
fixed

2025-02-25 22:54 UTC, henzigo commented on packages/administration/src/Component/Datagrid/Datagrid.php
> +    private DatagridRowActions $rowActions;
As we agreed, I changed `rowActions()` to `actions()` method

2025-02-25 23:05 UTC, henzigo commented on packages/administration/src/Component/Action/Action.php
> +    use ActionRouteTrait;
with a heavy heart adjusted

2025-02-25 23:13 UTC, henzigo commented on packages/framework/src/Component/Grid/GridView.php
> +        throw new InvalidArgumentException(
refactored :)

2025-02-26 08:55 UTC, vitek-rostislav requested changes
So, hopefully last return of this task :smile: 
Please,
- rebase the branch,
- squash the fixups, 
- resolve the failing builds, 
- and add tests at least for the `ProxyQuery` class

2025-03-04 16:07 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +## Configure List Page
the documentation is somehow weirdly structured. Link `Getting started` point to `Configure list page`

2025-03-05 09:59 UTC, grossmannmartin requested changes

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/creating-a-new-crud-controller.md
> +        ->setTitle(PageType::LIST, t('My new Crud Controller')) // Set the title of the list page
it's actually `ActionType` in the latest implementation... and it seems weird to use actionType here, but I can live with that

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/creating-a-new-crud-controller.md
> +        ->setTitle(PageType::LIST, t('My new Crud Controller')) // Set the title of the list page
Is the main idea here that we would be able to call it multiple times to set each page? 
like
```
->setTitle(ActionType::LIST, t('List products'))
->setTitle(ActionType::EDIT, t(Edit product'))
```

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +        // This column is defined automatically and is used to identify the record. You can override it if you want to display a different identifier or you can hide it with second argument set to fa
the default value is already false, which makes the behavior quite strange now. 

datagrid without call `addIdentifier` do not display ID column
datagrid with `->addIdentifier('id')` **do not display ID column**
datagrid with `->addIdentifier('id', true)` *display ID column*

what about split the responsibility to `changeIdentifier(string $idColumnName)` and if I want to display column ID in grid I will use default `addColumn(...)`?

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +2. Modify Datagrid query
this should be heading probably. the same applies to `3. Configure list actions`

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +        ->andWhere('o.deleted = :deleted')
is it always `o`? Why `o`?

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +
I see the `setPagination(bool $pagination)` method. Personally, I would rather have `enablePagination()` and `disablePagination()`

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +    );
linkToUrl accepts only closure. Shouldn't it also accept plain string? It seems obnoxious to be forced to wrap return string in anonymous function

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/datagrid/fields.md
> +- `transform` - A callback function that is used to transform the data before it is displayed in the field. The callback function receives the value of the field as the first parameter, row as the se
If I use transform on a virtual field I get fatal error

code:
```
 protected function configureDatagrid(Datagrid $datagrid): Datagrid
    {
        $datagrid->add('name');

        $datagrid->add('oreo', [
            'label' => 'Oreo',
            'virtual' => true,
            'transform' => function () {
                return 'asd';
            },
        ]);

        $datagrid->setDefaultOrder('name', OrderingEnum::DESC);
        $datagrid->setPagination(false);

        return $datagrid;
    }
```

![Snímek obrazovky 2025-03-05 v 10 15 30](https://github.com/user-attachments/assets/d7785732-3b3b-44d3-b83e-d772bd502e80)

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/datagrid/fields.md
> +- `template` - The template that is used to render the field. The template is a path to a Twig template file.
it would be nice to document what variables are available in the template

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/datagrid/fields.md
> +- `$datagrid->add('status.name')` - This will join the `status` relation and look for the `name` property of the `Status` entity. In this case `Status` is a translatable entity and the `name` propert
It would be nice to automatically provide a fallback text if the translation is not entered. 
Something similar to the current product grid behavior

![Snímek obrazovky 2025-03-05 v 10 26 02](https://github.com/user-attachments/assets/6c125f64-1c70-4b3f-bc4d-b35cfc6ba25b)

now the empty field is rendered

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/datagrid/fields.md
> +- `$datagrid->add('domainId')` - This will fetch the `domainId` property of the entity.
thinking... wouldn't be useful to provide a "syntax sugar" to quickly render text as the edit link? 
Now I have to write the custom template. 

something like

```
 $datagrid->add('name', [
            'with_detail_link' => true,
```

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/datagrid/fields.md
> +- `help` - The help text that is displayed next to label in column header.
help is not rendered if the field is not sortable or is virtual

2025-03-05 09:59 UTC, grossmannmartin commented on docs/administration/datagrid/fields.md
> +- `transform` - A callback function that is used to transform the data before it is displayed in the field. The callback function receives the value of the field as the first parameter, row as the se
transform behaves inconsistently for objects and scalar attributes

this code

```php
$datagrid->add('sellingFrom', [
    'label' => 'Selling from',
    'transform' => function (\DateTimeInterface $value) {
        return $value->format('Y-m-d');
    },
]);

$datagrid->add('sellingYear', [
    'label' => 'Selling Year',
    'virtual' => true,
    'template' => 'Admin/Crud/my.html.twig', // {{ row.sellingFrom|date('Y') }}
]);
```

works as expected (sellingFrom is a DateTime object) - outputs `2000-02-17 | 2000`

while this don't - outputs `name - transformed | NAME - TRANSFORMED`

```php
$datagrid->add('name', [
    'transform' => function (string $value) {
        return $value . ' - transformed';
    },
]);

$datagrid->add('oreo', [
    'label' => 'Oreo',
    'virtual' => true,
    'template' => 'Admin/Crud/my.html.twig', // {{ row.name|upper }}
]);
```

2025-03-24 12:25 UTC, henzigo commented on docs/administration/crud-controller/getting-started/creating-a-new-crud-controller.md
> +        ->setTitle(PageType::LIST, t('My new Crud Controller')) // Set the title of the list page
yes exactly

2025-03-24 12:25 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +        ->andWhere('o.deleted = :deleted')
`o` like `object`

2025-03-24 12:28 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +    );
I can add this option, but I wanted to have it as simple as possible :) 

```php
...
->linkToUrl(fn() => 'https://google.com')
```

It's not that bad :D

2025-03-24 12:29 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `transform` - A callback function that is used to transform the data before it is displayed in the field. The callback function receives the value of the field as the first parameter, row as the se
Maybe we can discuss how this should work. Like You want to transform data that does not exists :D

2025-03-24 12:30 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `transform` - A callback function that is used to transform the data before it is displayed in the field. The callback function receives the value of the field as the first parameter, row as the se
But I agree that there should be some check that will tell you something like `You cannot transform virtual field`

2025-03-24 12:31 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `template` - The template that is used to render the field. The template is a path to a Twig template file.
Yes, but I don't know which ones are in the template :D

2025-03-24 12:31 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `$datagrid->add('status.name')` - This will join the `status` relation and look for the `name` property of the `Status` entity. In this case `Status` is a translatable entity and the `name` propert
You can do that with transform or custom template. We can add this functionality later

2025-03-24 12:31 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `$datagrid->add('domainId')` - This will fetch the `domainId` property of the entity.
We can add this functionality later

2025-03-24 12:32 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `help` - The help text that is displayed next to label in column header.
I will look at it

2025-03-30 22:22 UTC, henzigo commented on docs/administration/crud-controller/getting-started/creating-a-new-crud-controller.md
> +        ->setTitle(PageType::LIST, t('My new Crud Controller')) // Set the title of the list page
fixed

2025-03-30 22:22 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +2. Modify Datagrid query
fixed

2025-03-30 22:25 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +
I'd like to have it as it is now :)

2025-03-30 22:30 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +    );
but you can now pass simply string

2025-03-30 22:51 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `transform` - A callback function that is used to transform the data before it is displayed in the field. The callback function receives the value of the field as the first parameter, row as the se
Ok, I made it fully functional. In case you want to transforma  virtual field, in closure you will get null instead, but you can return what you want to show based on other fields, etc.

2025-03-30 23:10 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `help` - The help text that is displayed next to label in column header.
Fixed. I misplaced it in template. Now it's working, but that code is placed twice due to weird CSS computing of arrows :D I can't wait for our new administration :D

2025-03-30 23:22 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `transform` - A callback function that is used to transform the data before it is displayed in the field. The callback function receives the value of the field as the first parameter, row as the se
It works the same in both cases. The problem is that with our internal Grid, there is only one place where I can transform fields right after fetching data from DB. Because of this `row` already contains a transformed field. 

In your first case `row.sellingFrom` contains `2000-02-17` but `|date()` twig filter accepts string so it feels like you have the original value here, but it's not true. 

I updated docs a little bit so it will be clearer how it works now

2025-03-30 23:44 UTC, henzigo commented on docs/administration/datagrid/fields.md
> +- `template` - The template that is used to render the field. The template is a path to a Twig template file.
👍 Updated docs for internal grid with that information and linked those pages :)

2025-03-31 00:41 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +        // This column is defined automatically and is used to identify the record. You can override it if you want to display a different identifier or you can hide it with second argument set to fa
You are right! Only one change in name of method `setIdentifier()`

2025-03-31 00:48 UTC, henzigo commented on docs/administration/crud-controller/getting-started/configure-list-page.md
> +## Configure List Page
fixed

2025-04-03 15:50 UTC, grossmannmartin approved these changes
Awesome work ♥️. Really looking forward to use this

2025-04-04 16:12 UTC, vitek-rostislav approved these changes
Hi, awesome, just a few last notes + please fix the standards (or remove the example, rebase it, and you can move the task to business validation :partying_face:

2025-04-04 16:12 UTC, vitek-rostislav commented on packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
> +            {% endif %}
this could be extracted into a macro to avoid the duplication :innocent:

2025-04-04 16:12 UTC, vitek-rostislav commented on docs/administration/internal-grid/grid-rendering-customization.md
> +- `column` - the column object itself
it would be nice to add "(i.e. instance of XX class)"

2025-04-04 16:12 UTC, vitek-rostislav commented on docs/administration/internal-grid/grid-rendering-customization.md
> +Ccreate a new template extending the original one, override appropriate blocks, and then set the template as a theme of your grid using `Grid::setTheme` method.
```suggestion
Create a new template extending the original one, override appropriate blocks, and then set the template as a theme of your grid using `Grid::setTheme` method.
```

2025-04-04 22:40 UTC, henzigo commented on packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
> +            {% endif %}
Yes, but they are not the same and after implementing the new administration it will be changed. I will not change it now :)

2025-04-04 22:42 UTC, henzigo commented on docs/administration/internal-grid/grid-rendering-customization.md
> +- `column` - the column object itself
fixed

2025-04-04 22:42 UTC, henzigo commented on docs/administration/internal-grid/grid-rendering-customization.md
> +Ccreate a new template extending the original one, override appropriate blocks, and then set the template as a theme of your grid using `Grid::setTheme` method.
fixed

2025-04-09 12:35 UTC, merged