Add parallel and regenerate to Gitlab pipelines
shopsys/shopsys pull request #3630
Opened 2024-12-02 07:07 UTC by AmpMVn

#### Description, the reason for the PR
It was not possible to manually run a cypress test regeneration in Gitlab UI. I added a regeneration pipeline that can be run manually in Gitlab UI plus added the ability to set up parallel runs.

#### Check the appropriate checkboxes below, please

- [ ] [BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/) 
- [ ] New feature 
- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-12-04 13:43 UTC, vitek-rostislav requested changes
please, add the upgrade notes with link project base diff for this PR and also for https://github.com/shopsys/shopsys/pull/3514

2024-12-04 13:43 UTC, vitek-rostislav commented on project-base/.gitlab-ci.yml
> +                git push https://shopsys_bot:$API_TOKEN@gitlab.shopsys.cz/ss6-projects/project-base.git "$CI_COMMIT_REF_NAME" --force -v || (echo "Failed to push changes" && git log -n 5 && exit 1)
```suggestion
                git push https://shopsys_bot:$API_TOKEN@gitlab.shopsys.cz/ss6-projects/$CI_PROJECT_NAME.git "$CI_COMMIT_REF_NAME" --force -v || (echo "Failed to push changes" && git log -n 5 && exit 1)
```

2024-12-05 06:49 UTC, AmpMVn commented on project-base/.gitlab-ci.yml
> +                git commit -m "Regenerated Cypress screenshots for ${GROUP} group"
```suggestion
                if [ -z "$GROUP" ]; then
                    git commit -m "Regenerated Cypress screenshots"
                else
                    git commit -m "Regenerated Cypress screenshots for ${GROUP} group"
                fi
```

2024-12-05 06:52 UTC, AmpMVn commented on project-base/.gitlab-ci.yml
> +                git push https://shopsys_bot:$API_TOKEN@gitlab.shopsys.cz/ss6-projects/project-base.git "$CI_COMMIT_REF_NAME" --force -v || (echo "Failed to push changes" && git log -n 5 && exit 1)
```suggestion
                git push https://shopsys_bot:$API_TOKEN@gitlab.shopsys.cz/ss6-projects/${CI_PROJECT_NAME}.git "$CI_COMMIT_REF_NAME" --force -v || (echo "Failed to push changes" && git log -n 5 && exit 1)
```

2024-12-05 09:03 UTC, vitek-rostislav approved these changes

2024-12-06 12:33 UTC, pk16011990 approved these changes

2024-12-10 09:51 UTC, merged