[framework] Admin dropdown UI & UX improvement
shopsys/shopsys pull request #3636
Opened 2024-12-04 15:20 UTC by JanMolcik

#### Description, the reason for the PR
To improve UI and UX, the "Domains filter" and "Go to Frontend" dropdown options list was adjusted.

#### Fixes issues
... 

#### License Agreement for contributions

- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-12-05 07:03 UTC, chlebektomas requested changes
Please, check the standarts as well.

2024-12-05 07:03 UTC, chlebektomas commented on project-base/storefront/next-env.d.ts
> -// see https://nextjs.org/docs/basic-features/typescript for more information.
I think we do not need this :)

2024-12-05 07:03 UTC, chlebektomas commented on packages/framework/src/Resources/translations/messages.cs.po
> -msgid "Select all"
Do we want to delete these translations?

2024-12-05 07:03 UTC, chlebektomas commented on packages/framework/assets/styles/admin/components/list/domain.less
> +            padding: 10px 1em;
I am just curious if we are mixing these units.

2024-12-09 11:34 UTC, vitek-rostislav requested changes
Hi, for testing purposes, could you also add a [DROP] commit with multiple domains set?

2024-12-09 11:34 UTC, vitek-rostislav commented on packages/framework/src/Resources/translations/messages.en.po
> +msgstr "All"
there should not be any translation for the `en` locale

2024-12-09 11:34 UTC, vitek-rostislav commented on packages/framework/src/Resources/views/Admin/Form/adminDomainsForm.html.twig
> +            <span class="checkbox__label">{{ 'All - full'|trans }}</span>
I think you need another translation key here - just "All" probably?

2024-12-16 09:16 UTC, merged