[project-base] added css variables
shopsys/shopsys pull request #3648
Opened 2024-12-11 07:02 UTC by chlebektomas

#### Description, the reason for the PR
New design system with CSS variables.

#### Fixes issues
... 

#### License Agreement for contributions

- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2025-05-01 09:49 UTC, JanMolcik requested changes
Good job, I have got just one idea/proposal.

2025-05-01 09:49 UTC, JanMolcik commented on project-base/storefront/components/Basic/Flag/Flag.tsx
If we are using just `isLight()` from `tinycolor` package, do we actually need it? There is already simillar functionality to get contrast text based on bg color (`getYIQContrastTextColor()` function in `bannersUtils`). Could we somehow re-use it instead?

2025-05-05 09:57 UTC, chlebektomas commented on project-base/storefront/components/Basic/Flag/Flag.tsx
fixed

2025-05-05 10:00 UTC, JanMolcik requested changes

2025-05-05 10:00 UTC, JanMolcik commented on project-base/storefront/components/Basic/Flag/Flag.tsx
> +import { getYIQContrastTextColor } from 'components/Blocks/Banners/bannersUtils';
Since it is now used by other components than just banner, I would move it somewhere to general utils.

2025-05-05 10:20 UTC, JanMolcik approved these changes

2025-05-20 11:27 UTC, merged