added deduplication for product messages in the queue, including scopes
shopsys/shopsys pull request #3669
Opened 2024-12-16 12:55 UTC by janjavorek

#### Description, the reason for the PR
... 

#### Fixes issues
... 

Fixing the problem when multiple consumers are processing product recalculation messages with the same product ID. Messages in the queue are filtered out before another message with the same product ID is dispatched.

#### License Agreement for contributions

- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-12-17 05:28 UTC, henzigo reviewed
I know this PR is not ready for CR yet, but I was curious and there's result 😃

2024-12-17 05:28 UTC, henzigo commented on project-base/app/config/packages/snc_redis.yaml
> +        product_recalculation_queue:
Why did you decide to use Redis instead of some RabbitMQ plugins for deduplications? Are there any benefits/downsides of this?

2024-12-17 05:28 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +class DispatchProductIdsBatchMessageHandler implements MessageHandlerInterface
What is the purpose of this class? I don't understand the benefit of this. It only iterates over products and then dispatches all products again

2024-12-17 05:28 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $idsToRecalculate = $this->productRecalculationRepository->getIdsToRecalculate($productIdsBatch);
You shouldn't call repository directly and you will slow down dispatching messages with this call. Moreover, you are calling this method already in Handler so this could probably create some problems with recalculating same product variants.

2024-12-17 05:28 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +                $scopes = array_unique(array_merge($scopes, explode(',', $scopesString)));
What about using JSON instead of exploding and imploding strings?

2024-12-17 05:28 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +class ProductRecalculationCacheFacade
What about using Hashes instead of a simple get/set? It will be grouped under one key with all options you need with benefit of executing batch operations. I'm talking about `HMGET`, `HMSET` and `HMDEL`.

Look: https://redis.io/docs/latest/commands/hmset/ and https://redis.io/docs/latest/commands/hmget/

2024-12-17 05:28 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +    public function contains(
This method is useless. You can simply call get(); if it returns false, then the key does not exist. Moreover, you will save one command for each product

2024-12-17 05:28 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +    public function save(
This should be probably named better. Something like `saveOrUpdateScopes` because I was confused that you are replacing scopes instead of updating them.

2024-12-20 17:19 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +class DispatchProductIdsBatchMessageHandler implements MessageHandlerInterface
The main purpose is optimization, if you're changing for example unit name or parameter then all affected products are dispatched at that time and if you have 50k and more affected products then you'll be waiting for a looong time to save the change.

2024-12-20 17:23 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $idsToRecalculate = $this->productRecalculationRepository->getIdsToRecalculate($productIdsBatch);
Yes, we already discussed this issue, and the main difference is that from now on, you're dispatching only main variants and regular products. Variants are not dispatched at all and are retrieved during the recalculation process afterward.

2024-12-20 17:29 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +    public function contains(
Ok, I changed only the content and switched `exists` with `get`. I think is more readable if name of the method is `contains`

2024-12-20 17:29 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +    public function save(
Ok, changed

2024-12-20 17:39 UTC, janjavorek commented on project-base/app/config/packages/snc_redis.yaml
> +        product_recalculation_queue:
Redis gives you more control over messages at the application level, and I believe it is more suitable for our purposes. It allows you to handle ELS scopes and deduplicate messages at that level.

2025-01-05 10:12 UTC, grossmannmartin requested changes

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/DispatchAffectedProductsSubscriber.php
> +            [ProductExportScopeConfig::SCOPE_CATEGORIES, ProductExportScopeConfig::SCOPE_FLAGS],
this seems more like a forgotten debug statement, or?

2025-01-05 10:12 UTC, grossmannmartin commented on project-base/app/config/packages/messenger.yaml
> +            Shopsys\FrameworkBundle\Model\Product\Recalculation\DispatchProductIdsBatchMessage: product_recalculation_priority_regular
Shouldn't be the dispatch itself placed with a high priority? Then IDs will be deduplicated immediately

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +class ProductRecalculationCacheFacade
interesting idea, @janjavorek did you consider it?

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        protected readonly ProductRecalculationRepository $productRecalculationRepository,
I would rather use the repository only in the related facade (in some scenarios in different facades), but I don't think it should be used here

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Component/Redis/RedisClientFacade.php
> +    public function save(string $key, mixed $data, mixed $options = null): void
this change seems unnecessary, or?

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Component/Redis/RedisClientFacade.php
> +    public function get(string $key): mixed
this method seems unused

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +    public function clear(): void
This method is unused, and the implementation is confusing. ProductRecalculationCacheFacade accepts a scoped redis client (`@snc_redis.product_recalculation_queue`), but the clean method will clear all redis clients, which is unexpected.

I suggest to remove the clear method and the dependency on the RedisFacade

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            if ($productRecalculationPriorityEnum === ProductRecalculationPriorityEnum::HIGH) {
does this mean that the high priority will not be deduplicated?

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $exists = $this->productRecalculationCacheFacade->contains($productId);
this may be called for multiple ids at once in redis (so we don't have to query redis 2000 times). 

also `contains` is called even in the saveOrUpdateScopes, which worsens performance

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $replaceVariantProductIds = $this->productRecalculationRepository->replaceVariantIdsWithMainVariantIds($productIdsBatch);
During dispatchAllProductsMessageHandler processing, this method is called, even though the product IDs does not contain any variant ID (the `iterateAllProductIdsExceptVariant()` method is used)

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +    public function dispatchProductIdsByBatches(
Doesn't this bring confusion to the developer when to use this and when a dispatchProductIds? 
What about unifying it and making it a simpler API to work with?

2025-01-05 10:12 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +class ProductRecalculationCacheFacade
I'm not sure about the use of word cache here... it's not used as a traditional cache. I would vote for `Deduplication,` so the purpose is clear, or something more describing the purpose.

2025-01-07 13:44 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +class ProductRecalculationCacheFacade
Ok. It's better. I changed it and the deduplication is using Hashes now.

2025-01-07 13:50 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +class ProductRecalculationCacheFacade
Ok, I changed the name to ProductRecalculationDeduplicationFacade

2025-01-07 13:59 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +    public function dispatchProductIdsByBatches(
Ok, dispatchProductIds is now protected and you suppose to use method dispatchProductIdsByBatches or dispatchSingleProductId

2025-01-07 14:01 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $exists = $this->productRecalculationCacheFacade->contains($productId);
It should be fixed by implementing Hashes

2025-01-07 14:01 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            if ($productRecalculationPriorityEnum === ProductRecalculationPriorityEnum::HIGH) {
yes

2025-01-07 14:07 UTC, henzigo commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        }
```suggestion
-        foreach ($productIds as $productId) {
-            $this->redisClient->hDel($this->getCacheKey(), (string)$productId);
-        }
+       $this->redisClient->hDel($this->getCacheKey(), ...$productIds);
```

2025-01-07 14:07 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        protected readonly ProductRecalculationRepository $productRecalculationRepository,
I could not use the ProductRecalculationFacade directly due to memory issues, so I left it as it is. We can have a call if you need further explanation.

2025-01-07 14:09 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationCacheFacade.php
> +                $scopes = array_unique(array_merge($scopes, explode(',', $scopesString)));
Ok, I changed it. It's better

2025-01-07 14:23 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $replaceVariantProductIds = $this->productRecalculationRepository->replaceVariantIdsWithMainVariantIds($productIdsBatch);
Yes, but I think the problem is not that significant, and I cannot think of an easy solution for it. You need to call the replacement function in all other cases anyway; only the DispatchAllProductsMessageHandler calls are unnecessary.

2025-01-08 06:54 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        }
I couldn't do it this way because hDel accepts only strings as fields, and I would have needed to convert the entire array of integers to strings.

2025-01-10 13:22 UTC, grossmannmartin requested changes

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Command/DispatchRecalculationMessageCommand.php
> +        }
the previous implementation returned truly dispatched IDs, for example if main_variant was provided, it returned main variant id and appropriate variant ids. 

What will happen when I dispatch variants from the same main variant? Do I get several identical messages?
Is there a reason why not to use batch dispatch?

All in all, the dispatchedProductIds just creates a copy of `$productIds` array, so in its current form, I think it's redundant.

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/ProductFacade.php
> +            $this->productRecalculationDispatcher->dispatchProductIdsByBatches($removedVariantIds, $priority);
I would keep the name `dispatchProductIds`. The fact that it does it "by batches" is an inner implementation that should not be a concern of a caller.

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/DispatchAffectedProductsSubscriber.php
> +            [ProductExportScopeConfig::SCOPE_UNIT, ProductExportScopeConfig::SCOPE_FLAGS],
when a change in a unit is made, flag scope should be also dispatched? 
It's unexpected

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +    public function getNotCachedKeys(array $productIds): array
Are those NOT cached keys? it seems like not cached keys are skipped (`!array_key_exist`)

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Command/DispatchRecalculationMessageCommand.php
> +            $this->productRecalculationDispatcher->dispatchSingleProductId($productId, $priority, $scopes);
`./bin/console shop:dis:rec 153 152` command returns following error

```
In ProductRecalculationDispatcher.php line 88:

  Shopsys\FrameworkBundle\Model\Product\Recalculation\ProductRecalculationDispatcher::dispatchSingleProductId(): Argument #1 ($productId) must be of type int, string given, cal
  led in /var/www/html/packages/framework/src/Command/DispatchRecalculationMessageCommand.php on line 149
```

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        $productIdsCached = $this->redisClient->hMget($this->getCacheKey(), array_map('strval', $productIds));
I'm not sure about this implementation. hmget will return the provided keys with false value even if it doesn't exist in redis... 
try 
```
d($this->redisClient->hMget($this->getCacheKey(), ['5242', '845', '9996']));
```

will return 
```
^ array:3 [
  5242 => false
  845 => false
  9996 => false
]
```

and the next code takes a false assumption about non-existing keys

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        return array_map(static fn (string|bool $scope) => $scope === false ? [] : json_decode($scope, true), $scopes);
try dispatch not-existing product id 
```
./bin/console shop:dis:rec 153 56663
```

you will get 
```
In ProductRecalculationDeduplicationFacade.php line 80:

  array_map(): Argument #2 ($array) must be of type array, false given
```

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +            $cachedScopeByProductId = $this->redisClient->hGet($this->getCacheKey(), $productId);
can we use `hmget` outside foreach?

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        protected readonly ProductRecalculationRepository $productRecalculationRepository,
I think creating the `replaceVariantIdsWithMainVariantIds` method in ProductRecalculationFacade should not cause memory issues, or?

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        $this->productRecalculationDeduplicationFacade->saveOrUpdateScopes($productIds, $scopes);
I would not expect this side-effect from a method named `filter...`

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
> +    protected function dropVariantIdsFromProductIds(array $productIds): array
this method seems unused

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
> +        return $structuredResults;
this seems more like a `Facade` code

2025-01-10 13:22 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
> +    public function getIdsToRecalculate(array $mainVariantsIds): array
Maybe I don't understand the code enough (and I truly don't understand it enough 😆 )
but wouldn't be this sql enough to get proper ids?

```
SELECT id FROM product WHERE id IN (/*main_variant_ids*/) OR main_variant_id IN (/*main_variant_ids*/)
```

2025-01-13 12:37 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        protected readonly ProductRecalculationRepository $productRecalculationRepository,
There seems to be an issue with ELS. Is using the Repository instead of the Facade a significant enough problem that I should take the time to resolve it?

2025-01-14 10:53 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
> +        return $structuredResults;
ok, method was moved to the ProductRecalculationFacade

2025-01-14 10:54 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
> +    protected function dropVariantIdsFromProductIds(array $productIds): array
removed

2025-01-14 10:54 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        $this->productRecalculationDeduplicationFacade->saveOrUpdateScopes($productIds, $scopes);
I moved it outside of the method

2025-01-14 10:57 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        protected readonly ProductRecalculationRepository $productRecalculationRepository,
This was discussed during the call, and the resolution is that we left it as it is. The Repository is used.

2025-01-14 10:58 UTC, janjavorek commented on packages/framework/src/Command/DispatchRecalculationMessageCommand.php
> +        }
dispatchedProductIds is now used, and the method also follows the batch processing principle.

2025-01-14 11:00 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +    public function getNotCachedKeys(array $productIds): array
Yes, the logic was fixed, and the method now correctly returns notCachedKeys

2025-01-14 11:04 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        $productIdsCached = $this->redisClient->hMget($this->getCacheKey(), array_map('strval', $productIds));
Yes, I fixed the code, and it should now work correctly with the response from hMget

2025-01-14 11:05 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +            $cachedScopeByProductId = $this->redisClient->hGet($this->getCacheKey(), $productId);
Yes, I moved it outside the foreach

2025-01-14 11:10 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
> +    public function getIdsToRecalculate(array $mainVariantsIds): array
I'm not sure, but this method is also supposed to work not only with main variants but also with variants and regular products, and it should return the appropriate IDs regardless of the input. I think this query might not be sufficient.

2025-01-17 13:40 UTC, grossmannmartin requested changes

2025-01-17 13:40 UTC, grossmannmartin commented on packages/framework/src/Command/DispatchRecalculationMessageCommand.php
> -        $dispatchedProductIds = $this->productRecalculationDispatcher->dispatchProductIds($productIds, $priority, $scopes);
If I dispatch a message with a non-existing scope, the command behaves like nothing is wrong, but then just silently fails and moves the message to the failed queue. 
It would be nice to check scopes before and even check if the code warns programmer if he tries to export a non-existing scope programmatically (e.g., with `dispatchProductIds` method)

2025-01-17 13:40 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +            $this->productRecalculationDispatcher->dispatchSingleProductId(
It would be nice to know that the message was consumed. Now it seems like it does nothing.

2025-01-17 13:40 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        $existingScopes = $this->getScopesByProductIds($productIds);
As we spoke, it seems like this method doesn't return the product IDs properly, causing the following code to malfunction (nothing is stored in Redis, and no deduplication takes place).

2025-01-20 09:02 UTC, janjavorek commented on packages/framework/src/Command/DispatchRecalculationMessageCommand.php
> -        $dispatchedProductIds = $this->productRecalculationDispatcher->dispatchProductIds($productIds, $priority, $scopes);
Yes, scopes are now verified before dispatching products batch

2025-01-20 09:02 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +            $this->productRecalculationDispatcher->dispatchSingleProductId(
fixed

2025-01-20 09:03 UTC, janjavorek commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        $existingScopes = $this->getScopesByProductIds($productIds);
fixed

2025-01-22 15:25 UTC, grossmannmartin requested changes, later dismissed

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        //        }
please remove the commented code

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +     * @throws \RedisException
please remove `@throws` annotation as we don't write them

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +     * @param array $productIds
```suggestion
     * @param int[] $productIds
```

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +            $cachedScopesIndexedByProductIds[(int)$productId] = $values;
I have noticed retyping to int at several places, are those necessary?

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +class ProductRecalculationDeduplicationFacade
It would be really awesome to have some tests for this class and maybe for other parts of the PR 😇

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +            $filteredProductIds = $this->filterNotCachedProductIds($replaceVariantProductIds, $productRecalculationPriorityEnum);
can't we directly use `ProductRecalculationDeduplicationFacade::getNotCachedKeys()`? 

unique on array is called twice in vain, and if we start deduplicating the high queue too, we can simplify the code a bit

2025-01-22 15:25 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationFacade.php
> +    public function getIdsToRecalculate(array $mainVariantsIds): array
if I dispatch `./bin/console shop:dis:rec 82 69` (both main variants), nothing is exported to elasticsearch. 

Also, this method seems really complex.

This method should return proper ids to recalculate - so it should return all variants, main variants and regular products?
if that's the case, I don't think why selecting by `id` or `main_variant_id` should not work 🤔  let's discuss it please

2025-02-07 14:15 UTC, vitek-rostislav requested changes
:rocket:

2025-02-07 14:15 UTC, vitek-rostislav commented on project-base/app/phpstan.neon
>              path: %currentWorkingDirectory%/tests/App/Functional/Component/Redis/Redis*FacadeTest.php
it looks like the entry below (`snc_redis.test`) should have been removed, not this one (`test.service_container`), right?

2025-02-07 14:15 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +            return;
I am wondering, this message might sometimes be a little bit misleading in the log because (if I understand it correctly) at least export scopes might have been updated here, right? Maybe (and just maybe) we could add that information here. But I am not sure whether it is worth the additional complexity. Let's discuss it please

2025-02-07 14:15 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        if ($this->isMessengerActive) {
I am wondering, does it make any sense to perform anything above when messenger is not active?

2025-02-07 14:15 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        }
Would not this do the same trick in a more elegant way?

```
foreach (array_chunk($productIds, static::DISPATCH_BATCH_SIZE) as $productIdsBatch) {
    $this->messageBus->dispatch(
        new DispatchProductIdsBatchMessage(
            $productIdsBatch,
            $exportScopes,
            $productRecalculationPriorityEnum,
        ),
    );
}
```

2025-02-07 14:15 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
> + * @internal This class is not intended to be used directly from your code
maybe we could add a hint of what should be used "instead" - `ProductRecalculationDispatcher` itself, right?

2025-02-07 14:15 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
> +        }
I do not understand this, could you explain it, please?

2025-02-07 14:15 UTC, vitek-rostislav commented on project-base/app/config/packages/snc_redis.yaml
> +        product_recalculation_queue:
is this queue persisted during deployment? In other words, is it cleaned within `clean-redis(-old)` call? :eyes: 

When I call `shopsys:redis:clean-cache`, it iterates through all the clients, including `:queue:recalculation:`, is that intentional?

2025-02-07 14:15 UTC, vitek-rostislav commented on project-base/app/tests/App/Functional/Model/Product/Recalculation/ProductRecalculationDeduplicationFacadeTest.php
> +class ProductRecalculationDeduplicationFacadeTest extends TransactionFunctionalTestCase
love it :heart_eyes:

2025-02-07 14:15 UTC, vitek-rostislav commented on upgrade-notes/backend_20250206_212223.md
> +- ensure you have Redis on version 7.4 (see #3673)
```suggestion
- ensure you have Redis on version 7.4 (see [#3673](https://github.com/shopsys/shopsys/pull/3673))
```

2025-02-07 14:15 UTC, vitek-rostislav commented on upgrade-notes/backend_20250206_212223.md
> +- `ProductRecalculationMessage` messages no longer contain `exportScopes`. Scopes are now stored in Redis.
maybe it is safer to mention the particular classes(s) - `AbstractProductRecalculationMessage` and its descendants - `ProductRecalculationPriorityHighMessage` and `ProductRecalculationPriorityRegularMessage`

2025-02-07 14:15 UTC, vitek-rostislav commented on upgrade-notes/backend_20250206_212223.md
> +- see #project-base-diff to update your project
maybe it is worth mentioning the docs as well? `docs/asynchronous-processing/product-recalculations.md`

2025-02-07 14:15 UTC, vitek-rostislav commented on docs/asynchronous-processing/product-recalculations.md
> +When a large number of product IDs, typically more than 2000, are dispatched at once due to i.e., affected changes, Shopsys Platform takes an optimized approach.
I would add something like `see the [next section](#dispatch-recalculation-message-when-an-indirect-change-is-made)` after the mention about "affected changes"

2025-02-07 14:24 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        }
array_chunk is slower 😇  

I had the same twitch and did some measurements. For large arrays, this is faster way

2025-02-07 14:30 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
> +        }
Sure... basically high priority queue is always dispatched. 

Imagine following scenario: 
- you dispatch a regular message `1`
- there are many messages, so `1` taking forever to handle
- you dispatch a high message `1`
- due to the item already present in Redis, the high message will be thrown away. 

This solves this issue with the most naive way - high is always dispatched. 
But it has some drawbacks... if a product was requested to recalculate with scope, the scope will be handled in high queue, and when the regular item is processed, it will be recalculated with all scope, because the redis entry is no longer.

I'm more than open to suggestions

2025-02-07 14:31 UTC, grossmannmartin commented on project-base/app/config/packages/snc_redis.yaml
> +        product_recalculation_queue:
most definitely not... I will look at it

2025-02-07 15:17 UTC, grossmannmartin commented on project-base/app/phpstan.neon
>              path: %currentWorkingDirectory%/tests/App/Functional/Component/Redis/Redis*FacadeTest.php
Of course... fixed in e20b7bbd3f

2025-02-07 15:37 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
> +        if ($this->isMessengerActive) {
make sense: aa092efe9e

2025-02-07 15:39 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
> + * @internal This class is not intended to be used directly from your code
good idea - 1d386b9b2b

2025-02-07 15:43 UTC, grossmannmartin commented on upgrade-notes/backend_20250206_212223.md
> +- `ProductRecalculationMessage` messages no longer contain `exportScopes`. Scopes are now stored in Redis.
6a8f07b139

2025-02-07 15:48 UTC, grossmannmartin commented on upgrade-notes/backend_20250206_212223.md
> +- see #project-base-diff to update your project
good idea - 0f39d5d369 (I have also fixed docs building error due to non-existing navigation item)

2025-02-07 15:50 UTC, grossmannmartin commented on docs/asynchronous-processing/product-recalculations.md
> +When a large number of product IDs, typically more than 2000, are dispatched at once due to i.e., affected changes, Shopsys Platform takes an optimized approach.
yup -  ca7f9a0fc9

2025-02-07 15:57 UTC, grossmannmartin commented on project-base/app/config/packages/snc_redis.yaml
> +        product_recalculation_queue:
great catch! fixed in b0874a0888

2025-02-07 16:00 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +            return;
I'm not sure, to be honest... I would need to pass back between two layers the calculated scopes to log it here... 
It's not worth from my point of view, but I'm open to discussion

2025-02-07 17:03 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
> +            return;
yeah, you have just confirmed my feelings about it, I am closing this thread

2025-02-07 17:05 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
> +        }
ok, thanks for the info :+1:

2025-02-07 17:12 UTC, vitek-rostislav commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
> +        }
let's keep this open and wait until Monday :pray:

2025-02-10 10:40 UTC, grossmannmartin commented on packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
> +        }
what about this? dfd53eced0

2025-02-10 12:07 UTC, vitek-rostislav approved these changes

2025-02-10 14:30 UTC, vitek-rostislav commented
Tested, works like a charm:

- :heavy_check_mark: product dispatched multiple times is actually processed only once thanks to the deduplication
- :heavy_check_mark: when the same product is dispatched with a different scope, the scopes are updated in the Redis queue, and then the product is processed only once with the union of the scopes
- :heavy_check_mark: priority high/regular are each duplicated separately - when a product is dispatched to the regular queue and then to the high priority queue, it is processed twice then - this is a wanted behavior
- :heavy_check_mark: batching of dispatched products - when dispatching a higher number of products at once, multiple messages with chunks of the products are dispatched with deduplication in mind (even if there were multiple product ids in the originally dispatched array, each product is correctly processed only once)

One note from testing:

- I would add information about priority to the log in `ProductRecalculationFacade::recalculate()`, what do you think?

2025-02-12 07:10 UTC, pk16011990 approved these changes

2025-02-12 11:11 UTC, merged