[project-base] add register form to payment confirmation page
shopsys/shopsys pull request #3670
Opened 2024-12-16 14:09 UTC by JanMolcik

#### Description, the reason for the PR
To fix UX, the register form is now displayed on the `order-payment-confirmation` also. This allows customers using  external payments to register after successful order creation and payment.

#### Fixes issues
... 

#### License Agreement for contributions

- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-12-16 14:12 UTC, chlebektomas requested changes

2024-12-16 14:12 UTC, chlebektomas commented on project-base/storefront/pages/order-payment-confirmation.tsx
> +    console.log(
remove the Rocketship please :D

2024-12-16 14:23 UTC, JanMolcik commented on project-base/storefront/pages/order-payment-confirmation.tsx
> +    console.log(
Thanks, forgot it there :-D

2024-12-17 07:00 UTC, chlebektomas approved these changes

2025-01-14 16:45 UTC, merged