WIP special category settings
shopsys/shopsys pull request #3672
Opened 2024-12-16 17:58 UTC by vitek-rostislav

#### Description, the reason for the PR
... 

#### Fixes issues
... 

#### License Agreement for contributions

- [ ] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

2024-12-18 07:39 UTC, grossmannmartin commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +                'expanded' => true,
we should start using `choice_translation_domain => false`

2024-12-18 07:44 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +                'expanded' => true,
Interesting. Without the setting, Symfony tries to translate the already translated choices?

2025-01-02 08:40 UTC, grossmannmartin commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +                'expanded' => true,
yup

2025-01-02 11:42 UTC, grossmannmartin requested changes
can you check the builds please?

2025-01-02 11:42 UTC, grossmannmartin commented on packages/frontend-api/src/Model/Product/BatchLoad/ProductElasticsearchBatchProvider.php
> +        }
this is a similar code as in `FilterQueryFactory::filterByCategory()`. Isn't possible to unify it? also here I would expect filterByCategory called as the method is named `...InCategory...`

2025-01-02 15:41 UTC, vitek-rostislav commented on packages/framework/src/Form/Admin/Category/CategoryFormType.php
> +                'expanded' => true,
so like this? 0e341a4d03

2025-01-02 16:16 UTC, vitek-rostislav commented on packages/frontend-api/src/Model/Product/BatchLoad/ProductElasticsearchBatchProvider.php
> +        }
nice catch! what about this? d4d0b51c9b

2025-01-02 16:18 UTC, vitek-rostislav commented on packages/frontend-api/src/Model/Product/BatchLoad/ProductElasticsearchBatchProvider.php
> +        }
and 758c55d3c9

2025-01-05 10:15 UTC, grossmannmartin commented on packages/frontend-api/src/Model/Product/BatchLoad/ProductElasticsearchBatchProvider.php
> +        }
👍

2025-01-05 10:16 UTC, grossmannmartin approved these changes

2025-01-14 14:36 UTC, merged